Bootstrap: docker
From: i386/ubuntu:18.04

%setup
    REPO_ROOT=`dirname $SINGULARITY_BUILDDEF`
    cp -r $REPO_ROOT/ $SINGULARITY_ROOTFS/planner

%post
    ## Install all dependencies.
    apt update
    apt install -y --no-install-recommends g++ make python

    cd /planner

    ## Build the planner.
    ./build

    ## Clean up.
    apt -y autoremove g++ make
    rm -rf /var/lib/apt/lists/*

%runscript
    DOMAINFILE=$1
    PROBLEMFILE=$2
    PLANFILE=$3

    /planner/plan $DOMAINFILE $PROBLEMFILE $PLANFILE
