Bootstrap: docker
From: i386/ubuntu:18.04

%setup
    REPO_ROOT=`dirname $SINGULARITY_BUILDDEF`
    cp -r $REPO_ROOT/ $SINGULARITY_ROOTFS/planner

%post
    ## Install all dependencies.
    apt update
    apt -y install cmake gawk g++ g++-multilib make python

    ## Build the planner.
    cd /planner
    ./build -j4

    ## Clean up.
    apt -y autoremove g++ make
    rm -rf /var/lib/apt/lists/*

%runscript
    DOMAINFILE=$1
    PROBLEMFILE=$2
    PLANFILE=$3

    /planner/plan.py seq-opt-symba-1 $DOMAINFILE $PROBLEMFILE $PLANFILE
