(define (problem p3_hosts_trial_1) (:domain CALDERA)
(:objects
	STR__F - STRING
	STR__S - STRING
	STR__Z - STRING
	STR__Y - STRING
	STR__JAMES - STRING
	STR__BA - STRING
	STR__BC - STRING
	STR__E - STRING
	STR__ALPHA - STRING
	STR__K - STRING
	STR__M - STRING
	STR__T - STRING
	STR__R - STRING
	STR__L - STRING
	STR__B - STRING
	ID_GHOST - OBSERVEDHOST
	ID_NHOST - OBSERVEDHOST
	ID_UHOST - OBSERVEDHOST
	ID_BLSCHTASK - OBSERVEDSCHTASK
	ID_BJSCHTASK - OBSERVEDSCHTASK
	ID_BKSCHTASK - OBSERVEDSCHTASK
	ID_ADOMAIN - OBSERVEDDOMAIN
	NUM__9 - NUM
	NUM__15 - NUM
	NUM__8 - NUM
	NUM__23 - NUM
	NUM__16 - NUM
	NUM__22 - NUM
	ID_BDSHARE - OBSERVEDSHARE
	ID_BFSHARE - OBSERVEDSHARE
	ID_BESHARE - OBSERVEDSHARE
	ID_CDOMAINUSER - OBSERVEDDOMAINUSER
	ID_BIFILE - OBSERVEDFILE
	ID_BGFILE - OBSERVEDFILE
	ID_BHFILE - OBSERVEDFILE
	ID_BBRAT - OBSERVEDRAT
	ID_BORAT - OBSERVEDRAT
	ID_BMRAT - OBSERVEDRAT
	ID_BNRAT - OBSERVEDRAT
	ID_DDOMAINCREDENTIAL - OBSERVEDDOMAINCREDENTIAL
	ID_VTIMEDELTA - OBSERVEDTIMEDELTA
	ID_OTIMEDELTA - OBSERVEDTIMEDELTA
	ID_HTIMEDELTA - OBSERVEDTIMEDELTA
)
(:init
	(KNOWS ID_BBRAT)
	(KNOWS ID_UHOST)
	(KNOWS_PROPERTY ID_BBRAT PEXECUTABLE)
	(KNOWS_PROPERTY ID_BBRAT PHOST)
	(KNOWS_PROPERTY ID_UHOST PFQDN)
	(MEM_CACHED_DOMAIN_CREDS ID_GHOST ID_DDOMAINCREDENTIAL)
	(MEM_CACHED_DOMAIN_CREDS ID_NHOST ID_DDOMAINCREDENTIAL)
	(MEM_CACHED_DOMAIN_CREDS ID_UHOST ID_DDOMAINCREDENTIAL)
	(MEM_DOMAIN_USER_ADMINS ID_GHOST ID_CDOMAINUSER)
	(MEM_DOMAIN_USER_ADMINS ID_NHOST ID_CDOMAINUSER)
	(MEM_DOMAIN_USER_ADMINS ID_UHOST ID_CDOMAINUSER)
	(MEM_HOSTS ID_ADOMAIN ID_GHOST)
	(MEM_HOSTS ID_ADOMAIN ID_NHOST)
	(MEM_HOSTS ID_ADOMAIN ID_UHOST)
	(PROP_CRED ID_CDOMAINUSER ID_DDOMAINCREDENTIAL)
	(PROP_DC ID_GHOST YES)
	(PROP_DC ID_NHOST NO)
	(PROP_DC ID_UHOST NO)
	(PROP_DNS_DOMAIN ID_ADOMAIN STR__B)
	(PROP_DNS_DOMAIN_NAME ID_GHOST STR__K)
	(PROP_DNS_DOMAIN_NAME ID_NHOST STR__R)
	(PROP_DNS_DOMAIN_NAME ID_UHOST STR__Y)
	(PROP_DOMAIN ID_CDOMAINUSER ID_ADOMAIN)
	(PROP_DOMAIN ID_DDOMAINCREDENTIAL ID_ADOMAIN)
	(PROP_DOMAIN ID_GHOST ID_ADOMAIN)
	(PROP_DOMAIN ID_NHOST ID_ADOMAIN)
	(PROP_DOMAIN ID_UHOST ID_ADOMAIN)
	(PROP_ELEVATED ID_BBRAT YES)
	(PROP_EXECUTABLE ID_BBRAT STR__BC)
	(PROP_FQDN ID_GHOST STR__L)
	(PROP_FQDN ID_NHOST STR__S)
	(PROP_FQDN ID_UHOST STR__Z)
	(PROP_HOST ID_BBRAT ID_UHOST)
	(PROP_HOST ID_HTIMEDELTA ID_GHOST)
	(PROP_HOST ID_OTIMEDELTA ID_NHOST)
	(PROP_HOST ID_VTIMEDELTA ID_UHOST)
	(PROP_HOSTNAME ID_GHOST STR__M)
	(PROP_HOSTNAME ID_NHOST STR__T)
	(PROP_HOSTNAME ID_UHOST STR__BA)
	(PROP_IS_GROUP ID_CDOMAINUSER NO)
	(PROP_MICROSECONDS ID_HTIMEDELTA NUM__8)
	(PROP_MICROSECONDS ID_OTIMEDELTA NUM__15)
	(PROP_MICROSECONDS ID_VTIMEDELTA NUM__22)
	(PROP_PASSWORD ID_DDOMAINCREDENTIAL STR__E)
	(PROP_SECONDS ID_HTIMEDELTA NUM__9)
	(PROP_SECONDS ID_OTIMEDELTA NUM__16)
	(PROP_SECONDS ID_VTIMEDELTA NUM__23)
	(PROP_SID ID_CDOMAINUSER STR__F)
	(PROP_TIMEDELTA ID_GHOST ID_HTIMEDELTA)
	(PROP_TIMEDELTA ID_NHOST ID_OTIMEDELTA)
	(PROP_TIMEDELTA ID_UHOST ID_VTIMEDELTA)
	(PROP_USER ID_DDOMAINCREDENTIAL ID_CDOMAINUSER)
	(PROP_USERNAME ID_CDOMAINUSER STR__JAMES)
	(PROP_WINDOWS_DOMAIN ID_ADOMAIN STR__ALPHA)
	(procnone)
(= (total-cost) 0)
)
(:goal (and (procnone) (PROP_HOST ID_BORAT ID_GHOST)(PROP_HOST ID_BNRAT ID_NHOST)))
(:metric minimize (total-cost))

)
