(define (problem p2_hosts_trial_1) (:domain CALDERA)
(:objects
	NUM__16 - NUM
	NUM__9 - NUM
	NUM__15 - NUM
	NUM__8 - NUM
	ID_XSHARE - OBSERVEDSHARE
	ID_WSHARE - OBSERVEDSHARE
	ID_NHOST - OBSERVEDHOST
	ID_GHOST - OBSERVEDHOST
	ID_CDOMAINUSER - OBSERVEDDOMAINUSER
	STR__K - STRING
	STR__M - STRING
	STR__E - STRING
	STR__S - STRING
	STR__B - STRING
	STR__ALPHA - STRING
	STR__R - STRING
	STR__T - STRING
	STR__V - STRING
	STR__F - STRING
	STR__JAMES - STRING
	STR__L - STRING
	ID_URAT - OBSERVEDRAT
	ID_BARAT - OBSERVEDRAT
	ID_BBRAT - OBSERVEDRAT
	ID_BDFILE - OBSERVEDFILE
	ID_BCFILE - OBSERVEDFILE
	ID_YSCHTASK - OBSERVEDSCHTASK
	ID_ZSCHTASK - OBSERVEDSCHTASK
	ID_OTIMEDELTA - OBSERVEDTIMEDELTA
	ID_HTIMEDELTA - OBSERVEDTIMEDELTA
	ID_DDOMAINCREDENTIAL - OBSERVEDDOMAINCREDENTIAL
	ID_ADOMAIN - OBSERVEDDOMAIN
)
(:init
	(KNOWS ID_NHOST)
	(KNOWS ID_URAT)
	(KNOWS_PROPERTY ID_NHOST PFQDN)
	(KNOWS_PROPERTY ID_URAT PEXECUTABLE)
	(KNOWS_PROPERTY ID_URAT PHOST)
	(MEM_CACHED_DOMAIN_CREDS ID_GHOST ID_DDOMAINCREDENTIAL)
	(MEM_CACHED_DOMAIN_CREDS ID_NHOST ID_DDOMAINCREDENTIAL)
	(MEM_DOMAIN_USER_ADMINS ID_GHOST ID_CDOMAINUSER)
	(MEM_DOMAIN_USER_ADMINS ID_NHOST ID_CDOMAINUSER)
	(MEM_HOSTS ID_ADOMAIN ID_GHOST)
	(MEM_HOSTS ID_ADOMAIN ID_NHOST)
	(PROP_CRED ID_CDOMAINUSER ID_DDOMAINCREDENTIAL)
	(PROP_DC ID_GHOST YES)
	(PROP_DC ID_NHOST NO)
	(PROP_DNS_DOMAIN ID_ADOMAIN STR__B)
	(PROP_DNS_DOMAIN_NAME ID_GHOST STR__K)
	(PROP_DNS_DOMAIN_NAME ID_NHOST STR__R)
	(PROP_DOMAIN ID_CDOMAINUSER ID_ADOMAIN)
	(PROP_DOMAIN ID_DDOMAINCREDENTIAL ID_ADOMAIN)
	(PROP_DOMAIN ID_GHOST ID_ADOMAIN)
	(PROP_DOMAIN ID_NHOST ID_ADOMAIN)
	(PROP_ELEVATED ID_URAT YES)
	(PROP_EXECUTABLE ID_URAT STR__V)
	(PROP_FQDN ID_GHOST STR__M)
	(PROP_FQDN ID_NHOST STR__T)
	(PROP_HOST ID_HTIMEDELTA ID_GHOST)
	(PROP_HOST ID_OTIMEDELTA ID_NHOST)
	(PROP_HOST ID_URAT ID_NHOST)
	(PROP_HOSTNAME ID_GHOST STR__L)
	(PROP_HOSTNAME ID_NHOST STR__S)
	(PROP_IS_GROUP ID_CDOMAINUSER NO)
	(PROP_MICROSECONDS ID_HTIMEDELTA NUM__8)
	(PROP_MICROSECONDS ID_OTIMEDELTA NUM__15)
	(PROP_PASSWORD ID_DDOMAINCREDENTIAL STR__E)
	(PROP_SECONDS ID_HTIMEDELTA NUM__9)
	(PROP_SECONDS ID_OTIMEDELTA NUM__16)
	(PROP_SID ID_CDOMAINUSER STR__F)
	(PROP_TIMEDELTA ID_GHOST ID_HTIMEDELTA)
	(PROP_TIMEDELTA ID_NHOST ID_OTIMEDELTA)
	(PROP_USER ID_DDOMAINCREDENTIAL ID_CDOMAINUSER)
	(PROP_USERNAME ID_CDOMAINUSER STR__JAMES)
	(PROP_WINDOWS_DOMAIN ID_ADOMAIN STR__ALPHA)
	(procnone)
(= (total-cost) 0)
)
(:goal (and (procnone) (PROP_HOST ID_BBRAT ID_GHOST)))
(:metric minimize (total-cost))

)
