(define (problem p2_hosts_trial_4) (:domain CALDERA)
(:objects
	ID_ADOMAIN - OBSERVEDDOMAIN
	ID_HDOMAINCREDENTIAL - OBSERVEDDOMAINCREDENTIAL
	ID_DDOMAINCREDENTIAL - OBSERVEDDOMAINCREDENTIAL
	ID_KHOST - OBSERVEDHOST
	ID_RHOST - OBSERVEDHOST
	NUM__13 - NUM
	NUM__20 - NUM
	NUM__19 - NUM
	NUM__12 - NUM
	ID_BFFILE - OBSERVEDFILE
	ID_BEFILE - OBSERVEDFILE
	ID_BHSHARE - OBSERVEDSHARE
	ID_BGSHARE - OBSERVEDSHARE
	ID_BBRAT - OBSERVEDRAT
	ID_BARAT - OBSERVEDRAT
	ID_YRAT - OBSERVEDRAT
	ID_BCSCHTASK - OBSERVEDSCHTASK
	ID_BDSCHTASK - OBSERVEDSCHTASK
	ID_LTIMEDELTA - OBSERVEDTIMEDELTA
	ID_STIMEDELTA - OBSERVEDTIMEDELTA
	ID_CDOMAINUSER - OBSERVEDDOMAINUSER
	ID_GDOMAINUSER - OBSERVEDDOMAINUSER
	STR__Q - STRING
	STR__Z - STRING
	STR__J - STRING
	STR__E - STRING
	STR__ALPHA - STRING
	STR__MARY - STRING
	STR__I - STRING
	STR__JAMES - STRING
	STR__X - STRING
	STR__P - STRING
	STR__B - STRING
	STR__F - STRING
	STR__O - STRING
	STR__W - STRING
	STR__V - STRING
)
(:init
	(KNOWS ID_KHOST)
	(KNOWS ID_YRAT)
	(KNOWS_PROPERTY ID_KHOST PFQDN)
	(KNOWS_PROPERTY ID_YRAT PEXECUTABLE)
	(KNOWS_PROPERTY ID_YRAT PHOST)
	(MEM_CACHED_DOMAIN_CREDS ID_KHOST ID_DDOMAINCREDENTIAL)
	(MEM_CACHED_DOMAIN_CREDS ID_KHOST ID_HDOMAINCREDENTIAL)
	(MEM_CACHED_DOMAIN_CREDS ID_RHOST ID_DDOMAINCREDENTIAL)
	(MEM_CACHED_DOMAIN_CREDS ID_RHOST ID_HDOMAINCREDENTIAL)
	(MEM_DOMAIN_USER_ADMINS ID_KHOST ID_CDOMAINUSER)
	(MEM_DOMAIN_USER_ADMINS ID_KHOST ID_GDOMAINUSER)
	(MEM_DOMAIN_USER_ADMINS ID_RHOST ID_CDOMAINUSER)
	(MEM_DOMAIN_USER_ADMINS ID_RHOST ID_GDOMAINUSER)
	(MEM_HOSTS ID_ADOMAIN ID_KHOST)
	(MEM_HOSTS ID_ADOMAIN ID_RHOST)
	(PROP_CRED ID_CDOMAINUSER ID_DDOMAINCREDENTIAL)
	(PROP_CRED ID_GDOMAINUSER ID_HDOMAINCREDENTIAL)
	(PROP_DC ID_KHOST NO)
	(PROP_DC ID_RHOST YES)
	(PROP_DNS_DOMAIN ID_ADOMAIN STR__B)
	(PROP_DNS_DOMAIN_NAME ID_KHOST STR__P)
	(PROP_DNS_DOMAIN_NAME ID_RHOST STR__W)
	(PROP_DOMAIN ID_CDOMAINUSER ID_ADOMAIN)
	(PROP_DOMAIN ID_DDOMAINCREDENTIAL ID_ADOMAIN)
	(PROP_DOMAIN ID_GDOMAINUSER ID_ADOMAIN)
	(PROP_DOMAIN ID_HDOMAINCREDENTIAL ID_ADOMAIN)
	(PROP_DOMAIN ID_KHOST ID_ADOMAIN)
	(PROP_DOMAIN ID_RHOST ID_ADOMAIN)
	(PROP_ELEVATED ID_YRAT YES)
	(PROP_EXECUTABLE ID_YRAT STR__Z)
	(PROP_FQDN ID_KHOST STR__O)
	(PROP_FQDN ID_RHOST STR__V)
	(PROP_HOST ID_LTIMEDELTA ID_KHOST)
	(PROP_HOST ID_STIMEDELTA ID_RHOST)
	(PROP_HOST ID_YRAT ID_KHOST)
	(PROP_HOSTNAME ID_KHOST STR__Q)
	(PROP_HOSTNAME ID_RHOST STR__X)
	(PROP_IS_GROUP ID_CDOMAINUSER NO)
	(PROP_IS_GROUP ID_GDOMAINUSER NO)
	(PROP_MICROSECONDS ID_LTIMEDELTA NUM__12)
	(PROP_MICROSECONDS ID_STIMEDELTA NUM__19)
	(PROP_PASSWORD ID_DDOMAINCREDENTIAL STR__E)
	(PROP_PASSWORD ID_HDOMAINCREDENTIAL STR__I)
	(PROP_SECONDS ID_LTIMEDELTA NUM__13)
	(PROP_SECONDS ID_STIMEDELTA NUM__20)
	(PROP_SID ID_CDOMAINUSER STR__F)
	(PROP_SID ID_GDOMAINUSER STR__J)
	(PROP_TIMEDELTA ID_KHOST ID_LTIMEDELTA)
	(PROP_TIMEDELTA ID_RHOST ID_STIMEDELTA)
	(PROP_USER ID_DDOMAINCREDENTIAL ID_CDOMAINUSER)
	(PROP_USER ID_HDOMAINCREDENTIAL ID_GDOMAINUSER)
	(PROP_USERNAME ID_CDOMAINUSER STR__JAMES)
	(PROP_USERNAME ID_GDOMAINUSER STR__MARY)
	(PROP_WINDOWS_DOMAIN ID_ADOMAIN STR__ALPHA)
	(procnone)
(= (total-cost) 0)
)
(:goal (and (procnone) (PROP_HOST ID_BBRAT ID_RHOST)))
(:metric minimize (total-cost))

)
