#!/bin/bash

set -eu

INSTANCE=$1
DOMAIN="$(dirname $INSTANCE)/domain-$(basename $INSTANCE)"

sed -i -e "s/( :REQUIREMENTS :ACTION-COSTS :CONDITIONAL-EFFECTS :TYPING )/( :REQUIREMENTS :ACTION-COSTS :CONDITIONAL-EFFECTS :TYPING :NEGATIVE-PRECONDITIONS :ADL)/g" $DOMAIN
