./bin/compile PLPR domains/excel_variables/domain_variables.pddl 3 domains/excel_variables/extract-minutes-3.pddl domains/excel_variables/extract-minutes-4.pddl domains/excel_variables/extract-minutes-5.pddl 4 4 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-extract-minutes-3-4.pddl 2> ipc-instances/extract-minutes-3-4.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 3 domains/excel_variables/extract-minutes-3.pddl domains/excel_variables/extract-minutes-4.pddl domains/excel_variables/extract-minutes-5.pddl 5 5 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-extract-minutes-3-5.pddl 2> ipc-instances/extract-minutes-3-5.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 3 domains/excel_variables/extract-minutes-3.pddl domains/excel_variables/extract-minutes-4.pddl domains/excel_variables/extract-minutes-5.pddl 6 6 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-extract-minutes-3-6.pddl 2> ipc-instances/extract-minutes-3-6.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/extract-minutes-1.pddl domains/excel_variables/extract-minutes-2.pddl 4 4 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-extract-minutes-2-4.pddl 2> ipc-instances/extract-minutes-2-4.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/extract-minutes-1.pddl domains/excel_variables/extract-minutes-2.pddl 5 5 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-extract-minutes-2-5.pddl 2> ipc-instances/extract-minutes-2-5.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/extract-minutes-1.pddl domains/excel_variables/extract-minutes-2.pddl 6 6 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-extract-minutes-2-6.pddl 2> ipc-instances/extract-minutes-2-6.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 5 domains/excel_variables/extract-minutes-1.pddl domains/excel_variables/extract-minutes-3.pddl domains/excel_variables/extract-minutes-5.pddl domains/excel_variables/extract-minutes-7.pddl domains/excel_variables/extract-minutes-9.pddl 4 4 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-extract-minutes-5-4.pddl 2> ipc-instances/extract-minutes-5-4.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 5 domains/excel_variables/extract-minutes-1.pddl domains/excel_variables/extract-minutes-3.pddl domains/excel_variables/extract-minutes-5.pddl domains/excel_variables/extract-minutes-7.pddl domains/excel_variables/extract-minutes-9.pddl 5 5 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-extract-minutes-5-5.pddl 2> ipc-instances/extract-minutes-5-5.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 5 domains/excel_variables/extract-minutes-1.pddl domains/excel_variables/extract-minutes-3.pddl domains/excel_variables/extract-minutes-5.pddl domains/excel_variables/extract-minutes-7.pddl domains/excel_variables/extract-minutes-9.pddl 6 6 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-extract-minutes-5-6.pddl 2> ipc-instances/extract-minutes-5-6.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 4 domains/excel_variables/extract-minutes-6.pddl domains/excel_variables/extract-minutes-7.pddl domains/excel_variables/extract-minutes-8.pddl domains/excel_variables/extract-minutes-9.pddl 4 4 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-extract-minutes-4-4.pddl 2> ipc-instances/extract-minutes-4-4.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 4 domains/excel_variables/extract-minutes-6.pddl domains/excel_variables/extract-minutes-7.pddl domains/excel_variables/extract-minutes-8.pddl domains/excel_variables/extract-minutes-9.pddl 5 5 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-extract-minutes-4-5.pddl 2> ipc-instances/extract-minutes-4-5.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 4 domains/excel_variables/extract-minutes-6.pddl domains/excel_variables/extract-minutes-7.pddl domains/excel_variables/extract-minutes-8.pddl domains/excel_variables/extract-minutes-9.pddl 6 6 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-extract-minutes-4-6.pddl 2> ipc-instances/extract-minutes-4-6.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/initials-3-3.pddl domains/excel_variables/initials-3-4.pddl 3 3 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-initials-2a-3.pddl 2> ipc-instances/initials-2a-3.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/initials-3-3.pddl domains/excel_variables/initials-3-4.pddl 4 4 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-initials-2a-4.pddl 2> ipc-instances/initials-2a-4.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/initials-3-3.pddl domains/excel_variables/initials-3-4.pddl 5 5 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-initials-2a-5.pddl 2> ipc-instances/initials-2a-5.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/initials-4-5.pddl domains/excel_variables/initials-6-5.pddl 3 3 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-initials-2b-3.pddl 2> ipc-instances/initials-2b-3.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/initials-4-5.pddl domains/excel_variables/initials-6-5.pddl 4 4 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-initials-2b-4.pddl 2> ipc-instances/initials-2b-4.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/initials-4-5.pddl domains/excel_variables/initials-6-5.pddl 5 5 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-initials-2b-5.pddl 2> ipc-instances/initials-2b-5.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/first-last-initial-3-5.pddl domains/excel_variables/first-last-initial-3-6.pddl 6 6 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-first-last-initial-2b-6.pddl 2> ipc-instances/first-last-initial-2b-6.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/first-last-initial-3-5.pddl domains/excel_variables/first-last-initial-3-6.pddl 7 7 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-first-last-initial-2b-7.pddl 2> ipc-instances/first-last-initial-2b-7.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/first-last-initial-3-5.pddl domains/excel_variables/first-last-initial-3-6.pddl 8 8 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-first-last-initial-2b-8.pddl 2> ipc-instances/first-last-initial-2b-8.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/first-last-initial-3-3.pddl domains/excel_variables/first-last-initial-3-4.pddl 6 6 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-first-last-initial-2a-6.pddl 2> ipc-instances/first-last-initial-2a-6.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/first-last-initial-3-3.pddl domains/excel_variables/first-last-initial-3-4.pddl 7 7 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-first-last-initial-2a-7.pddl 2> ipc-instances/first-last-initial-2a-7.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/first-last-initial-3-3.pddl domains/excel_variables/first-last-initial-3-4.pddl 8 8 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-first-last-initial-2a-8.pddl 2> ipc-instances/first-last-initial-2a-8.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 3 domains/excel_variables/initials-3-4.pddl domains/excel_variables/initials-3-5.pddl domains/excel_variables/initials-4-4.pddl 3 3 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-initials-3-3.pddl 2> ipc-instances/initials-3-3.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 3 domains/excel_variables/initials-3-4.pddl domains/excel_variables/initials-3-5.pddl domains/excel_variables/initials-4-4.pddl 4 4 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-initials-3-4.pddl 2> ipc-instances/initials-3-4.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 3 domains/excel_variables/initials-3-4.pddl domains/excel_variables/initials-3-5.pddl domains/excel_variables/initials-4-4.pddl 5 5 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-initials-3-5.pddl 2> ipc-instances/initials-3-5.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/add-paren-3-2.pddl domains/excel_variables/add-paren-3-3.pddl 4 4 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-add-paren-2a-4.pddl 2> ipc-instances/add-paren-2a-4.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/add-paren-3-2.pddl domains/excel_variables/add-paren-3-3.pddl 5 5 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-add-paren-2a-5.pddl 2> ipc-instances/add-paren-2a-5.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/add-paren-3-2.pddl domains/excel_variables/add-paren-3-3.pddl 6 6 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-add-paren-2a-6.pddl 2> ipc-instances/add-paren-2a-6.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/add-paren-4-1.pddl domains/excel_variables/add-paren-5-1.pddl 4 4 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-add-paren-2b-4.pddl 2> ipc-instances/add-paren-2b-4.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/add-paren-4-1.pddl domains/excel_variables/add-paren-5-1.pddl 5 5 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-add-paren-2b-5.pddl 2> ipc-instances/add-paren-2b-5.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 2 domains/excel_variables/add-paren-4-1.pddl domains/excel_variables/add-paren-5-1.pddl 6 6 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-add-paren-2b-6.pddl 2> ipc-instances/add-paren-2b-6.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 3 domains/excel_variables/add-paren-4-2.pddl domains/excel_variables/add-paren-5-3.pddl domains/excel_variables/add-paren-5-4.pddl 4 4 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-add-paren-3b-4.pddl 2> ipc-instances/add-paren-3b-4.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 3 domains/excel_variables/add-paren-4-2.pddl domains/excel_variables/add-paren-5-3.pddl domains/excel_variables/add-paren-5-4.pddl 5 5 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-add-paren-3b-5.pddl 2> ipc-instances/add-paren-3b-5.pddl
./bin/compile PLPR domains/excel_variables/domain_variables.pddl 3 domains/excel_variables/add-paren-4-2.pddl domains/excel_variables/add-paren-5-3.pddl domains/excel_variables/add-paren-5-4.pddl 6 6 0 1 INPUT-ASSIGNMENT 1 INPUT-VARIABLE 2 1 0 0 0 > ipc-instances/domain-add-paren-3b-6.pddl 2> ipc-instances/add-paren-3b-6.pddl
