; Domain designed by Yannis Dimopoulos, Alfonso Gerevini and Alessandro Saetti
; This file has been automatically generated by the generator available from
; http://zeus.ing.unibs.it/ipc-5/generators/index.html

(define (problem Pathways-Problem)
(:domain Pathways-Propositional)
(:objects
    pRb-E2F4p1-DP12 - simple
    HDAC1 - simple
    l0 - level
    l1 - level
    l2 - level)


(:init
    (possible pRb-E2F4p1-DP12)
    (possible HDAC1)
    (association-reaction HDAC1 pRb-E2F4p1-DP12 HDAC1-pRb-E2F4p1-DP12)
    (num-subs l0)
    (next l1 l0)
    (next l2 l1))


(:goal
    (and
    (goal1)))

)
