; Domain designed by Yannis Dimopoulos, Alfonso Gerevini and Alessandro Saetti
; This file has been automatically generated by the generator available from
; http://zeus.ing.unibs.it/ipc-5/generators/index.html

(define (problem Pathways-Problem)
(:domain Pathways-Propositional)
(:objects
    Wee1 - simple
    SP1 - simple
    SL1 - simple
    Skp2 - simple
    Skp1 - simple
    RPA - simple
    Raf1 - simple
    pRbp2 - simple
    pRbp1-E2F4p1-DP12 - simple
    pRb-E2F4p1-DP12 - simple
    pRb - simple
    Plk1 - simple
    PCNA - simple
    pCAF - simple
    p68 - simple
    p57p1 - simple
    p57 - simple
    p53p1 - simple
    p53 - simple
    p300 - simple
    p27 - simple
    p16 - simple
    p130-E2F5p1-DP12 - simple
    p130-E2F4p1-DP12 - simple
    p130 - simple
    Myt1 - simple
    Max - simple
    m1433 - simple
    Jun - simple
    HDAC1-pRbp1-E2F4-DP12 - simple
    HDAC1-pRbp1-E2F13p1-DP12 - simple
    HDAC1-pRbp1-E2F13-DP12 - simple
    HDAC1-p130-E2F5p1-DP12 - simple
    HDAC1-p130-E2F4p1-DP12 - simple
    HDAC1-p107-E2F4p1-DP12 - simple
    HDAC1 - simple
    HBP1 - simple
    gp19ARF - simple
    gP - simple
    gERCC1 - simple
    gE-c - simple
    gE2 - simple
    gcdc25A - simple
    E2F6-DP12p1 - simple
    E2F6 - simple
    E2F5-DP12p1 - simple
    E2F5 - simple
    E2F4-DP12p1 - simple
    E2F4 - simple
    E2F3 - simple
    E2F2 - simple
    E2F13p1-DP12p1 - simple
    E2F13p1-DP12 - simple
    E2F13-DP12p1 - simple
    E2F13-DP12 - simple
    E2F13 - simple
    E2F1 - simple
    DP12 - simple
    DMP1 - simple
    cycH - simple
    cycB - simple
    C-TAK1 - simple
    cks1 - simple
    Chk1 - simple
    CEBP - simple
    cdk7 - simple
    cdk46p3-cycDp1 - simple
    cdk46p3-cycD - simple
    cdk46p1 - simple
    cdk2p2-cycB - simple
    cdk2p1 - simple
    cdk2-cycB - simple
    cdk2 - simple
    cdk1p1p2 - simple
    cdc25C - simple
    c-Abl - simple
    APC - simple
    AP2 - simple
    AP2-gE-c - complex
    c-Abl-pRb - complex
    c-Abl-pRbp1 - complex
    c-Abl-pRbp1p2 - complex
    c-Abl-pRbp2 - complex
    cdk1-cks1 - complex
    cdk1-Gadd45 - complex
    cdk1p1-cks1 - complex
    cdk1p1-Gadd45 - complex
    cdk1p1 - complex
    cdk1p1p2-cks1 - complex
    cdk1p1p2-Gadd45 - complex
    cdk1p1p2p3-cks1 - complex
    cdk1p1p2p3-Gadd45 - complex
    cdk1p1p2p3 - complex
    cdk1p1p3-Gadd45 - complex
    cdk1p1p3 - complex
    cdk1 - complex
    cdk1p2-cks1 - complex
    cdk1p2-Gadd45 - complex
    cdk1p2 - complex
    cdk1p2p3-cks1 - complex
    cdk1p1p2p3-cycA - complex
    cdc25Cp1 - complex
    cdk1p1p2p3-cycB - complex
    cdk1p2p3-Gadd45 - complex
    cdk1p2p3 - complex
    cdk1p3-cks1 - complex
    cdk1p1p3-cycA - complex
    cdk1p2p3-cycA - complex
    cdk1p1p3-cycB - complex
    cdk1p2p3-cycB - complex
    cdk1p3-Gadd45 - complex
    cdk1p3 - complex
    cdk2-cks1 - complex
    cdk2-cycA-E2F13 - complex
    cdk2-cycA-E2F13p1 - complex
    cdk2p1-cycB - complex
    cdk2p1-cks1 - complex
    cdk2p1-cycA-E2F13 - complex
    cdk2p1-cycA-E2F13p1 - complex
    cdk2p1p2-cks1 - complex
    cdk2p1p2-cycA-E2F13 - complex
    cdk2p1p2-cycA-E2F13p1 - complex
    cdk2p1p2 - complex
    cdk2p2-cks1 - complex
    cdk2p2-cycA-E2F13 - complex
    cdk2p2-cycA-E2F13p1 - complex
    cdk2p1p2-cycB - complex
    cdk2p2 - complex
    cdk7-cycH - complex
    cdk7p1-cycH - complex
    CEBP-gP - complex
    CEBP-pRb - complex
    CEBP-pRb-gP - complex
    CEBP-pRbp1 - complex
    CEBP-pRbp1-gP - complex
    CEBP-pRbp1p2 - complex
    CEBP-pRbp1p2-gP - complex
    CEBP-pRbp2 - complex
    P - complex
    CEBP-pRbp2-gP - complex
    c-Myc-AP2 - complex
    c-Myc-Max-gcdc25A - complex
    c-Myc-Max - complex
    APCp1 - complex
    DMP1-cycD - complex
    DMP1-cycDp1 - complex
    DMP1-gp19ARF - complex
    DMP1p1-cycD - complex
    DMP1p1-cycDp1 - complex
    DMP1p1 - complex
    DMP1p1-gp19ARF - complex
    E2F13-DP12-gE2 - complex
    E2F13p1-DP12-gE2 - complex
    E2F1-DP12 - complex
    E2F2-DP12 - complex
    E2F3-DP12 - complex
    E2F4-DP12-gE2 - complex
    E2F5-DP12-gE2 - complex
    E2F6-DP12-gE2 - complex
    E2F6-DP12 - complex
    E2F6-DP12p1-gE2 - complex
    HBP1-p130 - complex
    HDAC1-p107-E2F4-DP12-gE2 - complex
    HDAC1-p107-E2F4-DP12 - complex
    HDAC1-p107-E2F4-DP12p1 - complex
    HDAC1-p107-E2F4p1-DP12-gE2 - complex
    HDAC1-p130-E2F4-DP12-gE2 - complex
    HDAC1-p130-E2F4-DP12 - complex
    HDAC1-p130-E2F4-DP12p1 - complex
    HDAC1-p130-E2F4p1-DP12-gE2 - complex
    HDAC1-p130-E2F5-DP12-gE2 - complex
    HDAC1-p130-E2F5-DP12 - complex
    HDAC1-p130-E2F5-DP12p1 - complex
    HDAC1-p130-E2F5p1-DP12-gE2 - complex
    HDAC1-pRb-E2F13-DP12-gE2 - complex
    HDAC1-pRb-E2F13-DP12 - complex
    HDAC1-pRb-E2F13-DP12p1 - complex
    HDAC1-pRb-E2F13p1-DP12-gE2 - complex
    HDAC1-pRb-E2F13p1-DP12 - complex
    HDAC1-pRb-E2F13p1-DP12p1 - complex
    HDAC1-pRb-E2F4-DP12-gE2 - complex
    HDAC1-pRb-E2F4-DP12 - complex
    HDAC1-pRb-E2F4p1-DP12 - complex
    HDAC1-pRbp1-E2F13-DP12-gE2 - complex
    HDAC1-pRbp1-E2F13p1-DP12-gE2 - complex
    HDAC1-pRbp1-E2F4-DP12-gE2 - complex
    Jun-c-Fos-gERCC1 - complex
    Jun-c-Fos - complex
    m1433-cdc25Cp1p2 - complex
    cdc25Cp1p2 - complex
    m1433-cdc25Cp2 - complex
    cdc25Cp2 - complex
    Mdm2-E2F13-DP12 - complex
    Mdm2-E2F13-DP12p1 - complex
    Mdm2-E2F13p1-DP12 - complex
    Mdm2-E2F13p1-DP12p1 - complex
    Mdm2-pRb - complex
    Mdm2-pRbp1 - complex
    Mdm2-pRbp1p2 - complex
    Mdm2-pRbp2 - complex
    p107-E2F4-DP12-gE2 - complex
    p107-E2F4-DP12 - complex
    p107-E2F4-DP12p1-gE2 - complex
    p107-E2F4-DP12p1 - complex
    p130-E2F4-DP12-gE2 - complex
    p130-E2F4-DP12p1-gE2 - complex
    p130-E2F4-DP12p1 - complex
    p130-E2F5-DP12-gE2 - complex
    E2F5-DP12 - complex
    p130-E2F5-DP12p1-gE2 - complex
    p130-E2F5-DP12p1 - complex
    p16-cdk46p1 - complex
    p16-cdk46p1p2 - complex
    cdk46p1p2 - complex
    p16-cdk46p2 - complex
    cdk46p2 - complex
    p16-cdk7 - complex
    p16-cdk7p1 - complex
    cdk7p1 - complex
    p21-cdk2-cycA - complex
    p21-cdk2-cycEp1 - complex
    p21-cdk2-cycE - complex
    p21-cdk2p1-cycA - complex
    p21-cdk2p1-cycEp1 - complex
    p21-cdk2p1-cycE - complex
    p21-cdk2p1p2-cycA - complex
    p21-cdk2p1p2-cycEp1 - complex
    p21-cdk2p1p2-cycE - complex
    p21-cdk2p2-cycA - complex
    p21-cdk2p2-cycEp1 - complex
    p21-cdk2p2-cycE - complex
    p21-cdk46-cycDp1 - complex
    p21-cdk46-cycD - complex
    p21-cdk46p1-cycDp1 - complex
    p21-cdk46p1-cycD - complex
    p21-cdk46p1p2-cycDp1 - complex
    p21-cdk46p1p2-cycD - complex
    p21-cdk46p2-cycDp1 - complex
    p21-cdk46p2-cycD - complex
    p21-Gadd45 - complex
    p27-cdk2-cycA - complex
    p27-cdk2-cycEp1 - complex
    p27-cdk2-cycE - complex
    p27-cdk2p1-cycA - complex
    p27-cdk2p1-cycEp1 - complex
    p27-cdk2p1-cycE - complex
    p27-cdk2p1p2-cycA - complex
    p27-cdk2p1p2-cycEp1 - complex
    p27-cdk2p1p2-cycE - complex
    p27-cdk2p2-cycA - complex
    p27-cdk2p2-cycEp1 - complex
    p27-cdk2p2-cycE - complex
    p27-cdk46-cycDp1 - complex
    p27-cdk46-cycD - complex
    p27-cdk46p1-cycDp1 - complex
    p27-cdk46p1-cycD - complex
    p27-cdk46p1p2-cycDp1 - complex
    p27-cdk46p1p2-cycD - complex
    p27-cdk46p2-cycDp1 - complex
    p27-cdk46p2-cycD - complex
    p27p1-cdk2-cycA - complex
    p27p1-cdk2-cycEp1 - complex
    p27p1-cdk2-cycE - complex
    p27p1-cdk2p1-cycA - complex
    p27p1-cdk2p1-cycEp1 - complex
    p27p1-cdk2p1-cycE - complex
    p27p1-cdk2p1p2-cycA - complex
    p27p1-cdk2p1p2-cycEp1 - complex
    p27p1-cdk2p1p2-cycE - complex
    p27p1-cdk2p2-cycA - complex
    p27p1-cdk2p2-cycEp1 - complex
    p27p1-cdk2p2-cycE - complex
    p27p1-cdk46-cycDp1 - complex
    p27p1-cdk46-cycD - complex
    p27p1-cdk46p1-cycDp1 - complex
    p27p1-cdk46p1-cycD - complex
    p27p1-cdk46p1p2-cycDp1 - complex
    p27p1-cdk46p1p2-cycD - complex
    p27p1-cdk46p2-cycDp1 - complex
    p27p1-cdk46p2-cycD - complex
    p27p1 - complex
    p53-DP12p1 - complex
    p53-DP12 - complex
    p53p1-DP12p1 - complex
    DP12p1 - complex
    p53p1-DP12 - complex
    Mdm2 - complex
    p57-cdk2-cycA - complex
    p57-cdk2-cycEp1 - complex
    p57-cdk2-cycE - complex
    p57-cdk2p1-cycA - complex
    p57-cdk2p1-cycEp1 - complex
    p57-cdk2p1-cycE - complex
    p57-cdk2p1p2-cycA - complex
    p57-cdk2p1p2-cycEp1 - complex
    p57-cdk2p1p2-cycE - complex
    p57-cdk2p2-cycA - complex
    p57-cdk2p2-cycEp1 - complex
    p57-cdk2p2-cycE - complex
    p57-cdk46-cycDp1 - complex
    p57-cdk46-cycD - complex
    p57-cdk46p1-cycDp1 - complex
    p57-cdk46p1-cycD - complex
    p57-cdk46p1p2-cycDp1 - complex
    p57-cdk46p1p2-cycD - complex
    p57-cdk46p2-cycDp1 - complex
    p57-cdk46p2-cycD - complex
    p57p1-cdk46-cycDp1 - complex
    p57p1-cdk46-cycD - complex
    p57p1-cdk46p1-cycDp1 - complex
    p57p1-cdk46p1-cycD - complex
    p57p1-cdk46p1p2-cycDp1 - complex
    p57p1-cdk46p1p2-cycD - complex
    p57p1-cdk46p2-cycDp1 - complex
    p57p1-cdk46p2-cycD - complex
    p68p1 - complex
    p68p1p2 - complex
    p68p2 - complex
    pCAF-p300 - complex
    PCNA-cycDp1 - complex
    PCNA-cycD - complex
    PCNA-Gadd45 - complex
    Gadd45 - complex
    PCNA-p21-cdk2-cycA - complex
    PCNA-p21-cdk2-cycEp1 - complex
    cdk2-cycEp1 - complex
    PCNA-p21-cdk2-cycE - complex
    cdk2-cycE - complex
    PCNA-p21-cdk2p1-cycA - complex
    PCNA-p21-cdk2p1-cycEp1 - complex
    cdk2p1-cycEp1 - complex
    PCNA-p21-cdk2p1-cycE - complex
    cdk2p1-cycE - complex
    PCNA-p21-cdk2p1p2-cycA - complex
    PCNA-p21-cdk2p1p2-cycEp1 - complex
    cdk2p1p2-cycEp1 - complex
    PCNA-p21-cdk2p1p2-cycE - complex
    cdk2p1p2-cycE - complex
    PCNA-p21-cdk2p2-cycA - complex
    PCNA-p21-cdk2p2-cycEp1 - complex
    PCNA-p21-cdk2p2-cycE - complex
    PCNA-p21-cdk46-cycDp1 - complex
    PCNA-p21-cdk46-cycD - complex
    cdk46-cycD - complex
    PCNA-p21-cdk46p1-cycDp1 - complex
    cdk46p1-cycDp1 - complex
    PCNA-p21-cdk46p1-cycD - complex
    cdk46p1-cycD - complex
    PCNA-p21-cdk46p1p2-cycDp1 - complex
    cdk46p1p2-cycDp1 - complex
    PCNA-p21-cdk46p1p2-cycD - complex
    cdk46p1p2-cycD - complex
    PCNA-p21-cdk46p2-cycDp1 - complex
    cdk46p2-cycDp1 - complex
    PCNA-p21-cdk46p2-cycD - complex
    cdk46p2-cycD - complex
    PCNA-p21 - complex
    p21 - complex
    pRb-AP2-gE-c - complex
    pRb-AP2 - complex
    pRb-E2F13-DP12-gE2 - complex
    pRb-E2F13-DP12p1-gE2 - complex
    pRb-E2F13p1-DP12-gE2 - complex
    pRb-E2F13p1-DP12p1-gE2 - complex
    pRb-E2F4-DP12-gE2 - complex
    pRb-E2F4-DP12p1 - complex
    pRb-E2F4p1-DP12-gE2 - complex
    pRb-Jun-c-Fos-gERCC1 - complex
    pRb-Jun-c-Fos - complex
    pRb-Jun - complex
    pRbp1-AP2-gE-c - complex
    pRbp1-AP2 - complex
    cdk2p2-cycEp1 - complex
    cdk2p2-cycE - complex
    pRbp1-E2F13-DP12-gE2 - complex
    pRbp1-E2F13-DP12p1-gE2 - complex
    pRbp1-E2F13p1-DP12-gE2 - complex
    pRbp1-E2F13p1-DP12p1-gE2 - complex
    pRbp1-E2F4-DP12-gE2 - complex
    pRbp1-E2F4-DP12p1 - complex
    E2F4-DP12 - complex
    pRbp1-E2F4p1-DP12-gE2 - complex
    pRbp1-Jun-c-Fos-gERCC1 - complex
    pRbp1-Jun-c-Fos - complex
    pRbp1-Jun - complex
    pRbp1 - complex
    pRbp1p2-AP2-gE-c - complex
    pRbp1p2-AP2 - complex
    pRbp1p2-Jun-c-Fos-gERCC1 - complex
    pRbp1p2-Jun-c-Fos - complex
    pRbp1p2-Jun - complex
    Ecadherin - complex
    pRbp2-AP2-gE-c - complex
    pRbp2-AP2 - complex
    pRbp1p2 - complex
    ERCC1 - complex
    pRbp2-Jun-c-Fos-gERCC1 - complex
    pRbp2-Jun-c-Fos - complex
    c-Fos - complex
    pRbp2-Jun - complex
    Raf1-cdc25Ap1 - complex
    cdc25Ap1 - complex
    Raf1-cdc25A - complex
    cdc25A - complex
    Raf1-p130-E2F4-DP12-gE2 - complex
    Raf1-p130-E2F4-DP12 - complex
    p130-E2F4-DP12 - complex
    Raf1-p130-E2F4p1-DP12-gE2 - complex
    Raf1-p130-E2F4p1-DP12 - complex
    Raf1-p130-E2F5-DP12-gE2 - complex
    Raf1-p130-E2F5-DP12 - complex
    p130-E2F5-DP12 - complex
    Raf1-p130-E2F5p1-DP12-gE2 - complex
    Raf1-p130-E2F5p1-DP12 - complex
    Raf1-pRb-E2F13-DP12-gE2 - complex
    Raf1-pRb-E2F13-DP12p1-gE2 - complex
    Raf1-pRb-E2F13-DP12p1 - complex
    pRb-E2F13-DP12p1 - complex
    Raf1-pRb-E2F13-DP12 - complex
    pRb-E2F13-DP12 - complex
    Raf1-pRb-E2F13p1-DP12-gE2 - complex
    Raf1-pRb-E2F13p1-DP12p1-gE2 - complex
    Raf1-pRb-E2F13p1-DP12p1 - complex
    pRb-E2F13p1-DP12p1 - complex
    Raf1-pRb-E2F13p1-DP12 - complex
    pRb-E2F13p1-DP12 - complex
    Raf1-pRb-E2F4-DP12-gE2 - complex
    Raf1-pRb-E2F4-DP12 - complex
    pRb-E2F4-DP12 - complex
    Raf1-pRb-E2F4p1-DP12-gE2 - complex
    Raf1-pRb-E2F4p1-DP12 - complex
    Raf1-pRbp1-E2F13-DP12-gE2 - complex
    Raf1-pRbp1-E2F13-DP12p1-gE2 - complex
    Raf1-pRbp1-E2F13-DP12p1 - complex
    pRbp1-E2F13-DP12p1 - complex
    Raf1-pRbp1-E2F13-DP12 - complex
    pRbp1-E2F13-DP12 - complex
    Raf1-pRbp1-E2F13p1-DP12-gE2 - complex
    Raf1-pRbp1-E2F13p1-DP12p1-gE2 - complex
    Raf1-pRbp1-E2F13p1-DP12p1 - complex
    pRbp1-E2F13p1-DP12p1 - complex
    Raf1-pRbp1-E2F13p1-DP12 - complex
    pRbp1-E2F13p1-DP12 - complex
    Raf1-pRbp1-E2F4-DP12-gE2 - complex
    Raf1-pRbp1-E2F4-DP12 - complex
    pRbp1-E2F4-DP12 - complex
    Raf1-pRbp1-E2F4p1-DP12-gE2 - complex
    Raf1-pRbp1-E2F4p1-DP12 - complex
    RPA-cycA - complex
    Skp2-cdk2-cycA - complex
    Skp2-cdk2p1-cycA - complex
    Skp2-cdk2p1p2-cycA - complex
    Skp2-cdk2p2-cycA - complex
    Skp2p1-Skp1p1 - complex
    Skp2p1-Skp1 - complex
    Skp2p1 - complex
    Skp2-Skp1-cdk2-cycA - complex
    Skp2-Skp1-cdk2p1-cycA - complex
    Skp2-Skp1-cdk2p1p2-cycA - complex
    Skp2-Skp1-cdk2p2-cycA - complex
    Skp2-Skp1p1-cdk2-cycA - complex
    cdk2-cycA - complex
    Skp2-Skp1p1-cdk2p1-cycA - complex
    cdk2p1-cycA - complex
    Skp2-Skp1p1-cdk2p1p2-cycA - complex
    cdk2p1p2-cycA - complex
    Skp2-Skp1p1-cdk2p2-cycA - complex
    cdk2p2-cycA - complex
    Skp2-Skp1p1 - complex
    Skp1p1 - complex
    Skp2-Skp1 - complex
    SL1p1 - complex
    SP1-E2F13-gP - complex
    SP1-E2F13p1-gP - complex
    SP1-E2F13p1 - complex
    E2F13p1 - complex
    SP1-E2F13 - complex
    c-Myc - complex
    cycA - complex
    cycD - complex
    cycDp1 - complex
    cycE - complex
    cycEp1 - complex
    p19ARF - complex
    pol - complex
    SP1-gP - complex
    SP1-p107-gP - complex
    SP1-p107p1-gP - complex
    SP1-p107p1 - complex
    p107p1 - complex
    SP1-p107 - complex
    p107 - complex
    cdk1p3-cycA - complex
    Wee1p1 - complex
    cdk1p3-cycB - complex
    l0 - level
    l1 - level
    l2 - level
    l3 - level
    l4 - level
    l5 - level
    l6 - level
    l7 - level
    l8 - level
    l9 - level
    l10 - level
    l11 - level
    l12 - level
    l13 - level
    l14 - level
    l15 - level
    l16 - level
    l17 - level
    l18 - level
    l19 - level
    l20 - level
    l21 - level
    l22 - level
    l23 - level
    l24 - level
    l25 - level
    l26 - level
    l27 - level
    l28 - level
    l29 - level
    l30 - level
    l31 - level
    l32 - level
    l33 - level
    l34 - level
    l35 - level
    l36 - level
    l37 - level
    l38 - level
    l39 - level
    l40 - level
    l41 - level
    l42 - level
    l43 - level
    l44 - level
    l45 - level
    l46 - level
    l47 - level
    l48 - level
    l49 - level
    l50 - level
    l51 - level
    l52 - level
    l53 - level
    l54 - level
    l55 - level
    l56 - level
    l57 - level
    l58 - level
    l59 - level
    l60 - level
    l61 - level
    l62 - level
    l63 - level
    l64 - level
    l65 - level
    l66 - level
    l67 - level
    l68 - level
    l69 - level
    l70 - level
    l71 - level
    l72 - level
    l73 - level
    l74 - level
    l75 - level
    l76 - level
    l77 - level
    l78 - level
    l79 - level
    l80 - level
    l81 - level
    l82 - level
    l83 - level
    l84 - level
    l85 - level
    l86 - level
    l87 - level
    l88 - level
    l89 - level
    l90 - level
    l91 - level
    l92 - level
    l93 - level
    l94 - level
    l95 - level
    l96 - level
    l97 - level
    l98 - level
    l99 - level
    l100 - level
    l101 - level
    l102 - level
    l103 - level
    l104 - level
    l105 - level
    l106 - level
    l107 - level
    l108 - level
    l109 - level
    l110 - level
    l111 - level
    l112 - level
    l113 - level
    l114 - level
    l115 - level
    l116 - level
    l117 - level
    l118 - level
    l119 - level
    l120 - level
    l121 - level
    l122 - level
    l123 - level
    l124 - level
    l125 - level
    l126 - level
    l127 - level
    l128 - level
    l129 - level
    l130 - level
    l131 - level
    l132 - level
    l133 - level
    l134 - level
    l135 - level
    l136 - level
    l137 - level
    l138 - level
    l139 - level
    l140 - level
    l141 - level
    l142 - level
    l143 - level
    l144 - level
    l145 - level
    l146 - level
    l147 - level
    l148 - level
    l149 - level
    l150 - level
    l151 - level
    l152 - level
    l153 - level
    l154 - level
    l155 - level
    l156 - level
    l157 - level
    l158 - level
    l159 - level
    l160 - level
    l161 - level
    l162 - level
    l163 - level
    l164 - level
    l165 - level
    l166 - level
    l167 - level
    l168 - level
    l169 - level
    l170 - level
    l171 - level
    l172 - level
    l173 - level
    l174 - level
    l175 - level
    l176 - level
    l177 - level
    l178 - level
    l179 - level
    l180 - level
    l181 - level
    l182 - level
    l183 - level
    l184 - level
    l185 - level
    l186 - level
    l187 - level
    l188 - level
    l189 - level
    l190 - level
    l191 - level
    l192 - level
    l193 - level
    l194 - level
    l195 - level
    l196 - level
    l197 - level
    l198 - level
    l199 - level
    l200 - level
    l201 - level
    l202 - level
    l203 - level
    l204 - level
    l205 - level
    l206 - level
    l207 - level
    l208 - level
    l209 - level
    l210 - level
    l211 - level
    l212 - level
    l213 - level
    l214 - level
    l215 - level
    l216 - level
    l217 - level
    l218 - level
    l219 - level
    l220 - level
    l221 - level
    l222 - level
    l223 - level
    l224 - level
    l225 - level
    l226 - level
    l227 - level
    l228 - level
    l229 - level
    l230 - level
    l231 - level
    l232 - level
    l233 - level
    l234 - level
    l235 - level
    l236 - level
    l237 - level
    l238 - level
    l239 - level
    l240 - level
    l241 - level
    l242 - level
    l243 - level
    l244 - level
    l245 - level
    l246 - level
    l247 - level
    l248 - level
    l249 - level
    l250 - level
    l251 - level
    l252 - level
    l253 - level
    l254 - level
    l255 - level
    l256 - level
    l257 - level
    l258 - level
    l259 - level
    l260 - level
    l261 - level
    l262 - level
    l263 - level
    l264 - level
    l265 - level
    l266 - level
    l267 - level
    l268 - level
    l269 - level
    l270 - level
    l271 - level
    l272 - level
    l273 - level
    l274 - level
    l275 - level
    l276 - level
    l277 - level
    l278 - level
    l279 - level
    l280 - level
    l281 - level
    l282 - level
    l283 - level
    l284 - level
    l285 - level
    l286 - level
    l287 - level
    l288 - level
    l289 - level
    l290 - level
    l291 - level
    l292 - level
    l293 - level
    l294 - level
    l295 - level
    l296 - level
    l297 - level
    l298 - level
    l299 - level
    l300 - level
    l301 - level
    l302 - level
    l303 - level
    l304 - level
    l305 - level
    l306 - level
    l307 - level
    l308 - level
    l309 - level
    l310 - level
    l311 - level
    l312 - level
    l313 - level
    l314 - level
    l315 - level
    l316 - level
    l317 - level
    l318 - level
    l319 - level
    l320 - level
    l321 - level
    l322 - level
    l323 - level
    l324 - level
    l325 - level
    l326 - level
    l327 - level
    l328 - level
    l329 - level
    l330 - level
    l331 - level
    l332 - level
    l333 - level
    l334 - level
    l335 - level
    l336 - level
    l337 - level
    l338 - level)


(:init
    (possible Wee1)
    (possible SP1)
    (possible SL1)
    (possible Skp2)
    (possible Skp1)
    (possible RPA)
    (possible Raf1)
    (possible pRbp2)
    (possible pRbp1-E2F4p1-DP12)
    (possible pRb-E2F4p1-DP12)
    (possible pRb)
    (possible Plk1)
    (possible PCNA)
    (possible pCAF)
    (possible p68)
    (possible p57p1)
    (possible p57)
    (possible p53p1)
    (possible p53)
    (possible p300)
    (possible p27)
    (possible p16)
    (possible p130-E2F5p1-DP12)
    (possible p130-E2F4p1-DP12)
    (possible p130)
    (possible Myt1)
    (possible Max)
    (possible m1433)
    (possible Jun)
    (possible HDAC1-pRbp1-E2F4-DP12)
    (possible HDAC1-pRbp1-E2F13p1-DP12)
    (possible HDAC1-pRbp1-E2F13-DP12)
    (possible HDAC1-p130-E2F5p1-DP12)
    (possible HDAC1-p130-E2F4p1-DP12)
    (possible HDAC1-p107-E2F4p1-DP12)
    (possible HDAC1)
    (possible HBP1)
    (possible gp19ARF)
    (possible gP)
    (possible gERCC1)
    (possible gE-c)
    (possible gE2)
    (possible gcdc25A)
    (possible E2F6-DP12p1)
    (possible E2F6)
    (possible E2F5-DP12p1)
    (possible E2F5)
    (possible E2F4-DP12p1)
    (possible E2F4)
    (possible E2F3)
    (possible E2F2)
    (possible E2F13p1-DP12p1)
    (possible E2F13p1-DP12)
    (possible E2F13-DP12p1)
    (possible E2F13-DP12)
    (possible E2F13)
    (possible E2F1)
    (possible DP12)
    (possible DMP1)
    (possible cycH)
    (possible cycB)
    (possible C-TAK1)
    (possible cks1)
    (possible Chk1)
    (possible CEBP)
    (possible cdk7)
    (possible cdk46p3-cycDp1)
    (possible cdk46p3-cycD)
    (possible cdk46p1)
    (possible cdk2p2-cycB)
    (possible cdk2p1)
    (possible cdk2-cycB)
    (possible cdk2)
    (possible cdk1p1p2)
    (possible cdc25C)
    (possible c-Abl)
    (possible APC)
    (possible AP2)
    (association-reaction AP2 gE-c AP2-gE-c)
    (synthesis-reaction AP2-gE-c Ecadherin) 
    (catalyzed-association-reaction APC Plk1 APCp1)
    (association-reaction c-Abl pRb c-Abl-pRb)
    (association-reaction c-Abl pRbp1 c-Abl-pRbp1)
    (association-reaction c-Abl pRbp1p2 c-Abl-pRbp1p2)
    (association-reaction c-Abl pRbp2 c-Abl-pRbp2)
    (catalyzed-association-reaction cdc25A Raf1 cdc25Ap1)
    (catalyzed-association-reaction cdc25C cdk1p3-cycA cdc25Cp1)
    (catalyzed-association-reaction cdc25C cdk1p3-cycB cdc25Cp1)
    (catalyzed-association-reaction cdc25C Chk1 cdc25Cp2)
    (catalyzed-association-reaction cdc25C C-TAK1 cdc25Cp2)
    (catalyzed-association-reaction cdc25Cp1 Chk1 cdc25Cp1p2)
    (catalyzed-association-reaction cdc25Cp1 C-TAK1 cdc25Cp1p2)
    (catalyzed-association-reaction cdc25Cp2 cdk1p3-cycA cdc25Cp1p2)
    (catalyzed-association-reaction cdc25Cp2 cdk1p3-cycB cdc25Cp1p2)
    (catalyzed-association-reaction cdc25Cp2 Plk1 cdc25Cp1p2)
    (catalyzed-association-reaction cdc25C Plk1 cdc25Cp1)
    (catalyzed-association-reaction cdk1 cdk7-cycH cdk1p3)
    (association-reaction cdk1 cks1 cdk1-cks1)
    (association-reaction cdk1 Gadd45 cdk1-Gadd45)
    (catalyzed-association-reaction cdk1p1 cdc25Cp1 cdk1)
    (catalyzed-association-reaction cdk1p1 cdc25Cp1p2 cdk1)
    (catalyzed-association-reaction cdk1p1 cdk7-cycH cdk1p1p3)
    (association-reaction cdk1p1 cks1 cdk1p1-cks1)
    (association-reaction cdk1p1 Gadd45 cdk1p1-Gadd45)
    (catalyzed-association-reaction cdk1p1p2 cdc25Cp1 cdk1p1)
    (catalyzed-association-reaction cdk1p1p2 cdc25Cp1 cdk1p2)
    (catalyzed-association-reaction cdk1p1p2 cdc25Cp1p2 cdk1p1)
    (catalyzed-association-reaction cdk1p1p2 cdc25Cp1p2 cdk1p2)
    (catalyzed-association-reaction cdk1p1p2 cdk7-cycH cdk1p1p2p3)
    (association-reaction cdk1p1p2 cks1 cdk1p1p2-cks1)
    (association-reaction cdk1p1p2 Gadd45 cdk1p1p2-Gadd45)
    (catalyzed-association-reaction cdk1p1p2p3 cdc25Cp1 cdk1p1p3)
    (catalyzed-association-reaction cdk1p1p2p3 cdc25Cp1 cdk1p2p3)
    (catalyzed-association-reaction cdk1p1p2p3 cdc25Cp1p2 cdk1p1p3)
    (catalyzed-association-reaction cdk1p1p2p3 cdc25Cp1p2 cdk1p2p3)
    (association-reaction cdk1p1p2p3 cks1 cdk1p1p2p3-cks1)
    (catalyzed-association-reaction cdk1p1p2p3-cycA cdc25Cp1 cdk1p1p3-cycA)
    (catalyzed-association-reaction cdk1p1p2p3-cycA cdc25Cp1 cdk1p2p3-cycA)
    (catalyzed-association-reaction cdk1p1p2p3-cycA cdc25Cp1p2 cdk1p1p3-cycA)
    (catalyzed-association-reaction cdk1p1p2p3-cycA cdc25Cp1p2 cdk1p2p3-cycA)
    (association-reaction cdk1p1p2p3 cycA cdk1p1p2p3-cycA)
    (catalyzed-association-reaction cdk1p1p2p3-cycB cdc25Cp1 cdk1p1p3-cycB)
    (catalyzed-association-reaction cdk1p1p2p3-cycB cdc25Cp1 cdk1p2p3-cycB)
    (catalyzed-association-reaction cdk1p1p2p3-cycB cdc25Cp1p2 cdk1p1p3-cycB)
    (catalyzed-association-reaction cdk1p1p2p3-cycB cdc25Cp1p2 cdk1p2p3-cycB)
    (association-reaction cdk1p1p2p3 cycB cdk1p1p2p3-cycB)
    (association-reaction cdk1p1p2p3 Gadd45 cdk1p1p2p3-Gadd45)
    (catalyzed-association-reaction cdk1p1p3 cdc25Cp1 cdk1p3)
    (catalyzed-association-reaction cdk1p1p3 cdc25Cp1p2 cdk1p3)
    (association-reaction cdk1p1p3 cks1 cdk1p1p3-cks1)
    (catalyzed-association-reaction cdk1p1p3-cycA cdc25Cp1 cdk1p3-cycA)
    (catalyzed-association-reaction cdk1p1p3-cycA cdc25Cp1p2 cdk1p3-cycA)
    (association-reaction cdk1p1p3 cycA cdk1p1p3-cycA)
    (catalyzed-association-reaction cdk1p1p3-cycA Wee1 cdk1p1p2p3-cycA)
    (catalyzed-association-reaction cdk1p1p3-cycB cdc25Cp1 cdk1p3-cycB)
    (catalyzed-association-reaction cdk1p1p3-cycB cdc25Cp1p2 cdk1p3-cycB)
    (association-reaction cdk1p1p3 cycB cdk1p1p3-cycB)
    (catalyzed-association-reaction cdk1p1p3-cycB Wee1 cdk1p1p2p3-cycB)
    (association-reaction cdk1p1p3 Gadd45 cdk1p1p3-Gadd45)
    (catalyzed-association-reaction cdk1p2 cdc25Cp1 cdk1)
    (catalyzed-association-reaction cdk1p2 cdc25Cp1p2 cdk1)
    (catalyzed-association-reaction cdk1p2 cdk7-cycH cdk1p2p3)
    (association-reaction cdk1p2 cks1 cdk1p2-cks1)
    (association-reaction cdk1p2 Gadd45 cdk1p2-Gadd45)
    (catalyzed-association-reaction cdk1p2p3 cdc25Cp1 cdk1p3)
    (catalyzed-association-reaction cdk1p2p3 cdc25Cp1p2 cdk1p3)
    (association-reaction cdk1p2p3 cks1 cdk1p2p3-cks1)
    (catalyzed-association-reaction cdk1p2p3-cycA cdc25Cp1 cdk1p3-cycA)
    (catalyzed-association-reaction cdk1p2p3-cycA cdc25Cp1p2 cdk1p3-cycA)
    (association-reaction cdk1p2p3 cycA cdk1p2p3-cycA)
    (catalyzed-association-reaction cdk1p2p3-cycA Myt1 cdk1p1p2p3-cycA)
    (catalyzed-association-reaction cdk1p2p3-cycB cdc25Cp1 cdk1p3-cycB)
    (catalyzed-association-reaction cdk1p2p3-cycB cdc25Cp1p2 cdk1p3-cycB)
    (association-reaction cdk1p2p3 cycB cdk1p2p3-cycB)
    (catalyzed-association-reaction cdk1p2p3-cycB Myt1 cdk1p1p2p3-cycB)
    (association-reaction cdk1p2p3 Gadd45 cdk1p2p3-Gadd45)
    (association-reaction cdk1p3 cks1 cdk1p3-cks1)
    (association-reaction cdk1p3 cycA cdk1p3-cycA)
    (catalyzed-association-reaction cdk1p3-cycA Myt1 cdk1p1p3-cycA)
    (catalyzed-association-reaction cdk1p3-cycA Wee1 cdk1p2p3-cycA)
    (association-reaction cdk1p3 cycB cdk1p3-cycB)
    (catalyzed-association-reaction cdk1p3-cycB Myt1 cdk1p1p3-cycB)
    (catalyzed-association-reaction cdk1p3-cycB Wee1 cdk1p2p3-cycB)
    (association-reaction cdk1p3 Gadd45 cdk1p3-Gadd45)
    (catalyzed-association-reaction cdk2 cdk7-cycH cdk2p2)
    (association-reaction cdk2 cks1 cdk2-cks1)
    (association-reaction cdk2 cycA cdk2-cycA)
    (catalyzed-association-reaction cdk2-cycA cdk7-cycH cdk2p2-cycA)
    (association-reaction cdk2-cycA E2F13 cdk2-cycA-E2F13)
    (association-reaction cdk2-cycA E2F13p1 cdk2-cycA-E2F13p1)
    (catalyzed-association-reaction cdk2-cycA Wee1 cdk2p1-cycA)
    (catalyzed-association-reaction cdk2-cycB Wee1 cdk2p1-cycB)
    (association-reaction cdk2 cycE cdk2-cycE)
    (catalyzed-association-reaction cdk2-cycE cdk7-cycH cdk2p2-cycE)
    (association-reaction cdk2 cycEp1 cdk2-cycEp1)
    (catalyzed-association-reaction cdk2-cycEp1 cdk7-cycH cdk2p2-cycEp1)
    (catalyzed-association-reaction cdk2p1 cdk7-cycH cdk2p1p2)
    (association-reaction cdk2p1 cks1 cdk2p1-cks1)
    (catalyzed-association-reaction cdk2p1-cycA cdc25Ap1 cdk2-cycA)
    (association-reaction cdk2p1 cycA cdk2p1-cycA)
    (catalyzed-association-reaction cdk2p1-cycA cdk7-cycH cdk2p1p2-cycA)
    (association-reaction cdk2p1-cycA E2F13 cdk2p1-cycA-E2F13)
    (association-reaction cdk2p1-cycA E2F13p1 cdk2p1-cycA-E2F13p1)
    (catalyzed-association-reaction cdk2p1-cycE cdc25Ap1 cdk2-cycE)
    (association-reaction cdk2p1 cycE cdk2p1-cycE)
    (catalyzed-association-reaction cdk2p1-cycE cdk7-cycH cdk2p1p2-cycE)
    (catalyzed-association-reaction cdk2p1-cycEp1 cdc25Ap1 cdk2-cycEp1)
    (association-reaction cdk2p1 cycEp1 cdk2p1-cycEp1)
    (catalyzed-association-reaction cdk2p1-cycEp1 cdk7-cycH cdk2p1p2-cycEp1)
    (association-reaction cdk2p1p2 cks1 cdk2p1p2-cks1)
    (catalyzed-association-reaction cdk2p1p2-cycA cdc25Ap1 cdk2p2-cycA)
    (association-reaction cdk2p1p2 cycA cdk2p1p2-cycA)
    (association-reaction cdk2p1p2-cycA E2F13 cdk2p1p2-cycA-E2F13)
    (association-reaction cdk2p1p2-cycA E2F13p1 cdk2p1p2-cycA-E2F13p1)
    (catalyzed-association-reaction cdk2p1p2-cycE cdc25Ap1 cdk2p2-cycE)
    (association-reaction cdk2p1p2 cycE cdk2p1p2-cycE)
    (catalyzed-association-reaction cdk2p1p2-cycEp1 cdc25Ap1 cdk2p2-cycEp1)
    (association-reaction cdk2p1p2 cycEp1 cdk2p1p2-cycEp1)
    (association-reaction cdk2p2 cks1 cdk2p2-cks1)
    (association-reaction cdk2p2 cycA cdk2p2-cycA)
    (association-reaction cdk2p2-cycA E2F13 cdk2p2-cycA-E2F13)
    (association-reaction cdk2p2-cycA E2F13p1 cdk2p2-cycA-E2F13p1)
    (catalyzed-association-reaction cdk2p2-cycA Wee1 cdk2p1p2-cycA)
    (catalyzed-association-reaction cdk2p2-cycB Wee1 cdk2p1p2-cycB)
    (association-reaction cdk2p2 cycE cdk2p2-cycE)
    (association-reaction cdk2p2 cycEp1 cdk2p2-cycEp1)
    (catalyzed-association-reaction cdk46 cdk7-cycH cdk46p2)
    (association-reaction cdk46 cycD cdk46-cycD)
    (catalyzed-association-reaction cdk46-cycD cdk7-cycH cdk46p2-cycD)
    (association-reaction cdk46 cycDp1 cdk46-cycDp1)
    (catalyzed-association-reaction cdk46-cycDp1 cdk7-cycH cdk46p2-cycDp1)
    (catalyzed-association-reaction cdk46p1 cdc25Ap1 cdk46)
    (catalyzed-association-reaction cdk46p1 cdk7-cycH cdk46p1p2)
    (association-reaction cdk46p1 cycD cdk46p1-cycD)
    (catalyzed-association-reaction cdk46p1-cycD cdk7-cycH cdk46p1p2-cycD)
    (association-reaction cdk46p1 cycDp1 cdk46p1-cycDp1)
    (catalyzed-association-reaction cdk46p1-cycDp1 cdk7-cycH cdk46p1p2-cycDp1)
    (catalyzed-association-reaction cdk46p1p2 cdc25Ap1 cdk46p2)
    (association-reaction cdk46p1p2 cycD cdk46p1p2-cycD)
    (association-reaction cdk46p1p2 cycDp1 cdk46p1p2-cycDp1)
    (association-reaction cdk46p2 cycD cdk46p2-cycD)
    (association-reaction cdk46p2 cycDp1 cdk46p2-cycDp1)
    (catalyzed-association-reaction cdk7 cdk7-cycH cdk7p1)
    (association-reaction cdk7 cycH cdk7-cycH)
    (catalyzed-association-reaction cdk7-cycH cdk7-cycH cdk7p1-cycH)
    (association-reaction cdk7p1 cycH cdk7p1-cycH)
    (association-reaction CEBP gP CEBP-gP)
    (synthesis-reaction CEBP-gP P) 
    (association-reaction CEBP pRb CEBP-pRb)
    (association-reaction CEBP-pRb gP CEBP-pRb-gP)
    (synthesis-reaction CEBP-pRb-gP P) 
    (association-reaction CEBP pRbp1 CEBP-pRbp1)
    (association-reaction CEBP-pRbp1 gP CEBP-pRbp1-gP)
    (synthesis-reaction CEBP-pRbp1-gP P) 
    (association-reaction CEBP pRbp1p2 CEBP-pRbp1p2)
    (association-reaction CEBP-pRbp1p2 gP CEBP-pRbp1p2-gP)
    (synthesis-reaction CEBP-pRbp1p2-gP P) 
    (association-reaction CEBP pRbp2 CEBP-pRbp2)
    (association-reaction CEBP-pRbp2 gP CEBP-pRbp2-gP)
    (synthesis-reaction CEBP-pRbp2-gP P) 
    (association-reaction c-Myc AP2 c-Myc-AP2)
    (association-reaction c-Myc Max c-Myc-Max)
    (synthesis-reaction c-Myc-Max-gcdc25A cdc25A) 
    (association-reaction c-Myc-Max gcdc25A c-Myc-Max-gcdc25A)
    (catalyzed-association-reaction cycA Skp2p1-Skp1 Skp2p1-Skp1)
    (catalyzed-association-reaction cycA Skp2p1-Skp1p1 Skp2p1-Skp1p1)
    (catalyzed-association-reaction cycA Skp2-Skp1 Skp2-Skp1)
    (catalyzed-association-reaction cycA Skp2-Skp1p1 Skp2-Skp1p1)
    (catalyzed-association-reaction cycB APCp1 APCp1)
    (catalyzed-association-reaction cycE cdk2p2-cycE cycEp1)
    (catalyzed-association-reaction cycE cdk2p2-cycEp1 cycEp1)
    (catalyzed-association-reaction DMP1 cdk46p3-cycD DMP1p1)
    (catalyzed-association-reaction DMP1 cdk46p3-cycDp1 DMP1p1)
    (association-reaction DMP1 cycD DMP1-cycD)
    (association-reaction DMP1 cycDp1 DMP1-cycDp1)
    (association-reaction DMP1 gp19ARF DMP1-gp19ARF)
    (association-reaction DMP1p1 cycD DMP1p1-cycD)
    (association-reaction DMP1p1 cycDp1 DMP1p1-cycDp1)
    (association-reaction DMP1p1 gp19ARF DMP1p1-gp19ARF)
    (synthesis-reaction DMP1p1-gp19ARF p19ARF) 
    (catalyzed-association-reaction DP12 cdk2p2-cycA DP12p1)
    (catalyzed-association-reaction E2F13 cdk2p2-cycA E2F13p1)
    (synthesis-reaction E2F13-DP12-gE2 c-Myc) 
    (synthesis-reaction E2F13-DP12-gE2 cycA) 
    (synthesis-reaction E2F13-DP12-gE2 cycD) 
    (synthesis-reaction E2F13-DP12-gE2 cycDp1) 
    (synthesis-reaction E2F13-DP12-gE2 cycE) 
    (synthesis-reaction E2F13-DP12-gE2 cycEp1) 
    (association-reaction E2F13-DP12 gE2 E2F13-DP12-gE2)
    (synthesis-reaction E2F13-DP12-gE2 p107) 
    (synthesis-reaction E2F13-DP12-gE2 p107p1) 
    (synthesis-reaction E2F13-DP12-gE2 p19ARF) 
    (synthesis-reaction E2F13-DP12-gE2 pol) 
    (synthesis-reaction E2F13p1-DP12-gE2 c-Myc) 
    (synthesis-reaction E2F13p1-DP12-gE2 cycA) 
    (synthesis-reaction E2F13p1-DP12-gE2 cycD) 
    (synthesis-reaction E2F13p1-DP12-gE2 cycDp1) 
    (synthesis-reaction E2F13p1-DP12-gE2 cycE) 
    (synthesis-reaction E2F13p1-DP12-gE2 cycEp1) 
    (association-reaction E2F13p1-DP12 gE2 E2F13p1-DP12-gE2)
    (synthesis-reaction E2F13p1-DP12-gE2 p107) 
    (synthesis-reaction E2F13p1-DP12-gE2 p107p1) 
    (synthesis-reaction E2F13p1-DP12-gE2 p19ARF) 
    (synthesis-reaction E2F13p1-DP12-gE2 pol) 
    (association-reaction E2F1 DP12 E2F1-DP12)
    (association-reaction E2F2 DP12 E2F2-DP12)
    (association-reaction E2F3 DP12 E2F3-DP12)
    (association-reaction E2F4 DP12 E2F4-DP12)
    (synthesis-reaction E2F4-DP12-gE2 c-Myc) 
    (synthesis-reaction E2F4-DP12-gE2 cycA) 
    (synthesis-reaction E2F4-DP12-gE2 cycD) 
    (synthesis-reaction E2F4-DP12-gE2 cycDp1) 
    (synthesis-reaction E2F4-DP12-gE2 cycE) 
    (synthesis-reaction E2F4-DP12-gE2 cycEp1) 
    (association-reaction E2F4-DP12 gE2 E2F4-DP12-gE2)
    (synthesis-reaction E2F4-DP12-gE2 p107) 
    (synthesis-reaction E2F4-DP12-gE2 p107p1) 
    (synthesis-reaction E2F4-DP12-gE2 p19ARF) 
    (synthesis-reaction E2F4-DP12-gE2 pol) 
    (association-reaction E2F5 DP12 E2F5-DP12)
    (synthesis-reaction E2F5-DP12-gE2 c-Myc) 
    (synthesis-reaction E2F5-DP12-gE2 cycA) 
    (synthesis-reaction E2F5-DP12-gE2 cycD) 
    (synthesis-reaction E2F5-DP12-gE2 cycDp1) 
    (synthesis-reaction E2F5-DP12-gE2 cycE) 
    (synthesis-reaction E2F5-DP12-gE2 cycEp1) 
    (association-reaction E2F5-DP12 gE2 E2F5-DP12-gE2)
    (synthesis-reaction E2F5-DP12-gE2 p107) 
    (synthesis-reaction E2F5-DP12-gE2 p107p1) 
    (synthesis-reaction E2F5-DP12-gE2 p19ARF) 
    (synthesis-reaction E2F5-DP12-gE2 pol) 
    (association-reaction E2F6 DP12 E2F6-DP12)
    (association-reaction E2F6-DP12 gE2 E2F6-DP12-gE2)
    (association-reaction E2F6-DP12p1 gE2 E2F6-DP12p1-gE2)
    (association-reaction HBP1 p130 HBP1-p130)
    (association-reaction HDAC1-p107-E2F4-DP12 gE2 HDAC1-p107-E2F4-DP12-gE2)
    (association-reaction HDAC1 p107-E2F4-DP12 HDAC1-p107-E2F4-DP12)
    (association-reaction HDAC1 p107-E2F4-DP12p1 HDAC1-p107-E2F4-DP12p1)
    (association-reaction HDAC1-p107-E2F4p1-DP12 gE2 HDAC1-p107-E2F4p1-DP12-gE2)
    (association-reaction HDAC1-p130-E2F4-DP12 gE2 HDAC1-p130-E2F4-DP12-gE2)
    (association-reaction HDAC1 p130-E2F4-DP12 HDAC1-p130-E2F4-DP12)
    (association-reaction HDAC1 p130-E2F4-DP12p1 HDAC1-p130-E2F4-DP12p1)
    (association-reaction HDAC1-p130-E2F4p1-DP12 gE2 HDAC1-p130-E2F4p1-DP12-gE2)
    (association-reaction HDAC1-p130-E2F5-DP12 gE2 HDAC1-p130-E2F5-DP12-gE2)
    (association-reaction HDAC1 p130-E2F5-DP12 HDAC1-p130-E2F5-DP12)
    (association-reaction HDAC1 p130-E2F5-DP12p1 HDAC1-p130-E2F5-DP12p1)
    (association-reaction HDAC1-p130-E2F5p1-DP12 gE2 HDAC1-p130-E2F5p1-DP12-gE2)
    (association-reaction HDAC1-pRb-E2F13-DP12 gE2 HDAC1-pRb-E2F13-DP12-gE2)
    (association-reaction HDAC1 pRb-E2F13-DP12 HDAC1-pRb-E2F13-DP12)
    (association-reaction HDAC1 pRb-E2F13-DP12p1 HDAC1-pRb-E2F13-DP12p1)
    (association-reaction HDAC1-pRb-E2F13p1-DP12 gE2 HDAC1-pRb-E2F13p1-DP12-gE2)
    (association-reaction HDAC1 pRb-E2F13p1-DP12 HDAC1-pRb-E2F13p1-DP12)
    (association-reaction HDAC1 pRb-E2F13p1-DP12p1 HDAC1-pRb-E2F13p1-DP12p1)
    (association-reaction HDAC1-pRb-E2F4-DP12 gE2 HDAC1-pRb-E2F4-DP12-gE2)
    (association-reaction HDAC1 pRb-E2F4-DP12 HDAC1-pRb-E2F4-DP12)
    (association-reaction HDAC1 pRb-E2F4p1-DP12 HDAC1-pRb-E2F4p1-DP12)
    (association-reaction HDAC1-pRbp1-E2F13-DP12 gE2 HDAC1-pRbp1-E2F13-DP12-gE2)
    (association-reaction HDAC1-pRbp1-E2F13p1-DP12 gE2 HDAC1-pRbp1-E2F13p1-DP12-gE2)
    (association-reaction HDAC1-pRbp1-E2F4-DP12 gE2 HDAC1-pRbp1-E2F4-DP12-gE2)
    (synthesis-reaction Jun-c-Fos-gERCC1 ERCC1) 
    (association-reaction Jun-c-Fos gERCC1 Jun-c-Fos-gERCC1)
    (association-reaction Jun c-Fos Jun-c-Fos)
    (association-reaction m1433 cdc25Cp1p2 m1433-cdc25Cp1p2)
    (association-reaction m1433 cdc25Cp2 m1433-cdc25Cp2)
    (association-reaction Mdm2 E2F13-DP12 Mdm2-E2F13-DP12)
    (association-reaction Mdm2 E2F13-DP12p1 Mdm2-E2F13-DP12p1)
    (association-reaction Mdm2 E2F13p1-DP12 Mdm2-E2F13p1-DP12)
    (association-reaction Mdm2 E2F13p1-DP12p1 Mdm2-E2F13p1-DP12p1)
    (association-reaction Mdm2 pRb Mdm2-pRb)
    (association-reaction Mdm2 pRbp1 Mdm2-pRbp1)
    (association-reaction Mdm2 pRbp1p2 Mdm2-pRbp1p2)
    (association-reaction Mdm2 pRbp2 Mdm2-pRbp2)
    (association-reaction p107-E2F4-DP12 gE2 p107-E2F4-DP12-gE2)
    (association-reaction p107 E2F4-DP12 p107-E2F4-DP12)
    (association-reaction p107-E2F4-DP12p1 gE2 p107-E2F4-DP12p1-gE2)
    (association-reaction p107 E2F4-DP12p1 p107-E2F4-DP12p1)
    (association-reaction p130-E2F4-DP12 gE2 p130-E2F4-DP12-gE2)
    (association-reaction p130 E2F4-DP12 p130-E2F4-DP12)
    (association-reaction p130-E2F4-DP12p1 gE2 p130-E2F4-DP12p1-gE2)
    (association-reaction p130 E2F4-DP12p1 p130-E2F4-DP12p1)
    (association-reaction p130-E2F5-DP12 gE2 p130-E2F5-DP12-gE2)
    (association-reaction p130 E2F5-DP12 p130-E2F5-DP12)
    (association-reaction p130-E2F5-DP12p1 gE2 p130-E2F5-DP12p1-gE2)
    (association-reaction p130 E2F5-DP12p1 p130-E2F5-DP12p1)
    (association-reaction p16 cdk46 p16-cdk46)
    (association-reaction p16 cdk46p1 p16-cdk46p1)
    (association-reaction p16 cdk46p1p2 p16-cdk46p1p2)
    (association-reaction p16 cdk46p2 p16-cdk46p2)
    (association-reaction p16 cdk7 p16-cdk7)
    (association-reaction p16 cdk7p1 p16-cdk7p1)
    (association-reaction p21 cdk2-cycA p21-cdk2-cycA)
    (association-reaction p21 cdk2-cycEp1 p21-cdk2-cycEp1)
    (association-reaction p21 cdk2-cycE p21-cdk2-cycE)
    (association-reaction p21 cdk2p1-cycA p21-cdk2p1-cycA)
    (association-reaction p21 cdk2p1-cycEp1 p21-cdk2p1-cycEp1)
    (association-reaction p21 cdk2p1-cycE p21-cdk2p1-cycE)
    (association-reaction p21 cdk2p1p2-cycA p21-cdk2p1p2-cycA)
    (association-reaction p21 cdk2p1p2-cycEp1 p21-cdk2p1p2-cycEp1)
    (association-reaction p21 cdk2p1p2-cycE p21-cdk2p1p2-cycE)
    (association-reaction p21 cdk2p2-cycA p21-cdk2p2-cycA)
    (association-reaction p21 cdk2p2-cycEp1 p21-cdk2p2-cycEp1)
    (association-reaction p21 cdk2p2-cycE p21-cdk2p2-cycE)
    (association-reaction p21 cdk46-cycDp1 p21-cdk46-cycDp1)
    (association-reaction p21 cdk46-cycD p21-cdk46-cycD)
    (association-reaction p21 cdk46p1-cycDp1 p21-cdk46p1-cycDp1)
    (association-reaction p21 cdk46p1-cycD p21-cdk46p1-cycD)
    (association-reaction p21 cdk46p1p2-cycDp1 p21-cdk46p1p2-cycDp1)
    (association-reaction p21 cdk46p1p2-cycD p21-cdk46p1p2-cycD)
    (association-reaction p21 cdk46p2-cycDp1 p21-cdk46p2-cycDp1)
    (association-reaction p21 cdk46p2-cycD p21-cdk46p2-cycD)
    (association-reaction p21 Gadd45 p21-Gadd45)
    (association-reaction p27 cdk2-cycA p27-cdk2-cycA)
    (association-reaction p27 cdk2-cycEp1 p27-cdk2-cycEp1)
    (association-reaction p27 cdk2-cycE p27-cdk2-cycE)
    (association-reaction p27 cdk2p1-cycA p27-cdk2p1-cycA)
    (association-reaction p27 cdk2p1-cycEp1 p27-cdk2p1-cycEp1)
    (association-reaction p27 cdk2p1-cycE p27-cdk2p1-cycE)
    (association-reaction p27 cdk2p1p2-cycA p27-cdk2p1p2-cycA)
    (association-reaction p27 cdk2p1p2-cycEp1 p27-cdk2p1p2-cycEp1)
    (association-reaction p27 cdk2p1p2-cycE p27-cdk2p1p2-cycE)
    (association-reaction p27 cdk2p2-cycA p27-cdk2p2-cycA)
    (association-reaction p27 cdk2p2-cycEp1 p27-cdk2p2-cycEp1)
    (catalyzed-association-reaction p27 cdk2p2-cycEp1 p27p1)
    (association-reaction p27 cdk2p2-cycE p27-cdk2p2-cycE)
    (catalyzed-association-reaction p27 cdk2p2-cycE p27p1)
    (association-reaction p27 cdk46-cycDp1 p27-cdk46-cycDp1)
    (association-reaction p27 cdk46-cycD p27-cdk46-cycD)
    (association-reaction p27 cdk46p1-cycDp1 p27-cdk46p1-cycDp1)
    (association-reaction p27 cdk46p1-cycD p27-cdk46p1-cycD)
    (association-reaction p27 cdk46p1p2-cycDp1 p27-cdk46p1p2-cycDp1)
    (association-reaction p27 cdk46p1p2-cycD p27-cdk46p1p2-cycD)
    (association-reaction p27 cdk46p2-cycDp1 p27-cdk46p2-cycDp1)
    (association-reaction p27 cdk46p2-cycD p27-cdk46p2-cycD)
    (association-reaction p27p1 cdk2-cycA p27p1-cdk2-cycA)
    (association-reaction p27p1 cdk2-cycEp1 p27p1-cdk2-cycEp1)
    (association-reaction p27p1 cdk2-cycE p27p1-cdk2-cycE)
    (association-reaction p27p1 cdk2p1-cycA p27p1-cdk2p1-cycA)
    (association-reaction p27p1 cdk2p1-cycEp1 p27p1-cdk2p1-cycEp1)
    (association-reaction p27p1 cdk2p1-cycE p27p1-cdk2p1-cycE)
    (association-reaction p27p1 cdk2p1p2-cycA p27p1-cdk2p1p2-cycA)
    (association-reaction p27p1 cdk2p1p2-cycEp1 p27p1-cdk2p1p2-cycEp1)
    (association-reaction p27p1 cdk2p1p2-cycE p27p1-cdk2p1p2-cycE)
    (association-reaction p27p1 cdk2p2-cycA p27p1-cdk2p2-cycA)
    (association-reaction p27p1 cdk2p2-cycEp1 p27p1-cdk2p2-cycEp1)
    (association-reaction p27p1 cdk2p2-cycE p27p1-cdk2p2-cycE)
    (association-reaction p27p1 cdk46-cycDp1 p27p1-cdk46-cycDp1)
    (association-reaction p27p1 cdk46-cycD p27p1-cdk46-cycD)
    (association-reaction p27p1 cdk46p1-cycDp1 p27p1-cdk46p1-cycDp1)
    (association-reaction p27p1 cdk46p1-cycD p27p1-cdk46p1-cycD)
    (association-reaction p27p1 cdk46p1p2-cycDp1 p27p1-cdk46p1p2-cycDp1)
    (association-reaction p27p1 cdk46p1p2-cycD p27p1-cdk46p1p2-cycD)
    (association-reaction p27p1 cdk46p2-cycDp1 p27p1-cdk46p2-cycDp1)
    (association-reaction p27p1 cdk46p2-cycD p27p1-cdk46p2-cycD)
    (synthesis-reaction p53 c-Fos) 
    (association-reaction p53 DP12p1 p53-DP12p1)
    (association-reaction p53 DP12 p53-DP12)
    (synthesis-reaction p53 Gadd45) 
    (synthesis-reaction p53 Mdm2) 
    (synthesis-reaction p53p1 c-Fos) 
    (association-reaction p53p1 DP12p1 p53p1-DP12p1)
    (association-reaction p53p1 DP12 p53p1-DP12)
    (synthesis-reaction p53p1 Gadd45) 
    (synthesis-reaction p53p1 Mdm2) 
    (synthesis-reaction p53p1 p21) 
    (synthesis-reaction p53 p21) 
    (association-reaction p57 cdk2-cycA p57-cdk2-cycA)
    (association-reaction p57 cdk2-cycEp1 p57-cdk2-cycEp1)
    (association-reaction p57 cdk2-cycE p57-cdk2-cycE)
    (association-reaction p57 cdk2p1-cycA p57-cdk2p1-cycA)
    (association-reaction p57 cdk2p1-cycEp1 p57-cdk2p1-cycEp1)
    (association-reaction p57 cdk2p1-cycE p57-cdk2p1-cycE)
    (association-reaction p57 cdk2p1p2-cycA p57-cdk2p1p2-cycA)
    (association-reaction p57 cdk2p1p2-cycEp1 p57-cdk2p1p2-cycEp1)
    (association-reaction p57 cdk2p1p2-cycE p57-cdk2p1p2-cycE)
    (association-reaction p57 cdk2p2-cycA p57-cdk2p2-cycA)
    (association-reaction p57 cdk2p2-cycEp1 p57-cdk2p2-cycEp1)
    (association-reaction p57 cdk2p2-cycE p57-cdk2p2-cycE)
    (association-reaction p57 cdk46-cycDp1 p57-cdk46-cycDp1)
    (association-reaction p57 cdk46-cycD p57-cdk46-cycD)
    (association-reaction p57 cdk46p1-cycDp1 p57-cdk46p1-cycDp1)
    (association-reaction p57 cdk46p1-cycD p57-cdk46p1-cycD)
    (association-reaction p57 cdk46p1p2-cycDp1 p57-cdk46p1p2-cycDp1)
    (association-reaction p57 cdk46p1p2-cycD p57-cdk46p1p2-cycD)
    (association-reaction p57 cdk46p2-cycDp1 p57-cdk46p2-cycDp1)
    (association-reaction p57 cdk46p2-cycD p57-cdk46p2-cycD)
    (association-reaction p57p1 cdk46-cycDp1 p57p1-cdk46-cycDp1)
    (association-reaction p57p1 cdk46-cycD p57p1-cdk46-cycD)
    (association-reaction p57p1 cdk46p1-cycDp1 p57p1-cdk46p1-cycDp1)
    (association-reaction p57p1 cdk46p1-cycD p57p1-cdk46p1-cycD)
    (association-reaction p57p1 cdk46p1p2-cycDp1 p57p1-cdk46p1p2-cycDp1)
    (association-reaction p57p1 cdk46p1p2-cycD p57p1-cdk46p1p2-cycD)
    (association-reaction p57p1 cdk46p2-cycDp1 p57p1-cdk46p2-cycDp1)
    (association-reaction p57p1 cdk46p2-cycD p57p1-cdk46p2-cycD)
    (catalyzed-association-reaction p68 cdk2p2-cycA p68p2)
    (catalyzed-association-reaction p68 cdk2p2-cycEp1 p68p1)
    (catalyzed-association-reaction p68 cdk2p2-cycE p68p1)
    (catalyzed-association-reaction p68p1 cdk2p2-cycA p68p1p2)
    (catalyzed-association-reaction p68p2 cdk2p2-cycEp1 p68p1p2)
    (catalyzed-association-reaction p68p2 cdk2p2-cycE p68p1p2)
    (association-reaction pCAF p300 pCAF-p300)
    (association-reaction PCNA cycDp1 PCNA-cycDp1)
    (association-reaction PCNA cycD PCNA-cycD)
    (association-reaction PCNA Gadd45 PCNA-Gadd45)
    (association-reaction PCNA-p21 cdk2-cycA PCNA-p21-cdk2-cycA)
    (association-reaction PCNA-p21 cdk2-cycEp1 PCNA-p21-cdk2-cycEp1)
    (association-reaction PCNA-p21 cdk2-cycE PCNA-p21-cdk2-cycE)
    (association-reaction PCNA-p21 cdk2p1-cycA PCNA-p21-cdk2p1-cycA)
    (association-reaction PCNA-p21 cdk2p1-cycEp1 PCNA-p21-cdk2p1-cycEp1)
    (association-reaction PCNA-p21 cdk2p1-cycE PCNA-p21-cdk2p1-cycE)
    (association-reaction PCNA-p21 cdk2p1p2-cycA PCNA-p21-cdk2p1p2-cycA)
    (association-reaction PCNA-p21 cdk2p1p2-cycEp1 PCNA-p21-cdk2p1p2-cycEp1)
    (association-reaction PCNA-p21 cdk2p1p2-cycE PCNA-p21-cdk2p1p2-cycE)
    (association-reaction PCNA-p21 cdk2p2-cycA PCNA-p21-cdk2p2-cycA)
    (association-reaction PCNA-p21 cdk2p2-cycEp1 PCNA-p21-cdk2p2-cycEp1)
    (association-reaction PCNA-p21 cdk2p2-cycE PCNA-p21-cdk2p2-cycE)
    (association-reaction PCNA-p21 cdk46-cycDp1 PCNA-p21-cdk46-cycDp1)
    (association-reaction PCNA-p21 cdk46-cycD PCNA-p21-cdk46-cycD)
    (association-reaction PCNA-p21 cdk46p1-cycDp1 PCNA-p21-cdk46p1-cycDp1)
    (association-reaction PCNA-p21 cdk46p1-cycD PCNA-p21-cdk46p1-cycD)
    (association-reaction PCNA-p21 cdk46p1p2-cycDp1 PCNA-p21-cdk46p1p2-cycDp1)
    (association-reaction PCNA-p21 cdk46p1p2-cycD PCNA-p21-cdk46p1p2-cycD)
    (association-reaction PCNA-p21 cdk46p2-cycDp1 PCNA-p21-cdk46p2-cycDp1)
    (association-reaction PCNA-p21 cdk46p2-cycD PCNA-p21-cdk46p2-cycD)
    (association-reaction PCNA p21 PCNA-p21)
    (synthesis-reaction pRb-AP2-gE-c Ecadherin) 
    (association-reaction pRb-AP2 gE-c pRb-AP2-gE-c)
    (association-reaction pRb AP2 pRb-AP2)
    (catalyzed-association-reaction pRb cdk46p3-cycDp1 pRbp1)
    (catalyzed-association-reaction pRb cdk46p3-cycD pRbp1)
    (association-reaction pRb-E2F13-DP12 gE2 pRb-E2F13-DP12-gE2)
    (association-reaction pRb-E2F13-DP12p1 gE2 pRb-E2F13-DP12p1-gE2)
    (association-reaction pRb E2F13-DP12p1 pRb-E2F13-DP12p1)
    (association-reaction pRb E2F13-DP12 pRb-E2F13-DP12)
    (association-reaction pRb-E2F13p1-DP12 gE2 pRb-E2F13p1-DP12-gE2)
    (association-reaction pRb-E2F13p1-DP12p1 gE2 pRb-E2F13p1-DP12p1-gE2)
    (association-reaction pRb E2F13p1-DP12p1 pRb-E2F13p1-DP12p1)
    (association-reaction pRb E2F13p1-DP12 pRb-E2F13p1-DP12)
    (association-reaction pRb-E2F4-DP12 gE2 pRb-E2F4-DP12-gE2)
    (association-reaction pRb E2F4-DP12p1 pRb-E2F4-DP12p1)
    (association-reaction pRb E2F4-DP12 pRb-E2F4-DP12)
    (association-reaction pRb-E2F4p1-DP12 gE2 pRb-E2F4p1-DP12-gE2)
    (synthesis-reaction pRb-Jun-c-Fos-gERCC1 ERCC1) 
    (association-reaction pRb-Jun-c-Fos gERCC1 pRb-Jun-c-Fos-gERCC1)
    (association-reaction pRb-Jun c-Fos pRb-Jun-c-Fos)
    (association-reaction pRb Jun pRb-Jun)
    (synthesis-reaction pRbp1-AP2-gE-c Ecadherin) 
    (association-reaction pRbp1-AP2 gE-c pRbp1-AP2-gE-c)
    (association-reaction pRbp1 AP2 pRbp1-AP2)
    (catalyzed-association-reaction pRbp1 cdk2p2-cycEp1 pRbp1p2)
    (catalyzed-association-reaction pRbp1 cdk2p2-cycE pRbp1p2)
    (association-reaction pRbp1-E2F13-DP12 gE2 pRbp1-E2F13-DP12-gE2)
    (association-reaction pRbp1-E2F13-DP12p1 gE2 pRbp1-E2F13-DP12p1-gE2)
    (association-reaction pRbp1 E2F13-DP12p1 pRbp1-E2F13-DP12p1)
    (association-reaction pRbp1 E2F13-DP12 pRbp1-E2F13-DP12)
    (association-reaction pRbp1-E2F13p1-DP12 gE2 pRbp1-E2F13p1-DP12-gE2)
    (association-reaction pRbp1-E2F13p1-DP12p1 gE2 pRbp1-E2F13p1-DP12p1-gE2)
    (association-reaction pRbp1 E2F13p1-DP12p1 pRbp1-E2F13p1-DP12p1)
    (association-reaction pRbp1 E2F13p1-DP12 pRbp1-E2F13p1-DP12)
    (association-reaction pRbp1-E2F4-DP12 gE2 pRbp1-E2F4-DP12-gE2)
    (association-reaction pRbp1 E2F4-DP12p1 pRbp1-E2F4-DP12p1)
    (association-reaction pRbp1 E2F4-DP12 pRbp1-E2F4-DP12)
    (association-reaction pRbp1-E2F4p1-DP12 gE2 pRbp1-E2F4p1-DP12-gE2)
    (synthesis-reaction pRbp1-Jun-c-Fos-gERCC1 ERCC1) 
    (association-reaction pRbp1-Jun-c-Fos gERCC1 pRbp1-Jun-c-Fos-gERCC1)
    (association-reaction pRbp1-Jun c-Fos pRbp1-Jun-c-Fos)
    (association-reaction pRbp1 Jun pRbp1-Jun)
    (synthesis-reaction pRbp1p2-AP2-gE-c Ecadherin) 
    (association-reaction pRbp1p2-AP2 gE-c pRbp1p2-AP2-gE-c)
    (association-reaction pRbp1p2 AP2 pRbp1p2-AP2)
    (synthesis-reaction pRbp1p2-Jun-c-Fos-gERCC1 ERCC1) 
    (association-reaction pRbp1p2-Jun-c-Fos gERCC1 pRbp1p2-Jun-c-Fos-gERCC1)
    (association-reaction pRbp1p2-Jun c-Fos pRbp1p2-Jun-c-Fos)
    (association-reaction pRbp1p2 Jun pRbp1p2-Jun)
    (synthesis-reaction pRbp2-AP2-gE-c Ecadherin) 
    (association-reaction pRbp2-AP2 gE-c pRbp2-AP2-gE-c)
    (association-reaction pRbp2 AP2 pRbp2-AP2)
    (catalyzed-association-reaction pRbp2 cdk46p3-cycDp1 pRbp1p2)
    (catalyzed-association-reaction pRbp2 cdk46p3-cycD pRbp1p2)
    (synthesis-reaction pRbp2-Jun-c-Fos-gERCC1 ERCC1) 
    (association-reaction pRbp2-Jun-c-Fos gERCC1 pRbp2-Jun-c-Fos-gERCC1)
    (association-reaction pRbp2-Jun c-Fos pRbp2-Jun-c-Fos)
    (association-reaction pRbp2 Jun pRbp2-Jun)
    (association-reaction Raf1 cdc25Ap1 Raf1-cdc25Ap1)
    (association-reaction Raf1 cdc25A Raf1-cdc25A)
    (synthesis-reaction Raf1-p130-E2F4-DP12-gE2 c-Myc) 
    (synthesis-reaction Raf1-p130-E2F4-DP12-gE2 cycA) 
    (synthesis-reaction Raf1-p130-E2F4-DP12-gE2 cycD) 
    (synthesis-reaction Raf1-p130-E2F4-DP12-gE2 cycDp1) 
    (synthesis-reaction Raf1-p130-E2F4-DP12-gE2 cycE) 
    (synthesis-reaction Raf1-p130-E2F4-DP12-gE2 cycEp1) 
    (synthesis-reaction Raf1-p130-E2F4-DP12-gE2 p107) 
    (synthesis-reaction Raf1-p130-E2F4-DP12-gE2 p107p1) 
    (synthesis-reaction Raf1-p130-E2F4-DP12-gE2 p19ARF) 
    (synthesis-reaction Raf1-p130-E2F4-DP12-gE2 pol) 
    (association-reaction Raf1-p130-E2F4-DP12 gE2 Raf1-p130-E2F4-DP12-gE2)
    (association-reaction Raf1 p130-E2F4-DP12 Raf1-p130-E2F4-DP12)
    (synthesis-reaction Raf1-p130-E2F4p1-DP12-gE2 c-Myc) 
    (synthesis-reaction Raf1-p130-E2F4p1-DP12-gE2 cycA) 
    (synthesis-reaction Raf1-p130-E2F4p1-DP12-gE2 cycD) 
    (synthesis-reaction Raf1-p130-E2F4p1-DP12-gE2 cycDp1) 
    (synthesis-reaction Raf1-p130-E2F4p1-DP12-gE2 cycE) 
    (synthesis-reaction Raf1-p130-E2F4p1-DP12-gE2 cycEp1) 
    (synthesis-reaction Raf1-p130-E2F4p1-DP12-gE2 p107) 
    (synthesis-reaction Raf1-p130-E2F4p1-DP12-gE2 p107p1) 
    (synthesis-reaction Raf1-p130-E2F4p1-DP12-gE2 p19ARF) 
    (synthesis-reaction Raf1-p130-E2F4p1-DP12-gE2 pol) 
    (association-reaction Raf1-p130-E2F4p1-DP12 gE2 Raf1-p130-E2F4p1-DP12-gE2)
    (association-reaction Raf1 p130-E2F4p1-DP12 Raf1-p130-E2F4p1-DP12)
    (synthesis-reaction Raf1-p130-E2F5-DP12-gE2 c-Myc) 
    (synthesis-reaction Raf1-p130-E2F5-DP12-gE2 cycA) 
    (synthesis-reaction Raf1-p130-E2F5-DP12-gE2 cycD) 
    (synthesis-reaction Raf1-p130-E2F5-DP12-gE2 cycDp1) 
    (synthesis-reaction Raf1-p130-E2F5-DP12-gE2 cycE) 
    (synthesis-reaction Raf1-p130-E2F5-DP12-gE2 cycEp1) 
    (synthesis-reaction Raf1-p130-E2F5-DP12-gE2 p107) 
    (synthesis-reaction Raf1-p130-E2F5-DP12-gE2 p107p1) 
    (synthesis-reaction Raf1-p130-E2F5-DP12-gE2 p19ARF) 
    (synthesis-reaction Raf1-p130-E2F5-DP12-gE2 pol) 
    (association-reaction Raf1-p130-E2F5-DP12 gE2 Raf1-p130-E2F5-DP12-gE2)
    (association-reaction Raf1 p130-E2F5-DP12 Raf1-p130-E2F5-DP12)
    (synthesis-reaction Raf1-p130-E2F5p1-DP12-gE2 c-Myc) 
    (synthesis-reaction Raf1-p130-E2F5p1-DP12-gE2 cycA) 
    (synthesis-reaction Raf1-p130-E2F5p1-DP12-gE2 cycD) 
    (synthesis-reaction Raf1-p130-E2F5p1-DP12-gE2 cycDp1) 
    (synthesis-reaction Raf1-p130-E2F5p1-DP12-gE2 cycE) 
    (synthesis-reaction Raf1-p130-E2F5p1-DP12-gE2 cycEp1) 
    (synthesis-reaction Raf1-p130-E2F5p1-DP12-gE2 p107) 
    (synthesis-reaction Raf1-p130-E2F5p1-DP12-gE2 p107p1) 
    (synthesis-reaction Raf1-p130-E2F5p1-DP12-gE2 p19ARF) 
    (synthesis-reaction Raf1-p130-E2F5p1-DP12-gE2 pol) 
    (association-reaction Raf1-p130-E2F5p1-DP12 gE2 Raf1-p130-E2F5p1-DP12-gE2)
    (association-reaction Raf1 p130-E2F5p1-DP12 Raf1-p130-E2F5p1-DP12)
    (synthesis-reaction Raf1-pRb-E2F13-DP12-gE2 c-Myc) 
    (synthesis-reaction Raf1-pRb-E2F13-DP12-gE2 cycA) 
    (synthesis-reaction Raf1-pRb-E2F13-DP12-gE2 cycD) 
    (synthesis-reaction Raf1-pRb-E2F13-DP12-gE2 cycDp1) 
    (synthesis-reaction Raf1-pRb-E2F13-DP12-gE2 cycE) 
    (synthesis-reaction Raf1-pRb-E2F13-DP12-gE2 cycEp1) 
    (synthesis-reaction Raf1-pRb-E2F13-DP12-gE2 p107) 
    (synthesis-reaction Raf1-pRb-E2F13-DP12-gE2 p107p1) 
    (synthesis-reaction Raf1-pRb-E2F13-DP12-gE2 p19ARF) 
    (synthesis-reaction Raf1-pRb-E2F13-DP12-gE2 pol) 
    (association-reaction Raf1-pRb-E2F13-DP12 gE2 Raf1-pRb-E2F13-DP12-gE2)
    (synthesis-reaction Raf1-pRb-E2F13-DP12p1-gE2 c-Myc) 
    (synthesis-reaction Raf1-pRb-E2F13-DP12p1-gE2 cycA) 
    (synthesis-reaction Raf1-pRb-E2F13-DP12p1-gE2 cycD) 
    (synthesis-reaction Raf1-pRb-E2F13-DP12p1-gE2 cycDp1) 
    (synthesis-reaction Raf1-pRb-E2F13-DP12p1-gE2 cycE) 
    (synthesis-reaction Raf1-pRb-E2F13-DP12p1-gE2 cycEp1) 
    (synthesis-reaction Raf1-pRb-E2F13-DP12p1-gE2 p107) 
    (synthesis-reaction Raf1-pRb-E2F13-DP12p1-gE2 p107p1) 
    (synthesis-reaction Raf1-pRb-E2F13-DP12p1-gE2 p19ARF) 
    (synthesis-reaction Raf1-pRb-E2F13-DP12p1-gE2 pol) 
    (association-reaction Raf1-pRb-E2F13-DP12p1 gE2 Raf1-pRb-E2F13-DP12p1-gE2)
    (association-reaction Raf1 pRb-E2F13-DP12p1 Raf1-pRb-E2F13-DP12p1)
    (association-reaction Raf1 pRb-E2F13-DP12 Raf1-pRb-E2F13-DP12)
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12-gE2 c-Myc) 
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12-gE2 cycA) 
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12-gE2 cycD) 
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12-gE2 cycDp1) 
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12-gE2 cycE) 
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12-gE2 cycEp1) 
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12-gE2 p107) 
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12-gE2 p107p1) 
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12-gE2 p19ARF) 
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12-gE2 pol) 
    (association-reaction Raf1-pRb-E2F13p1-DP12 gE2 Raf1-pRb-E2F13p1-DP12-gE2)
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12p1-gE2 c-Myc) 
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12p1-gE2 cycA) 
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12p1-gE2 cycD) 
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12p1-gE2 cycDp1) 
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12p1-gE2 cycE) 
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12p1-gE2 cycEp1) 
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12p1-gE2 p107) 
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12p1-gE2 p107p1) 
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12p1-gE2 p19ARF) 
    (synthesis-reaction Raf1-pRb-E2F13p1-DP12p1-gE2 pol) 
    (association-reaction Raf1-pRb-E2F13p1-DP12p1 gE2 Raf1-pRb-E2F13p1-DP12p1-gE2)
    (association-reaction Raf1 pRb-E2F13p1-DP12p1 Raf1-pRb-E2F13p1-DP12p1)
    (association-reaction Raf1 pRb-E2F13p1-DP12 Raf1-pRb-E2F13p1-DP12)
    (synthesis-reaction Raf1-pRb-E2F4-DP12-gE2 c-Myc) 
    (synthesis-reaction Raf1-pRb-E2F4-DP12-gE2 cycA) 
    (synthesis-reaction Raf1-pRb-E2F4-DP12-gE2 cycD) 
    (synthesis-reaction Raf1-pRb-E2F4-DP12-gE2 cycDp1) 
    (synthesis-reaction Raf1-pRb-E2F4-DP12-gE2 cycE) 
    (synthesis-reaction Raf1-pRb-E2F4-DP12-gE2 cycEp1) 
    (synthesis-reaction Raf1-pRb-E2F4-DP12-gE2 p107) 
    (synthesis-reaction Raf1-pRb-E2F4-DP12-gE2 p107p1) 
    (synthesis-reaction Raf1-pRb-E2F4-DP12-gE2 p19ARF) 
    (synthesis-reaction Raf1-pRb-E2F4-DP12-gE2 pol) 
    (association-reaction Raf1-pRb-E2F4-DP12 gE2 Raf1-pRb-E2F4-DP12-gE2)
    (association-reaction Raf1 pRb-E2F4-DP12 Raf1-pRb-E2F4-DP12)
    (synthesis-reaction Raf1-pRb-E2F4p1-DP12-gE2 c-Myc) 
    (synthesis-reaction Raf1-pRb-E2F4p1-DP12-gE2 cycA) 
    (synthesis-reaction Raf1-pRb-E2F4p1-DP12-gE2 cycD) 
    (synthesis-reaction Raf1-pRb-E2F4p1-DP12-gE2 cycDp1) 
    (synthesis-reaction Raf1-pRb-E2F4p1-DP12-gE2 cycE) 
    (synthesis-reaction Raf1-pRb-E2F4p1-DP12-gE2 cycEp1) 
    (synthesis-reaction Raf1-pRb-E2F4p1-DP12-gE2 p107) 
    (synthesis-reaction Raf1-pRb-E2F4p1-DP12-gE2 p107p1) 
    (synthesis-reaction Raf1-pRb-E2F4p1-DP12-gE2 p19ARF) 
    (synthesis-reaction Raf1-pRb-E2F4p1-DP12-gE2 pol) 
    (association-reaction Raf1-pRb-E2F4p1-DP12 gE2 Raf1-pRb-E2F4p1-DP12-gE2)
    (association-reaction Raf1 pRb-E2F4p1-DP12 Raf1-pRb-E2F4p1-DP12)
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12-gE2 c-Myc) 
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12-gE2 cycA) 
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12-gE2 cycD) 
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12-gE2 cycDp1) 
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12-gE2 cycE) 
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12-gE2 cycEp1) 
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12-gE2 p107) 
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12-gE2 p107p1) 
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12-gE2 p19ARF) 
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12-gE2 pol) 
    (association-reaction Raf1-pRbp1-E2F13-DP12 gE2 Raf1-pRbp1-E2F13-DP12-gE2)
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12p1-gE2 c-Myc) 
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12p1-gE2 cycA) 
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12p1-gE2 cycD) 
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12p1-gE2 cycDp1) 
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12p1-gE2 cycE) 
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12p1-gE2 cycEp1) 
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12p1-gE2 p107) 
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12p1-gE2 p107p1) 
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12p1-gE2 p19ARF) 
    (synthesis-reaction Raf1-pRbp1-E2F13-DP12p1-gE2 pol) 
    (association-reaction Raf1-pRbp1-E2F13-DP12p1 gE2 Raf1-pRbp1-E2F13-DP12p1-gE2)
    (association-reaction Raf1 pRbp1-E2F13-DP12p1 Raf1-pRbp1-E2F13-DP12p1)
    (association-reaction Raf1 pRbp1-E2F13-DP12 Raf1-pRbp1-E2F13-DP12)
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12-gE2 c-Myc) 
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12-gE2 cycA) 
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12-gE2 cycD) 
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12-gE2 cycDp1) 
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12-gE2 cycE) 
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12-gE2 cycEp1) 
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12-gE2 p107) 
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12-gE2 p107p1) 
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12-gE2 p19ARF) 
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12-gE2 pol) 
    (association-reaction Raf1-pRbp1-E2F13p1-DP12 gE2 Raf1-pRbp1-E2F13p1-DP12-gE2)
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12p1-gE2 c-Myc) 
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12p1-gE2 cycA) 
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12p1-gE2 cycD) 
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12p1-gE2 cycDp1) 
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12p1-gE2 cycE) 
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12p1-gE2 cycEp1) 
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12p1-gE2 p107) 
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12p1-gE2 p107p1) 
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12p1-gE2 p19ARF) 
    (synthesis-reaction Raf1-pRbp1-E2F13p1-DP12p1-gE2 pol) 
    (association-reaction Raf1-pRbp1-E2F13p1-DP12p1 gE2 Raf1-pRbp1-E2F13p1-DP12p1-gE2)
    (association-reaction Raf1 pRbp1-E2F13p1-DP12p1 Raf1-pRbp1-E2F13p1-DP12p1)
    (association-reaction Raf1 pRbp1-E2F13p1-DP12 Raf1-pRbp1-E2F13p1-DP12)
    (synthesis-reaction Raf1-pRbp1-E2F4-DP12-gE2 c-Myc) 
    (synthesis-reaction Raf1-pRbp1-E2F4-DP12-gE2 cycA) 
    (synthesis-reaction Raf1-pRbp1-E2F4-DP12-gE2 cycD) 
    (synthesis-reaction Raf1-pRbp1-E2F4-DP12-gE2 cycDp1) 
    (synthesis-reaction Raf1-pRbp1-E2F4-DP12-gE2 cycE) 
    (synthesis-reaction Raf1-pRbp1-E2F4-DP12-gE2 cycEp1) 
    (synthesis-reaction Raf1-pRbp1-E2F4-DP12-gE2 p107) 
    (synthesis-reaction Raf1-pRbp1-E2F4-DP12-gE2 p107p1) 
    (synthesis-reaction Raf1-pRbp1-E2F4-DP12-gE2 p19ARF) 
    (synthesis-reaction Raf1-pRbp1-E2F4-DP12-gE2 pol) 
    (association-reaction Raf1-pRbp1-E2F4-DP12 gE2 Raf1-pRbp1-E2F4-DP12-gE2)
    (association-reaction Raf1 pRbp1-E2F4-DP12 Raf1-pRbp1-E2F4-DP12)
    (synthesis-reaction Raf1-pRbp1-E2F4p1-DP12-gE2 c-Myc) 
    (synthesis-reaction Raf1-pRbp1-E2F4p1-DP12-gE2 cycA) 
    (synthesis-reaction Raf1-pRbp1-E2F4p1-DP12-gE2 cycD) 
    (synthesis-reaction Raf1-pRbp1-E2F4p1-DP12-gE2 cycDp1) 
    (synthesis-reaction Raf1-pRbp1-E2F4p1-DP12-gE2 cycE) 
    (synthesis-reaction Raf1-pRbp1-E2F4p1-DP12-gE2 cycEp1) 
    (synthesis-reaction Raf1-pRbp1-E2F4p1-DP12-gE2 p107) 
    (synthesis-reaction Raf1-pRbp1-E2F4p1-DP12-gE2 p107p1) 
    (synthesis-reaction Raf1-pRbp1-E2F4p1-DP12-gE2 p19ARF) 
    (synthesis-reaction Raf1-pRbp1-E2F4p1-DP12-gE2 pol) 
    (association-reaction Raf1-pRbp1-E2F4p1-DP12 gE2 Raf1-pRbp1-E2F4p1-DP12-gE2)
    (association-reaction Raf1 pRbp1-E2F4p1-DP12 Raf1-pRbp1-E2F4p1-DP12)
    (association-reaction RPA cycA RPA-cycA)
    (catalyzed-association-reaction Skp1 cdk2p2-cycA Skp1p1)
    (association-reaction Skp2 cdk2-cycA Skp2-cdk2-cycA)
    (association-reaction Skp2 cdk2p1-cycA Skp2-cdk2p1-cycA)
    (association-reaction Skp2 cdk2p1p2-cycA Skp2-cdk2p1p2-cycA)
    (association-reaction Skp2 cdk2p2-cycA Skp2-cdk2p2-cycA)
    (catalyzed-association-reaction Skp2 cdk2p2-cycA Skp2p1)
    (association-reaction Skp2p1 Skp1p1 Skp2p1-Skp1p1)
    (association-reaction Skp2p1 Skp1 Skp2p1-Skp1)
    (association-reaction Skp2-Skp1 cdk2-cycA Skp2-Skp1-cdk2-cycA)
    (association-reaction Skp2-Skp1 cdk2p1-cycA Skp2-Skp1-cdk2p1-cycA)
    (association-reaction Skp2-Skp1 cdk2p1p2-cycA Skp2-Skp1-cdk2p1p2-cycA)
    (association-reaction Skp2-Skp1 cdk2p2-cycA Skp2-Skp1-cdk2p2-cycA)
    (association-reaction Skp2-Skp1p1 cdk2-cycA Skp2-Skp1p1-cdk2-cycA)
    (association-reaction Skp2-Skp1p1 cdk2p1-cycA Skp2-Skp1p1-cdk2p1-cycA)
    (association-reaction Skp2-Skp1p1 cdk2p1p2-cycA Skp2-Skp1p1-cdk2p1p2-cycA)
    (association-reaction Skp2-Skp1p1 cdk2p2-cycA Skp2-Skp1p1-cdk2p2-cycA)
    (association-reaction Skp2 Skp1p1 Skp2-Skp1p1)
    (association-reaction Skp2 Skp1 Skp2-Skp1)
    (catalyzed-association-reaction SL1 cdk1p3-cycA SL1p1)
    (catalyzed-association-reaction SL1 cdk1p3-cycB SL1p1)
    (synthesis-reaction SP1-E2F13-gP c-Myc) 
    (synthesis-reaction SP1-E2F13-gP cycA) 
    (synthesis-reaction SP1-E2F13-gP cycD) 
    (synthesis-reaction SP1-E2F13-gP cycDp1) 
    (synthesis-reaction SP1-E2F13-gP cycE) 
    (synthesis-reaction SP1-E2F13-gP cycEp1) 
    (synthesis-reaction SP1-E2F13-gP p107) 
    (synthesis-reaction SP1-E2F13-gP p107p1) 
    (synthesis-reaction SP1-E2F13-gP p19ARF) 
    (synthesis-reaction SP1-E2F13-gP pol) 
    (association-reaction SP1-E2F13 gP SP1-E2F13-gP)
    (synthesis-reaction SP1-E2F13p1-gP c-Myc) 
    (synthesis-reaction SP1-E2F13p1-gP cycA) 
    (synthesis-reaction SP1-E2F13p1-gP cycD) 
    (synthesis-reaction SP1-E2F13p1-gP cycDp1) 
    (synthesis-reaction SP1-E2F13p1-gP cycE) 
    (synthesis-reaction SP1-E2F13p1-gP cycEp1) 
    (synthesis-reaction SP1-E2F13p1-gP p107) 
    (synthesis-reaction SP1-E2F13p1-gP p107p1) 
    (synthesis-reaction SP1-E2F13p1-gP p19ARF) 
    (synthesis-reaction SP1-E2F13p1-gP pol) 
    (association-reaction SP1-E2F13p1 gP SP1-E2F13p1-gP)
    (association-reaction SP1 E2F13p1 SP1-E2F13p1)
    (association-reaction SP1 E2F13 SP1-E2F13)
    (synthesis-reaction SP1-gP c-Myc) 
    (synthesis-reaction SP1-gP cycA) 
    (synthesis-reaction SP1-gP cycD) 
    (synthesis-reaction SP1-gP cycDp1) 
    (synthesis-reaction SP1-gP cycE) 
    (synthesis-reaction SP1-gP cycEp1) 
    (synthesis-reaction SP1-gP p107) 
    (synthesis-reaction SP1-gP p107p1) 
    (synthesis-reaction SP1-gP p19ARF) 
    (synthesis-reaction SP1-gP pol) 
    (association-reaction SP1 gP SP1-gP)
    (association-reaction SP1-p107 gP SP1-p107-gP)
    (association-reaction SP1-p107p1 gP SP1-p107p1-gP)
    (association-reaction SP1 p107p1 SP1-p107p1)
    (association-reaction SP1 p107 SP1-p107)
    (catalyzed-association-reaction Wee1 cdk1p3-cycA Wee1p1)
    (catalyzed-association-reaction Wee1 cdk1p3-cycB Wee1p1)
    (num-subs l0)
    (next l1 l0)
    (next l2 l1)
    (next l3 l2)
    (next l4 l3)
    (next l5 l4)
    (next l6 l5)
    (next l7 l6)
    (next l8 l7)
    (next l9 l8)
    (next l10 l9)
    (next l11 l10)
    (next l12 l11)
    (next l13 l12)
    (next l14 l13)
    (next l15 l14)
    (next l16 l15)
    (next l17 l16)
    (next l18 l17)
    (next l19 l18)
    (next l20 l19)
    (next l21 l20)
    (next l22 l21)
    (next l23 l22)
    (next l24 l23)
    (next l25 l24)
    (next l26 l25)
    (next l27 l26)
    (next l28 l27)
    (next l29 l28)
    (next l30 l29)
    (next l31 l30)
    (next l32 l31)
    (next l33 l32)
    (next l34 l33)
    (next l35 l34)
    (next l36 l35)
    (next l37 l36)
    (next l38 l37)
    (next l39 l38)
    (next l40 l39)
    (next l41 l40)
    (next l42 l41)
    (next l43 l42)
    (next l44 l43)
    (next l45 l44)
    (next l46 l45)
    (next l47 l46)
    (next l48 l47)
    (next l49 l48)
    (next l50 l49)
    (next l51 l50)
    (next l52 l51)
    (next l53 l52)
    (next l54 l53)
    (next l55 l54)
    (next l56 l55)
    (next l57 l56)
    (next l58 l57)
    (next l59 l58)
    (next l60 l59)
    (next l61 l60)
    (next l62 l61)
    (next l63 l62)
    (next l64 l63)
    (next l65 l64)
    (next l66 l65)
    (next l67 l66)
    (next l68 l67)
    (next l69 l68)
    (next l70 l69)
    (next l71 l70)
    (next l72 l71)
    (next l73 l72)
    (next l74 l73)
    (next l75 l74)
    (next l76 l75)
    (next l77 l76)
    (next l78 l77)
    (next l79 l78)
    (next l80 l79)
    (next l81 l80)
    (next l82 l81)
    (next l83 l82)
    (next l84 l83)
    (next l85 l84)
    (next l86 l85)
    (next l87 l86)
    (next l88 l87)
    (next l89 l88)
    (next l90 l89)
    (next l91 l90)
    (next l92 l91)
    (next l93 l92)
    (next l94 l93)
    (next l95 l94)
    (next l96 l95)
    (next l97 l96)
    (next l98 l97)
    (next l99 l98)
    (next l100 l99)
    (next l101 l100)
    (next l102 l101)
    (next l103 l102)
    (next l104 l103)
    (next l105 l104)
    (next l106 l105)
    (next l107 l106)
    (next l108 l107)
    (next l109 l108)
    (next l110 l109)
    (next l111 l110)
    (next l112 l111)
    (next l113 l112)
    (next l114 l113)
    (next l115 l114)
    (next l116 l115)
    (next l117 l116)
    (next l118 l117)
    (next l119 l118)
    (next l120 l119)
    (next l121 l120)
    (next l122 l121)
    (next l123 l122)
    (next l124 l123)
    (next l125 l124)
    (next l126 l125)
    (next l127 l126)
    (next l128 l127)
    (next l129 l128)
    (next l130 l129)
    (next l131 l130)
    (next l132 l131)
    (next l133 l132)
    (next l134 l133)
    (next l135 l134)
    (next l136 l135)
    (next l137 l136)
    (next l138 l137)
    (next l139 l138)
    (next l140 l139)
    (next l141 l140)
    (next l142 l141)
    (next l143 l142)
    (next l144 l143)
    (next l145 l144)
    (next l146 l145)
    (next l147 l146)
    (next l148 l147)
    (next l149 l148)
    (next l150 l149)
    (next l151 l150)
    (next l152 l151)
    (next l153 l152)
    (next l154 l153)
    (next l155 l154)
    (next l156 l155)
    (next l157 l156)
    (next l158 l157)
    (next l159 l158)
    (next l160 l159)
    (next l161 l160)
    (next l162 l161)
    (next l163 l162)
    (next l164 l163)
    (next l165 l164)
    (next l166 l165)
    (next l167 l166)
    (next l168 l167)
    (next l169 l168)
    (next l170 l169)
    (next l171 l170)
    (next l172 l171)
    (next l173 l172)
    (next l174 l173)
    (next l175 l174)
    (next l176 l175)
    (next l177 l176)
    (next l178 l177)
    (next l179 l178)
    (next l180 l179)
    (next l181 l180)
    (next l182 l181)
    (next l183 l182)
    (next l184 l183)
    (next l185 l184)
    (next l186 l185)
    (next l187 l186)
    (next l188 l187)
    (next l189 l188)
    (next l190 l189)
    (next l191 l190)
    (next l192 l191)
    (next l193 l192)
    (next l194 l193)
    (next l195 l194)
    (next l196 l195)
    (next l197 l196)
    (next l198 l197)
    (next l199 l198)
    (next l200 l199)
    (next l201 l200)
    (next l202 l201)
    (next l203 l202)
    (next l204 l203)
    (next l205 l204)
    (next l206 l205)
    (next l207 l206)
    (next l208 l207)
    (next l209 l208)
    (next l210 l209)
    (next l211 l210)
    (next l212 l211)
    (next l213 l212)
    (next l214 l213)
    (next l215 l214)
    (next l216 l215)
    (next l217 l216)
    (next l218 l217)
    (next l219 l218)
    (next l220 l219)
    (next l221 l220)
    (next l222 l221)
    (next l223 l222)
    (next l224 l223)
    (next l225 l224)
    (next l226 l225)
    (next l227 l226)
    (next l228 l227)
    (next l229 l228)
    (next l230 l229)
    (next l231 l230)
    (next l232 l231)
    (next l233 l232)
    (next l234 l233)
    (next l235 l234)
    (next l236 l235)
    (next l237 l236)
    (next l238 l237)
    (next l239 l238)
    (next l240 l239)
    (next l241 l240)
    (next l242 l241)
    (next l243 l242)
    (next l244 l243)
    (next l245 l244)
    (next l246 l245)
    (next l247 l246)
    (next l248 l247)
    (next l249 l248)
    (next l250 l249)
    (next l251 l250)
    (next l252 l251)
    (next l253 l252)
    (next l254 l253)
    (next l255 l254)
    (next l256 l255)
    (next l257 l256)
    (next l258 l257)
    (next l259 l258)
    (next l260 l259)
    (next l261 l260)
    (next l262 l261)
    (next l263 l262)
    (next l264 l263)
    (next l265 l264)
    (next l266 l265)
    (next l267 l266)
    (next l268 l267)
    (next l269 l268)
    (next l270 l269)
    (next l271 l270)
    (next l272 l271)
    (next l273 l272)
    (next l274 l273)
    (next l275 l274)
    (next l276 l275)
    (next l277 l276)
    (next l278 l277)
    (next l279 l278)
    (next l280 l279)
    (next l281 l280)
    (next l282 l281)
    (next l283 l282)
    (next l284 l283)
    (next l285 l284)
    (next l286 l285)
    (next l287 l286)
    (next l288 l287)
    (next l289 l288)
    (next l290 l289)
    (next l291 l290)
    (next l292 l291)
    (next l293 l292)
    (next l294 l293)
    (next l295 l294)
    (next l296 l295)
    (next l297 l296)
    (next l298 l297)
    (next l299 l298)
    (next l300 l299)
    (next l301 l300)
    (next l302 l301)
    (next l303 l302)
    (next l304 l303)
    (next l305 l304)
    (next l306 l305)
    (next l307 l306)
    (next l308 l307)
    (next l309 l308)
    (next l310 l309)
    (next l311 l310)
    (next l312 l311)
    (next l313 l312)
    (next l314 l313)
    (next l315 l314)
    (next l316 l315)
    (next l317 l316)
    (next l318 l317)
    (next l319 l318)
    (next l320 l319)
    (next l321 l320)
    (next l322 l321)
    (next l323 l322)
    (next l324 l323)
    (next l325 l324)
    (next l326 l325)
    (next l327 l326)
    (next l328 l327)
    (next l329 l328)
    (next l330 l329)
    (next l331 l330)
    (next l332 l331)
    (next l333 l332)
    (next l334 l333)
    (next l335 l334)
    (next l336 l335)
    (next l337 l336)
    (next l338 l337))


(:goal
    (and
    (goal1)
    (goal2)))

)
