( DEFINE ( DOMAIN EXCEL )
( :REQUIREMENTS :ACTION-COSTS :CONDITIONAL-EFFECTS :TYPING :NEGATIVE-PRECONDITIONS :ADL)
( :TYPES
	CHAR - OBJECT
	LIMITER - CHAR
	STRING - OBJECT
	INPUT - STRING
	OUTPUT - STRING
	INDEX - OBJECT
	INPUT-VARIABLE - OBJECT
	STACKROW - OBJECT
)
( :CONSTANTS
	 A   B   C   D   F   G   H   L   O   Q   T   U   - CHAR
	 SPACE   - LIMITER
	STR STR2 - INPUT
	RES - OUTPUT
	I0 I1 I10 I11 I12 I2 I3 I4 I5 I6 I7 I8 I9 - INDEX
	STR-VAR STR2-VAR - INPUT-VARIABLE
	ROW-0 ROW-1 - STACKROW
)
( :PREDICATES
	( ASSIGNMENT ?STRING0 - STRING ?INDEX1 - INDEX ?CHAR2 - CHAR )
	( LOINDEX ?INPUT0 - INPUT ?INDEX1 - INDEX )
	( HIINDEX ?INPUT0 - INPUT ?INDEX1 - INDEX )
	( SIZE ?STRING0 - STRING ?INDEX1 - INDEX )
	( EMPTY ?INPUT-VARIABLE0 - INPUT-VARIABLE )
	( NEXT ?INDEX0 - INDEX ?INDEX1 - INDEX )
	( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 - INPUT-VARIABLE ?INPUT1 - INPUT ?STACKROW2 - STACKROW )
	( EMPTY-STACK )
	( NEXT-STACK-ROW ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
	( TOP-STACK ?STACKROW0 - STACKROW )
	( ACCUMULATOR )
	( DONE-EVALUATING )
	( DONE-PROGRAMMING )
	( STACK-MAIN ?STACKROW0 - STACKROW )
	( STACK-LINE-0 ?STACKROW0 - STACKROW )
	( STACK-LINE-1 ?STACKROW0 - STACKROW )
	( STACK-LINE-2 ?STACKROW0 - STACKROW )
	( STACK-LINE-3 ?STACKROW0 - STACKROW )
	( TEST-0 )
	( TEST-1 )
	( EMPTY-0 )
	( EMPTY-1 )
	( EMPTY-2 )
	( EMPTY-3 )
	( INS-END-1 )
	( INS-END-2 )
	( INS-END-3 )
	( CALL-0-0-0 ?INPUT-VARIABLE0 - INPUT-VARIABLE )
	( CALL-0-0-1 ?INPUT-VARIABLE0 - INPUT-VARIABLE )
	( CALL-0-0-2 ?INPUT-VARIABLE0 - INPUT-VARIABLE )
	( INS-APPEND-CHAR-0 ?OUTPUT0 - OUTPUT ?LIMITER1 - LIMITER )
	( INS-APPEND-CHAR-1 ?OUTPUT0 - OUTPUT ?LIMITER1 - LIMITER )
	( INS-APPEND-CHAR-2 ?OUTPUT0 - OUTPUT ?LIMITER1 - LIMITER )
	( INS-APPEND-STR-0 ?OUTPUT0 - OUTPUT ?INPUT-VARIABLE1 - INPUT-VARIABLE )
	( INS-APPEND-STR-1 ?OUTPUT0 - OUTPUT ?INPUT-VARIABLE1 - INPUT-VARIABLE )
	( INS-APPEND-STR-2 ?OUTPUT0 - OUTPUT ?INPUT-VARIABLE1 - INPUT-VARIABLE )
	( INS-INC-LOINDEX-0 ?INPUT-VARIABLE0 - INPUT-VARIABLE )
	( INS-INC-LOINDEX-1 ?INPUT-VARIABLE0 - INPUT-VARIABLE )
	( INS-INC-LOINDEX-2 ?INPUT-VARIABLE0 - INPUT-VARIABLE )
	( INS-GET-PREFIX-0 ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER )
	( INS-GET-PREFIX-1 ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER )
	( INS-GET-PREFIX-2 ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER )
	( INS-GET-SUFFIX-0 ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER )
	( INS-GET-SUFFIX-1 ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER )
	( INS-GET-SUFFIX-2 ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER )
	( INS-GET-SUBSTR-0 ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?LIMITER2 - LIMITER )
	( INS-GET-SUBSTR-1 ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?LIMITER2 - LIMITER )
	( INS-GET-SUBSTR-2 ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?LIMITER2 - LIMITER )
	( GOTO-0-0-0 )
	( GOTO-0-0-1 )
	( GOTO-0-0-2 )
	( GOTO-0-0-3 )
	( GOTO-0-1-0 )
	( GOTO-0-1-1 )
	( GOTO-0-1-2 )
	( GOTO-0-1-3 )
	( GOTO-0-2-0 )
	( GOTO-0-2-1 )
	( GOTO-0-2-2 )
	( GOTO-0-2-3 )
	( COND-ASSIGNMENT-0-0 ?STRING0 - STRING ?INDEX1 - INDEX ?CHAR2 - CHAR )
	( COND-ASSIGNMENT-0-1 ?STRING0 - STRING ?INDEX1 - INDEX ?CHAR2 - CHAR )
	( COND-ASSIGNMENT-0-2 ?STRING0 - STRING ?INDEX1 - INDEX ?CHAR2 - CHAR )
	( COND-LOINDEX-0-0 ?INPUT0 - INPUT ?INDEX1 - INDEX )
	( COND-LOINDEX-0-1 ?INPUT0 - INPUT ?INDEX1 - INDEX )
	( COND-LOINDEX-0-2 ?INPUT0 - INPUT ?INDEX1 - INDEX )
	( COND-HIINDEX-0-0 ?INPUT0 - INPUT ?INDEX1 - INDEX )
	( COND-HIINDEX-0-1 ?INPUT0 - INPUT ?INDEX1 - INDEX )
	( COND-HIINDEX-0-2 ?INPUT0 - INPUT ?INDEX1 - INDEX )
	( COND-SIZE-0-0 ?STRING0 - STRING ?INDEX1 - INDEX )
	( COND-SIZE-0-1 ?STRING0 - STRING ?INDEX1 - INDEX )
	( COND-SIZE-0-2 ?STRING0 - STRING ?INDEX1 - INDEX )
	( COND-EMPTY-0-0 ?INPUT-VARIABLE0 - INPUT-VARIABLE )
	( COND-EMPTY-0-1 ?INPUT-VARIABLE0 - INPUT-VARIABLE )
	( COND-EMPTY-0-2 ?INPUT-VARIABLE0 - INPUT-VARIABLE )
)
( :FUNCTIONS
	( TOTAL-COST )
)
( :ACTION PROGRAM-APPEND-CHAR-0
  :PARAMETERS ( ?OUTPUT0 - OUTPUT ?LIMITER1 - LIMITER ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( INS-APPEND-CHAR-0 ?OUTPUT0 ?LIMITER1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-APPEND-CHAR-1
  :PARAMETERS ( ?OUTPUT0 - OUTPUT ?LIMITER1 - LIMITER ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-APPEND-CHAR-1 ?OUTPUT0 ?LIMITER1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-APPEND-CHAR-2
  :PARAMETERS ( ?OUTPUT0 - OUTPUT ?LIMITER1 - LIMITER ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-APPEND-CHAR-2 ?OUTPUT0 ?LIMITER1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-APPEND-STR-0
  :PARAMETERS ( ?OUTPUT0 - OUTPUT ?INPUT-VARIABLE1 - INPUT-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( INS-APPEND-STR-0 ?OUTPUT0 ?INPUT-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-APPEND-STR-1
  :PARAMETERS ( ?OUTPUT0 - OUTPUT ?INPUT-VARIABLE1 - INPUT-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-APPEND-STR-1 ?OUTPUT0 ?INPUT-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-APPEND-STR-2
  :PARAMETERS ( ?OUTPUT0 - OUTPUT ?INPUT-VARIABLE1 - INPUT-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-APPEND-STR-2 ?OUTPUT0 ?INPUT-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-INC-LOINDEX-0
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( INS-INC-LOINDEX-0 ?INPUT-VARIABLE0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-INC-LOINDEX-1
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-INC-LOINDEX-1 ?INPUT-VARIABLE0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-INC-LOINDEX-2
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-INC-LOINDEX-2 ?INPUT-VARIABLE0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GET-PREFIX-0
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( INS-GET-PREFIX-0 ?INPUT-VARIABLE0 ?LIMITER1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GET-PREFIX-1
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-GET-PREFIX-1 ?INPUT-VARIABLE0 ?LIMITER1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GET-PREFIX-2
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-GET-PREFIX-2 ?INPUT-VARIABLE0 ?LIMITER1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GET-SUFFIX-0
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( INS-GET-SUFFIX-0 ?INPUT-VARIABLE0 ?LIMITER1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GET-SUFFIX-1
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-GET-SUFFIX-1 ?INPUT-VARIABLE0 ?LIMITER1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GET-SUFFIX-2
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW2 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-GET-SUFFIX-2 ?INPUT-VARIABLE0 ?LIMITER1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GET-SUBSTR-0
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?LIMITER2 - LIMITER ?STACKROW3 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW3 )
		( TOP-STACK ?STACKROW3 )
		( STACK-MAIN ?STACKROW3 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( INS-GET-SUBSTR-0 ?INPUT-VARIABLE0 ?LIMITER1 ?LIMITER2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GET-SUBSTR-1
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?LIMITER2 - LIMITER ?STACKROW3 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW3 )
		( TOP-STACK ?STACKROW3 )
		( STACK-MAIN ?STACKROW3 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-GET-SUBSTR-1 ?INPUT-VARIABLE0 ?LIMITER1 ?LIMITER2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GET-SUBSTR-2
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?LIMITER2 - LIMITER ?STACKROW3 - STACKROW )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW3 )
		( TOP-STACK ?STACKROW3 )
		( STACK-MAIN ?STACKROW3 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-GET-SUBSTR-2 ?INPUT-VARIABLE0 ?LIMITER1 ?LIMITER2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-ASSIGNMENT-0-2
  :PARAMETERS ( ?STRING0 - STRING ?INDEX1 - INDEX ?CHAR2 - CHAR ?STACKROW3 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW3 )
		( STACK-MAIN ?STACKROW3 )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW3 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( GOTO-0-0-2 )
		( COND-ASSIGNMENT-0-0 ?STRING0 ?INDEX1 ?CHAR2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-LOINDEX-0-2
  :PARAMETERS ( ?INPUT0 - INPUT ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( GOTO-0-0-2 )
		( COND-LOINDEX-0-0 ?INPUT0 ?INDEX1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-HIINDEX-0-2
  :PARAMETERS ( ?INPUT0 - INPUT ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( GOTO-0-0-2 )
		( COND-HIINDEX-0-0 ?INPUT0 ?INDEX1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-SIZE-0-2
  :PARAMETERS ( ?STRING0 - STRING ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( GOTO-0-0-2 )
		( COND-SIZE-0-0 ?STRING0 ?INDEX1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-EMPTY-0-2
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( GOTO-0-0-2 )
		( COND-EMPTY-0-0 ?INPUT-VARIABLE0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-ASSIGNMENT-0-3
  :PARAMETERS ( ?STRING0 - STRING ?INDEX1 - INDEX ?CHAR2 - CHAR ?STACKROW3 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW3 )
		( STACK-MAIN ?STACKROW3 )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW3 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( GOTO-0-0-3 )
		( COND-ASSIGNMENT-0-0 ?STRING0 ?INDEX1 ?CHAR2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-LOINDEX-0-3
  :PARAMETERS ( ?INPUT0 - INPUT ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( GOTO-0-0-3 )
		( COND-LOINDEX-0-0 ?INPUT0 ?INDEX1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-HIINDEX-0-3
  :PARAMETERS ( ?INPUT0 - INPUT ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( GOTO-0-0-3 )
		( COND-HIINDEX-0-0 ?INPUT0 ?INDEX1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-SIZE-0-3
  :PARAMETERS ( ?STRING0 - STRING ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( GOTO-0-0-3 )
		( COND-SIZE-0-0 ?STRING0 ?INDEX1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-EMPTY-0-3
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( EMPTY-0 )
		( STACK-LINE-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( GOTO-0-0-3 )
		( COND-EMPTY-0-0 ?INPUT-VARIABLE0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-ASSIGNMENT-1-0
  :PARAMETERS ( ?STRING0 - STRING ?INDEX1 - INDEX ?CHAR2 - CHAR ?STACKROW3 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW3 )
		( STACK-MAIN ?STACKROW3 )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW3 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( GOTO-0-1-0 )
		( COND-ASSIGNMENT-0-1 ?STRING0 ?INDEX1 ?CHAR2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-LOINDEX-1-0
  :PARAMETERS ( ?INPUT0 - INPUT ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( GOTO-0-1-0 )
		( COND-LOINDEX-0-1 ?INPUT0 ?INDEX1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-HIINDEX-1-0
  :PARAMETERS ( ?INPUT0 - INPUT ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( GOTO-0-1-0 )
		( COND-HIINDEX-0-1 ?INPUT0 ?INDEX1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-SIZE-1-0
  :PARAMETERS ( ?STRING0 - STRING ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( GOTO-0-1-0 )
		( COND-SIZE-0-1 ?STRING0 ?INDEX1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-EMPTY-1-0
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( GOTO-0-1-0 )
		( COND-EMPTY-0-1 ?INPUT-VARIABLE0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-ASSIGNMENT-1-3
  :PARAMETERS ( ?STRING0 - STRING ?INDEX1 - INDEX ?CHAR2 - CHAR ?STACKROW3 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW3 )
		( STACK-MAIN ?STACKROW3 )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW3 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( GOTO-0-1-3 )
		( COND-ASSIGNMENT-0-1 ?STRING0 ?INDEX1 ?CHAR2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-LOINDEX-1-3
  :PARAMETERS ( ?INPUT0 - INPUT ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( GOTO-0-1-3 )
		( COND-LOINDEX-0-1 ?INPUT0 ?INDEX1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-HIINDEX-1-3
  :PARAMETERS ( ?INPUT0 - INPUT ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( GOTO-0-1-3 )
		( COND-HIINDEX-0-1 ?INPUT0 ?INDEX1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-SIZE-1-3
  :PARAMETERS ( ?STRING0 - STRING ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( GOTO-0-1-3 )
		( COND-SIZE-0-1 ?STRING0 ?INDEX1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-EMPTY-1-3
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( GOTO-0-1-3 )
		( COND-EMPTY-0-1 ?INPUT-VARIABLE0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-ASSIGNMENT-2-0
  :PARAMETERS ( ?STRING0 - STRING ?INDEX1 - INDEX ?CHAR2 - CHAR ?STACKROW3 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW3 )
		( STACK-MAIN ?STACKROW3 )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW3 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( GOTO-0-2-0 )
		( COND-ASSIGNMENT-0-2 ?STRING0 ?INDEX1 ?CHAR2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-LOINDEX-2-0
  :PARAMETERS ( ?INPUT0 - INPUT ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( GOTO-0-2-0 )
		( COND-LOINDEX-0-2 ?INPUT0 ?INDEX1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-HIINDEX-2-0
  :PARAMETERS ( ?INPUT0 - INPUT ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( GOTO-0-2-0 )
		( COND-HIINDEX-0-2 ?INPUT0 ?INDEX1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-SIZE-2-0
  :PARAMETERS ( ?STRING0 - STRING ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( GOTO-0-2-0 )
		( COND-SIZE-0-2 ?STRING0 ?INDEX1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-EMPTY-2-0
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( GOTO-0-2-0 )
		( COND-EMPTY-0-2 ?INPUT-VARIABLE0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-ASSIGNMENT-2-1
  :PARAMETERS ( ?STRING0 - STRING ?INDEX1 - INDEX ?CHAR2 - CHAR ?STACKROW3 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW3 )
		( STACK-MAIN ?STACKROW3 )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW3 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( GOTO-0-2-1 )
		( COND-ASSIGNMENT-0-2 ?STRING0 ?INDEX1 ?CHAR2 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-LOINDEX-2-1
  :PARAMETERS ( ?INPUT0 - INPUT ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( GOTO-0-2-1 )
		( COND-LOINDEX-0-2 ?INPUT0 ?INDEX1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-HIINDEX-2-1
  :PARAMETERS ( ?INPUT0 - INPUT ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( GOTO-0-2-1 )
		( COND-HIINDEX-0-2 ?INPUT0 ?INDEX1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-SIZE-2-1
  :PARAMETERS ( ?STRING0 - STRING ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( GOTO-0-2-1 )
		( COND-SIZE-0-2 ?STRING0 ?INDEX1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-GOTO-EMPTY-2-1
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( GOTO-0-2-1 )
		( COND-EMPTY-0-2 ?INPUT-VARIABLE0 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-END-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-1 )
		( STACK-LINE-1 ?STACKROW0 )
		( TEST-0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( INS-END-1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-END-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-2 )
		( STACK-LINE-2 ?STACKROW0 )
		( TEST-0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( INS-END-2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-END-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( EMPTY-3 )
		( STACK-LINE-3 ?STACKROW0 )
		( TEST-0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-3 ) )
		( INS-END-3 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION PROGRAM-CALL-0-0-0
  :PARAMETERS ( ?STACKROW0 - STACKROW ?INPUT-VARIABLE1 - INPUT-VARIABLE )
  :PRECONDITION
	( AND
		( EMPTY-0 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-0 ) )
		( CALL-0-0-0 ?INPUT-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-CALL-0-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?INPUT-VARIABLE1 - INPUT-VARIABLE )
  :PRECONDITION
	( AND
		( EMPTY-1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-1 ) )
		( CALL-0-0-1 ?INPUT-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION PROGRAM-CALL-0-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW ?INPUT-VARIABLE1 - INPUT-VARIABLE )
  :PRECONDITION
	( AND
		( EMPTY-2 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( EMPTY-2 ) )
		( CALL-0-0-2 ?INPUT-VARIABLE1 )
		( INCREASE ( TOTAL-COST ) 1001 )
	)
)
( :ACTION REPEAT-APPEND-CHAR-0-0
  :PARAMETERS ( ?OUTPUT0 - OUTPUT ?LIMITER1 - LIMITER ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
		( INS-APPEND-CHAR-0 ?OUTPUT0 ?LIMITER1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX3 - INDEX ?INDEX4 - INDEX )
			( WHEN
				( AND
					( SIZE ?OUTPUT0 ?INDEX3 )
					( NEXT ?INDEX3 ?INDEX4 )
				)
				( AND
					( NOT ( SIZE ?OUTPUT0 ?INDEX3 ) )
					( SIZE ?OUTPUT0 ?INDEX4 )
					( ASSIGNMENT ?OUTPUT0 ?INDEX3 ?LIMITER1 )
				)
			)
		)
		( NOT ( STACK-LINE-0 ?STACKROW2 ) )
		( STACK-LINE-1 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-APPEND-CHAR-0-1
  :PARAMETERS ( ?OUTPUT0 - OUTPUT ?LIMITER1 - LIMITER ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
		( INS-APPEND-CHAR-1 ?OUTPUT0 ?LIMITER1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX3 - INDEX ?INDEX4 - INDEX )
			( WHEN
				( AND
					( SIZE ?OUTPUT0 ?INDEX3 )
					( NEXT ?INDEX3 ?INDEX4 )
				)
				( AND
					( NOT ( SIZE ?OUTPUT0 ?INDEX3 ) )
					( SIZE ?OUTPUT0 ?INDEX4 )
					( ASSIGNMENT ?OUTPUT0 ?INDEX3 ?LIMITER1 )
				)
			)
		)
		( NOT ( STACK-LINE-1 ?STACKROW2 ) )
		( STACK-LINE-2 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-APPEND-CHAR-0-2
  :PARAMETERS ( ?OUTPUT0 - OUTPUT ?LIMITER1 - LIMITER ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
		( INS-APPEND-CHAR-2 ?OUTPUT0 ?LIMITER1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX3 - INDEX ?INDEX4 - INDEX )
			( WHEN
				( AND
					( SIZE ?OUTPUT0 ?INDEX3 )
					( NEXT ?INDEX3 ?INDEX4 )
				)
				( AND
					( NOT ( SIZE ?OUTPUT0 ?INDEX3 ) )
					( SIZE ?OUTPUT0 ?INDEX4 )
					( ASSIGNMENT ?OUTPUT0 ?INDEX3 ?LIMITER1 )
				)
			)
		)
		( NOT ( STACK-LINE-2 ?STACKROW2 ) )
		( STACK-LINE-3 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-APPEND-STR-0-0
  :PARAMETERS ( ?OUTPUT0 - OUTPUT ?INPUT-VARIABLE1 - INPUT-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
		( INS-APPEND-STR-0 ?OUTPUT0 ?INPUT-VARIABLE1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX3 - INDEX ?INDEX4 - INDEX ?CHAR5 - CHAR ?INPUT6 - INPUT )
			( WHEN
				( AND
					( SIZE ?OUTPUT0 ?INDEX3 )
					( LOINDEX ?INPUT6 ?INDEX4 )
					( ASSIGNMENT ?INPUT6 ?INDEX4 ?CHAR5 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE1 ?INPUT6 ?STACKROW2 )
				)
				( AND
					( ASSIGNMENT ?OUTPUT0 ?INDEX3 ?CHAR5 )
				)
			)
		)
		( FORALL
			( ?INDEX3 - INDEX ?INDEX4 - INDEX )
			( WHEN
				( AND
					( SIZE ?OUTPUT0 ?INDEX3 )
					( NEXT ?INDEX3 ?INDEX4 )
				)
				( AND
					( NOT ( SIZE ?OUTPUT0 ?INDEX3 ) )
					( SIZE ?OUTPUT0 ?INDEX4 )
				)
			)
		)
		( NOT ( STACK-LINE-0 ?STACKROW2 ) )
		( STACK-LINE-1 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-APPEND-STR-0-1
  :PARAMETERS ( ?OUTPUT0 - OUTPUT ?INPUT-VARIABLE1 - INPUT-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
		( INS-APPEND-STR-1 ?OUTPUT0 ?INPUT-VARIABLE1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX3 - INDEX ?INDEX4 - INDEX ?CHAR5 - CHAR ?INPUT6 - INPUT )
			( WHEN
				( AND
					( SIZE ?OUTPUT0 ?INDEX3 )
					( LOINDEX ?INPUT6 ?INDEX4 )
					( ASSIGNMENT ?INPUT6 ?INDEX4 ?CHAR5 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE1 ?INPUT6 ?STACKROW2 )
				)
				( AND
					( ASSIGNMENT ?OUTPUT0 ?INDEX3 ?CHAR5 )
				)
			)
		)
		( FORALL
			( ?INDEX3 - INDEX ?INDEX4 - INDEX )
			( WHEN
				( AND
					( SIZE ?OUTPUT0 ?INDEX3 )
					( NEXT ?INDEX3 ?INDEX4 )
				)
				( AND
					( NOT ( SIZE ?OUTPUT0 ?INDEX3 ) )
					( SIZE ?OUTPUT0 ?INDEX4 )
				)
			)
		)
		( NOT ( STACK-LINE-1 ?STACKROW2 ) )
		( STACK-LINE-2 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-APPEND-STR-0-2
  :PARAMETERS ( ?OUTPUT0 - OUTPUT ?INPUT-VARIABLE1 - INPUT-VARIABLE ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
		( INS-APPEND-STR-2 ?OUTPUT0 ?INPUT-VARIABLE1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX3 - INDEX ?INDEX4 - INDEX ?CHAR5 - CHAR ?INPUT6 - INPUT )
			( WHEN
				( AND
					( SIZE ?OUTPUT0 ?INDEX3 )
					( LOINDEX ?INPUT6 ?INDEX4 )
					( ASSIGNMENT ?INPUT6 ?INDEX4 ?CHAR5 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE1 ?INPUT6 ?STACKROW2 )
				)
				( AND
					( ASSIGNMENT ?OUTPUT0 ?INDEX3 ?CHAR5 )
				)
			)
		)
		( FORALL
			( ?INDEX3 - INDEX ?INDEX4 - INDEX )
			( WHEN
				( AND
					( SIZE ?OUTPUT0 ?INDEX3 )
					( NEXT ?INDEX3 ?INDEX4 )
				)
				( AND
					( NOT ( SIZE ?OUTPUT0 ?INDEX3 ) )
					( SIZE ?OUTPUT0 ?INDEX4 )
				)
			)
		)
		( NOT ( STACK-LINE-2 ?STACKROW2 ) )
		( STACK-LINE-3 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-INC-LOINDEX-0-0
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( INS-INC-LOINDEX-0 ?INPUT-VARIABLE0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX2 - INDEX ?INDEX3 - INDEX ?INPUT4 - INPUT )
			( WHEN
				( AND
					( LOINDEX ?INPUT4 ?INDEX2 )
					( NEXT ?INDEX2 ?INDEX3 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT4 ?STACKROW1 )
				)
				( AND
					( NOT ( LOINDEX ?INPUT4 ?INDEX2 ) )
					( LOINDEX ?INPUT4 ?INDEX3 )
				)
			)
		)
		( NOT ( STACK-LINE-0 ?STACKROW1 ) )
		( STACK-LINE-1 ?STACKROW1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-INC-LOINDEX-0-1
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
		( INS-INC-LOINDEX-1 ?INPUT-VARIABLE0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX2 - INDEX ?INDEX3 - INDEX ?INPUT4 - INPUT )
			( WHEN
				( AND
					( LOINDEX ?INPUT4 ?INDEX2 )
					( NEXT ?INDEX2 ?INDEX3 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT4 ?STACKROW1 )
				)
				( AND
					( NOT ( LOINDEX ?INPUT4 ?INDEX2 ) )
					( LOINDEX ?INPUT4 ?INDEX3 )
				)
			)
		)
		( NOT ( STACK-LINE-1 ?STACKROW1 ) )
		( STACK-LINE-2 ?STACKROW1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-INC-LOINDEX-0-2
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
		( INS-INC-LOINDEX-2 ?INPUT-VARIABLE0 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX2 - INDEX ?INDEX3 - INDEX ?INPUT4 - INPUT )
			( WHEN
				( AND
					( LOINDEX ?INPUT4 ?INDEX2 )
					( NEXT ?INDEX2 ?INDEX3 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT4 ?STACKROW1 )
				)
				( AND
					( NOT ( LOINDEX ?INPUT4 ?INDEX2 ) )
					( LOINDEX ?INPUT4 ?INDEX3 )
				)
			)
		)
		( NOT ( STACK-LINE-2 ?STACKROW1 ) )
		( STACK-LINE-3 ?STACKROW1 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-GET-PREFIX-0-0
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
		( INS-GET-PREFIX-0 ?INPUT-VARIABLE0 ?LIMITER1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX3 - INDEX ?INPUT4 - INPUT )
			( WHEN
				( AND
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT4 ?STACKROW2 )
				)
				( AND
					( NOT ( LOINDEX ?INPUT4 ?INDEX3 ) )
					( NOT ( HIINDEX ?INPUT4 ?INDEX3 ) )
				)
			)
		)
		( FORALL
			( ?INPUT3 - INPUT )
			( WHEN
				( AND
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT3 ?STACKROW2 )
				)
				( LOINDEX ?INPUT3 I0 )
			)
		)
		( FORALL
			( ?INDEX3 - INDEX ?INPUT4 - INPUT )
			( WHEN
				( AND
					( ASSIGNMENT ?INPUT4 ?INDEX3 ?LIMITER1 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT4 ?STACKROW2 )
				)
				( AND
					( HIINDEX ?INPUT4 ?INDEX3 )
				)
			)
		)
		( NOT ( STACK-LINE-0 ?STACKROW2 ) )
		( STACK-LINE-1 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-GET-PREFIX-0-1
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
		( INS-GET-PREFIX-1 ?INPUT-VARIABLE0 ?LIMITER1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX3 - INDEX ?INPUT4 - INPUT )
			( WHEN
				( AND
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT4 ?STACKROW2 )
				)
				( AND
					( NOT ( LOINDEX ?INPUT4 ?INDEX3 ) )
					( NOT ( HIINDEX ?INPUT4 ?INDEX3 ) )
				)
			)
		)
		( FORALL
			( ?INPUT3 - INPUT )
			( WHEN
				( AND
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT3 ?STACKROW2 )
				)
				( LOINDEX ?INPUT3 I0 )
			)
		)
		( FORALL
			( ?INDEX3 - INDEX ?INPUT4 - INPUT )
			( WHEN
				( AND
					( ASSIGNMENT ?INPUT4 ?INDEX3 ?LIMITER1 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT4 ?STACKROW2 )
				)
				( AND
					( HIINDEX ?INPUT4 ?INDEX3 )
				)
			)
		)
		( NOT ( STACK-LINE-1 ?STACKROW2 ) )
		( STACK-LINE-2 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-GET-PREFIX-0-2
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
		( INS-GET-PREFIX-2 ?INPUT-VARIABLE0 ?LIMITER1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX3 - INDEX ?INPUT4 - INPUT )
			( WHEN
				( AND
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT4 ?STACKROW2 )
				)
				( AND
					( NOT ( LOINDEX ?INPUT4 ?INDEX3 ) )
					( NOT ( HIINDEX ?INPUT4 ?INDEX3 ) )
				)
			)
		)
		( FORALL
			( ?INPUT3 - INPUT )
			( WHEN
				( AND
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT3 ?STACKROW2 )
				)
				( LOINDEX ?INPUT3 I0 )
			)
		)
		( FORALL
			( ?INDEX3 - INDEX ?INPUT4 - INPUT )
			( WHEN
				( AND
					( ASSIGNMENT ?INPUT4 ?INDEX3 ?LIMITER1 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT4 ?STACKROW2 )
				)
				( AND
					( HIINDEX ?INPUT4 ?INDEX3 )
				)
			)
		)
		( NOT ( STACK-LINE-2 ?STACKROW2 ) )
		( STACK-LINE-3 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-GET-SUFFIX-0-0
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
		( INS-GET-SUFFIX-0 ?INPUT-VARIABLE0 ?LIMITER1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX3 - INDEX ?INPUT4 - INPUT )
			( WHEN
				( AND
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT4 ?STACKROW2 )
				)
				( AND
					( NOT ( LOINDEX ?INPUT4 ?INDEX3 ) )
					( NOT ( HIINDEX ?INPUT4 ?INDEX3 ) )
				)
			)
		)
		( FORALL
			( ?INDEX3 - INDEX ?INDEX4 - INDEX ?INPUT5 - INPUT )
			( WHEN
				( AND
					( NEXT ?INDEX3 ?INDEX4 )
					( ASSIGNMENT ?INPUT5 ?INDEX3 ?LIMITER1 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT5 ?STACKROW2 )
				)
				( AND
					( LOINDEX ?INPUT5 ?INDEX4 )
				)
			)
		)
		( FORALL
			( ?INDEX3 - INDEX ?INPUT4 - INPUT )
			( WHEN
				( AND
					( SIZE ?INPUT4 ?INDEX3 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT4 ?STACKROW2 )
				)
				( AND
					( HIINDEX ?INPUT4 ?INDEX3 )
				)
			)
		)
		( NOT ( STACK-LINE-0 ?STACKROW2 ) )
		( STACK-LINE-1 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-GET-SUFFIX-0-1
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
		( INS-GET-SUFFIX-1 ?INPUT-VARIABLE0 ?LIMITER1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX3 - INDEX ?INPUT4 - INPUT )
			( WHEN
				( AND
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT4 ?STACKROW2 )
				)
				( AND
					( NOT ( LOINDEX ?INPUT4 ?INDEX3 ) )
					( NOT ( HIINDEX ?INPUT4 ?INDEX3 ) )
				)
			)
		)
		( FORALL
			( ?INDEX3 - INDEX ?INDEX4 - INDEX ?INPUT5 - INPUT )
			( WHEN
				( AND
					( NEXT ?INDEX3 ?INDEX4 )
					( ASSIGNMENT ?INPUT5 ?INDEX3 ?LIMITER1 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT5 ?STACKROW2 )
				)
				( AND
					( LOINDEX ?INPUT5 ?INDEX4 )
				)
			)
		)
		( FORALL
			( ?INDEX3 - INDEX ?INPUT4 - INPUT )
			( WHEN
				( AND
					( SIZE ?INPUT4 ?INDEX3 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT4 ?STACKROW2 )
				)
				( AND
					( HIINDEX ?INPUT4 ?INDEX3 )
				)
			)
		)
		( NOT ( STACK-LINE-1 ?STACKROW2 ) )
		( STACK-LINE-2 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-GET-SUFFIX-0-2
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
		( INS-GET-SUFFIX-2 ?INPUT-VARIABLE0 ?LIMITER1 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX3 - INDEX ?INPUT4 - INPUT )
			( WHEN
				( AND
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT4 ?STACKROW2 )
				)
				( AND
					( NOT ( LOINDEX ?INPUT4 ?INDEX3 ) )
					( NOT ( HIINDEX ?INPUT4 ?INDEX3 ) )
				)
			)
		)
		( FORALL
			( ?INDEX3 - INDEX ?INDEX4 - INDEX ?INPUT5 - INPUT )
			( WHEN
				( AND
					( NEXT ?INDEX3 ?INDEX4 )
					( ASSIGNMENT ?INPUT5 ?INDEX3 ?LIMITER1 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT5 ?STACKROW2 )
				)
				( AND
					( LOINDEX ?INPUT5 ?INDEX4 )
				)
			)
		)
		( FORALL
			( ?INDEX3 - INDEX ?INPUT4 - INPUT )
			( WHEN
				( AND
					( SIZE ?INPUT4 ?INDEX3 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT4 ?STACKROW2 )
				)
				( AND
					( HIINDEX ?INPUT4 ?INDEX3 )
				)
			)
		)
		( NOT ( STACK-LINE-2 ?STACKROW2 ) )
		( STACK-LINE-3 ?STACKROW2 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-GET-SUBSTR-0-0
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?LIMITER2 - LIMITER ?STACKROW3 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW3 )
		( STACK-MAIN ?STACKROW3 )
		( STACK-LINE-0 ?STACKROW3 )
		( INS-GET-SUBSTR-0 ?INPUT-VARIABLE0 ?LIMITER1 ?LIMITER2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX4 - INDEX ?INPUT5 - INPUT )
			( WHEN
				( AND
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT5 ?STACKROW3 )
				)
				( AND
					( NOT ( LOINDEX ?INPUT5 ?INDEX4 ) )
					( NOT ( HIINDEX ?INPUT5 ?INDEX4 ) )
				)
			)
		)
		( FORALL
			( ?INDEX4 - INDEX ?INDEX5 - INDEX ?INPUT6 - INPUT )
			( WHEN
				( AND
					( NEXT ?INDEX4 ?INDEX5 )
					( ASSIGNMENT ?INPUT6 ?INDEX4 ?LIMITER1 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT6 ?STACKROW3 )
				)
				( AND
					( LOINDEX ?INPUT6 ?INDEX5 )
				)
			)
		)
		( FORALL
			( ?INDEX4 - INDEX ?INPUT5 - INPUT )
			( WHEN
				( AND
					( ASSIGNMENT ?INPUT5 ?INDEX4 ?LIMITER2 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT5 ?STACKROW3 )
				)
				( AND
					( HIINDEX ?INPUT5 ?INDEX4 )
				)
			)
		)
		( NOT ( STACK-LINE-0 ?STACKROW3 ) )
		( STACK-LINE-1 ?STACKROW3 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-GET-SUBSTR-0-1
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?LIMITER2 - LIMITER ?STACKROW3 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW3 )
		( STACK-MAIN ?STACKROW3 )
		( STACK-LINE-1 ?STACKROW3 )
		( INS-GET-SUBSTR-1 ?INPUT-VARIABLE0 ?LIMITER1 ?LIMITER2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX4 - INDEX ?INPUT5 - INPUT )
			( WHEN
				( AND
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT5 ?STACKROW3 )
				)
				( AND
					( NOT ( LOINDEX ?INPUT5 ?INDEX4 ) )
					( NOT ( HIINDEX ?INPUT5 ?INDEX4 ) )
				)
			)
		)
		( FORALL
			( ?INDEX4 - INDEX ?INDEX5 - INDEX ?INPUT6 - INPUT )
			( WHEN
				( AND
					( NEXT ?INDEX4 ?INDEX5 )
					( ASSIGNMENT ?INPUT6 ?INDEX4 ?LIMITER1 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT6 ?STACKROW3 )
				)
				( AND
					( LOINDEX ?INPUT6 ?INDEX5 )
				)
			)
		)
		( FORALL
			( ?INDEX4 - INDEX ?INPUT5 - INPUT )
			( WHEN
				( AND
					( ASSIGNMENT ?INPUT5 ?INDEX4 ?LIMITER2 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT5 ?STACKROW3 )
				)
				( AND
					( HIINDEX ?INPUT5 ?INDEX4 )
				)
			)
		)
		( NOT ( STACK-LINE-1 ?STACKROW3 ) )
		( STACK-LINE-2 ?STACKROW3 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-GET-SUBSTR-0-2
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?LIMITER1 - LIMITER ?LIMITER2 - LIMITER ?STACKROW3 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW3 )
		( STACK-MAIN ?STACKROW3 )
		( STACK-LINE-2 ?STACKROW3 )
		( INS-GET-SUBSTR-2 ?INPUT-VARIABLE0 ?LIMITER1 ?LIMITER2 )
	)
  :EFFECT
	( AND
		( FORALL
			( ?INDEX4 - INDEX ?INPUT5 - INPUT )
			( WHEN
				( AND
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT5 ?STACKROW3 )
				)
				( AND
					( NOT ( LOINDEX ?INPUT5 ?INDEX4 ) )
					( NOT ( HIINDEX ?INPUT5 ?INDEX4 ) )
				)
			)
		)
		( FORALL
			( ?INDEX4 - INDEX ?INDEX5 - INDEX ?INPUT6 - INPUT )
			( WHEN
				( AND
					( NEXT ?INDEX4 ?INDEX5 )
					( ASSIGNMENT ?INPUT6 ?INDEX4 ?LIMITER1 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT6 ?STACKROW3 )
				)
				( AND
					( LOINDEX ?INPUT6 ?INDEX5 )
				)
			)
		)
		( FORALL
			( ?INDEX4 - INDEX ?INPUT5 - INPUT )
			( WHEN
				( AND
					( ASSIGNMENT ?INPUT5 ?INDEX4 ?LIMITER2 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT5 ?STACKROW3 )
				)
				( AND
					( HIINDEX ?INPUT5 ?INDEX4 )
				)
			)
		)
		( NOT ( STACK-LINE-2 ?STACKROW3 ) )
		( STACK-LINE-3 ?STACKROW3 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-GOTO-0-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-0-2 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-GOTO-0-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-0-3 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-GOTO-0-1-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-1-0 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-GOTO-0-1-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-1-3 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-GOTO-0-2-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-2-0 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DO-GOTO-0-2-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-2-1 )
		( DONE-EVALUATING )
		( NOT ( ACCUMULATOR ) )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DONT-GOTO-0-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-0-2 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( NOT ( ACCUMULATOR ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DONT-GOTO-0-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-0-3 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( NOT ( ACCUMULATOR ) )
		( STACK-LINE-1 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DONT-GOTO-0-1-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-1-0 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( NOT ( ACCUMULATOR ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DONT-GOTO-0-1-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-1-3 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( NOT ( ACCUMULATOR ) )
		( STACK-LINE-2 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DONT-GOTO-0-2-0
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-2-0 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( NOT ( ACCUMULATOR ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION DONT-GOTO-0-2-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( GOTO-0-2-1 )
		( DONE-EVALUATING )
		( ACCUMULATOR )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-EVALUATING ) )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( NOT ( ACCUMULATOR ) )
		( STACK-LINE-3 ?STACKROW0 )
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-ASSIGNMENT-0-0
  :PARAMETERS ( ?STRING0 - STRING ?INDEX1 - INDEX ?CHAR2 - CHAR ?STACKROW3 - STACKROW )
  :PRECONDITION
	( AND
		( COND-ASSIGNMENT-0-0 ?STRING0 ?INDEX1 ?CHAR2 )
		( TOP-STACK ?STACKROW3 )
		( STACK-MAIN ?STACKROW3 )
		( STACK-LINE-0 ?STACKROW3 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( ASSIGNMENT ?STRING0 ?INDEX1 ?CHAR2 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-ASSIGNMENT-0-1
  :PARAMETERS ( ?STRING0 - STRING ?INDEX1 - INDEX ?CHAR2 - CHAR ?STACKROW3 - STACKROW )
  :PRECONDITION
	( AND
		( COND-ASSIGNMENT-0-1 ?STRING0 ?INDEX1 ?CHAR2 )
		( TOP-STACK ?STACKROW3 )
		( STACK-MAIN ?STACKROW3 )
		( STACK-LINE-1 ?STACKROW3 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( ASSIGNMENT ?STRING0 ?INDEX1 ?CHAR2 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-ASSIGNMENT-0-2
  :PARAMETERS ( ?STRING0 - STRING ?INDEX1 - INDEX ?CHAR2 - CHAR ?STACKROW3 - STACKROW )
  :PRECONDITION
	( AND
		( COND-ASSIGNMENT-0-2 ?STRING0 ?INDEX1 ?CHAR2 )
		( TOP-STACK ?STACKROW3 )
		( STACK-MAIN ?STACKROW3 )
		( STACK-LINE-2 ?STACKROW3 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( ASSIGNMENT ?STRING0 ?INDEX1 ?CHAR2 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-LOINDEX-0-0
  :PARAMETERS ( ?INPUT0 - INPUT ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( COND-LOINDEX-0-0 ?INPUT0 ?INDEX1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( LOINDEX ?INPUT0 ?INDEX1 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-LOINDEX-0-1
  :PARAMETERS ( ?INPUT0 - INPUT ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( COND-LOINDEX-0-1 ?INPUT0 ?INDEX1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( LOINDEX ?INPUT0 ?INDEX1 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-LOINDEX-0-2
  :PARAMETERS ( ?INPUT0 - INPUT ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( COND-LOINDEX-0-2 ?INPUT0 ?INDEX1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( LOINDEX ?INPUT0 ?INDEX1 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-HIINDEX-0-0
  :PARAMETERS ( ?INPUT0 - INPUT ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( COND-HIINDEX-0-0 ?INPUT0 ?INDEX1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( HIINDEX ?INPUT0 ?INDEX1 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-HIINDEX-0-1
  :PARAMETERS ( ?INPUT0 - INPUT ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( COND-HIINDEX-0-1 ?INPUT0 ?INDEX1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( HIINDEX ?INPUT0 ?INDEX1 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-HIINDEX-0-2
  :PARAMETERS ( ?INPUT0 - INPUT ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( COND-HIINDEX-0-2 ?INPUT0 ?INDEX1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( HIINDEX ?INPUT0 ?INDEX1 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-SIZE-0-0
  :PARAMETERS ( ?STRING0 - STRING ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( COND-SIZE-0-0 ?STRING0 ?INDEX1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-0 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( SIZE ?STRING0 ?INDEX1 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-SIZE-0-1
  :PARAMETERS ( ?STRING0 - STRING ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( COND-SIZE-0-1 ?STRING0 ?INDEX1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-1 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( SIZE ?STRING0 ?INDEX1 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-SIZE-0-2
  :PARAMETERS ( ?STRING0 - STRING ?INDEX1 - INDEX ?STACKROW2 - STACKROW )
  :PRECONDITION
	( AND
		( COND-SIZE-0-2 ?STRING0 ?INDEX1 )
		( TOP-STACK ?STACKROW2 )
		( STACK-MAIN ?STACKROW2 )
		( STACK-LINE-2 ?STACKROW2 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( WHEN
			( SIZE ?STRING0 ?INDEX1 )
			( AND
				( ACCUMULATOR )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-EMPTY-0-0
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( COND-EMPTY-0-0 ?INPUT-VARIABLE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( NOT ( EMPTY ?INPUT-VARIABLE0 ) )
		( FORALL
			( ?INDEX2 - INDEX ?INPUT3 - INPUT )
			( WHEN
				( AND
					( LOINDEX ?INPUT3 ?INDEX2 )
					( HIINDEX ?INPUT3 ?INDEX2 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT3 ?STACKROW1 )
				)
				( AND
					( ACCUMULATOR )
					( EMPTY ?INPUT-VARIABLE0 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-EMPTY-0-1
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( COND-EMPTY-0-1 ?INPUT-VARIABLE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( NOT ( EMPTY ?INPUT-VARIABLE0 ) )
		( FORALL
			( ?INDEX2 - INDEX ?INPUT3 - INPUT )
			( WHEN
				( AND
					( LOINDEX ?INPUT3 ?INDEX2 )
					( HIINDEX ?INPUT3 ?INDEX2 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT3 ?STACKROW1 )
				)
				( AND
					( ACCUMULATOR )
					( EMPTY ?INPUT-VARIABLE0 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION EVAL-COND-EMPTY-0-2
  :PARAMETERS ( ?INPUT-VARIABLE0 - INPUT-VARIABLE ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( COND-EMPTY-0-2 ?INPUT-VARIABLE0 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( DONE-EVALUATING )
		( NOT ( EMPTY ?INPUT-VARIABLE0 ) )
		( FORALL
			( ?INDEX2 - INDEX ?INPUT3 - INPUT )
			( WHEN
				( AND
					( LOINDEX ?INPUT3 ?INDEX2 )
					( HIINDEX ?INPUT3 ?INDEX2 )
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE0 ?INPUT3 ?STACKROW1 )
				)
				( AND
					( ACCUMULATOR )
					( EMPTY ?INPUT-VARIABLE0 )
				)
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-MAIN-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-1 ROW-0 )
		( INS-END-1 )
		( TEST-0 )
		( ASSIGNMENT RES I0 B )
		( ASSIGNMENT RES I1 SPACE )
		( ASSIGNMENT RES I2 L )
		( SIZE RES I3 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-0 ) )
		( TEST-1 )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( HIINDEX STR I6 )
		( LOINDEX STR I0 )
		( HIINDEX STR2 I5 )
		( LOINDEX STR2 I0 )
		( SIZE STR I6 )
		( SIZE STR2 I5 )
		( SIZE RES I0 )
		( INPUT-ASSIGNMENT STR-VAR STR ROW-0 )
		( INPUT-ASSIGNMENT STR2-VAR STR2 ROW-0 )
		( NEXT I0 I1 )
		( NEXT I1 I2 )
		( NEXT I2 I3 )
		( NEXT I3 I4 )
		( NEXT I4 I5 )
		( NEXT I5 I6 )
		( NEXT I6 I7 )
		( NEXT I7 I8 )
		( NEXT I8 I9 )
		( NEXT I9 I10 )
		( NEXT I10 I11 )
		( NEXT I11 I12 )
		( ASSIGNMENT STR I0 C )
		( ASSIGNMENT STR I1 O )
		( ASSIGNMENT STR I2 A )
		( ASSIGNMENT STR I3 H )
		( ASSIGNMENT STR I4 F )
		( ASSIGNMENT STR I5 U )
		( ASSIGNMENT STR2 I0 T )
		( ASSIGNMENT STR2 I1 H )
		( ASSIGNMENT STR2 I2 O )
		( ASSIGNMENT STR2 I3 A )
		( ASSIGNMENT STR2 I4 D )
		( FORALL
			( ?STRING1 - STRING ?INDEX2 - INDEX ?CHAR3 - CHAR )
			( WHEN
				( AND
					( ASSIGNMENT ?STRING1 ?INDEX2 ?CHAR3 )
				)
				( NOT ( ASSIGNMENT ?STRING1 ?INDEX2 ?CHAR3 ) )
			)
		)
		( FORALL
			( ?INPUT1 - INPUT ?INDEX2 - INDEX )
			( WHEN
				( AND
					( LOINDEX ?INPUT1 ?INDEX2 )
				)
				( NOT ( LOINDEX ?INPUT1 ?INDEX2 ) )
			)
		)
		( FORALL
			( ?INPUT1 - INPUT ?INDEX2 - INDEX )
			( WHEN
				( AND
					( HIINDEX ?INPUT1 ?INDEX2 )
				)
				( NOT ( HIINDEX ?INPUT1 ?INDEX2 ) )
			)
		)
		( FORALL
			( ?STRING1 - STRING ?INDEX2 - INDEX )
			( WHEN
				( AND
					( SIZE ?STRING1 ?INDEX2 )
				)
				( NOT ( SIZE ?STRING1 ?INDEX2 ) )
			)
		)
		( FORALL
			( ?INPUT-VARIABLE1 - INPUT-VARIABLE )
			( WHEN
				( AND
					( EMPTY ?INPUT-VARIABLE1 )
				)
				( NOT ( EMPTY ?INPUT-VARIABLE1 ) )
			)
		)
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX )
			( WHEN
				( AND
					( NEXT ?INDEX1 ?INDEX2 )
				)
				( NOT ( NEXT ?INDEX1 ?INDEX2 ) )
			)
		)
		( FORALL
			( ?INPUT-VARIABLE1 - INPUT-VARIABLE ?INPUT2 - INPUT ?STACKROW3 - STACKROW )
			( WHEN
				( AND
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE1 ?INPUT2 ?STACKROW3 )
				)
				( NOT ( INPUT-ASSIGNMENT ?INPUT-VARIABLE1 ?INPUT2 ?STACKROW3 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-2 ROW-0 )
		( INS-END-2 )
		( TEST-0 )
		( ASSIGNMENT RES I0 B )
		( ASSIGNMENT RES I1 SPACE )
		( ASSIGNMENT RES I2 L )
		( SIZE RES I3 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-0 ) )
		( TEST-1 )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( HIINDEX STR I6 )
		( LOINDEX STR I0 )
		( HIINDEX STR2 I5 )
		( LOINDEX STR2 I0 )
		( SIZE STR I6 )
		( SIZE STR2 I5 )
		( SIZE RES I0 )
		( INPUT-ASSIGNMENT STR-VAR STR ROW-0 )
		( INPUT-ASSIGNMENT STR2-VAR STR2 ROW-0 )
		( NEXT I0 I1 )
		( NEXT I1 I2 )
		( NEXT I2 I3 )
		( NEXT I3 I4 )
		( NEXT I4 I5 )
		( NEXT I5 I6 )
		( NEXT I6 I7 )
		( NEXT I7 I8 )
		( NEXT I8 I9 )
		( NEXT I9 I10 )
		( NEXT I10 I11 )
		( NEXT I11 I12 )
		( ASSIGNMENT STR I0 C )
		( ASSIGNMENT STR I1 O )
		( ASSIGNMENT STR I2 A )
		( ASSIGNMENT STR I3 H )
		( ASSIGNMENT STR I4 F )
		( ASSIGNMENT STR I5 U )
		( ASSIGNMENT STR2 I0 T )
		( ASSIGNMENT STR2 I1 H )
		( ASSIGNMENT STR2 I2 O )
		( ASSIGNMENT STR2 I3 A )
		( ASSIGNMENT STR2 I4 D )
		( FORALL
			( ?STRING1 - STRING ?INDEX2 - INDEX ?CHAR3 - CHAR )
			( WHEN
				( AND
					( ASSIGNMENT ?STRING1 ?INDEX2 ?CHAR3 )
				)
				( NOT ( ASSIGNMENT ?STRING1 ?INDEX2 ?CHAR3 ) )
			)
		)
		( FORALL
			( ?INPUT1 - INPUT ?INDEX2 - INDEX )
			( WHEN
				( AND
					( LOINDEX ?INPUT1 ?INDEX2 )
				)
				( NOT ( LOINDEX ?INPUT1 ?INDEX2 ) )
			)
		)
		( FORALL
			( ?INPUT1 - INPUT ?INDEX2 - INDEX )
			( WHEN
				( AND
					( HIINDEX ?INPUT1 ?INDEX2 )
				)
				( NOT ( HIINDEX ?INPUT1 ?INDEX2 ) )
			)
		)
		( FORALL
			( ?STRING1 - STRING ?INDEX2 - INDEX )
			( WHEN
				( AND
					( SIZE ?STRING1 ?INDEX2 )
				)
				( NOT ( SIZE ?STRING1 ?INDEX2 ) )
			)
		)
		( FORALL
			( ?INPUT-VARIABLE1 - INPUT-VARIABLE )
			( WHEN
				( AND
					( EMPTY ?INPUT-VARIABLE1 )
				)
				( NOT ( EMPTY ?INPUT-VARIABLE1 ) )
			)
		)
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX )
			( WHEN
				( AND
					( NEXT ?INDEX1 ?INDEX2 )
				)
				( NOT ( NEXT ?INDEX1 ?INDEX2 ) )
			)
		)
		( FORALL
			( ?INPUT-VARIABLE1 - INPUT-VARIABLE ?INPUT2 - INPUT ?STACKROW3 - STACKROW )
			( WHEN
				( AND
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE1 ?INPUT2 ?STACKROW3 )
				)
				( NOT ( INPUT-ASSIGNMENT ?INPUT-VARIABLE1 ?INPUT2 ?STACKROW3 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-3 ROW-0 )
		( INS-END-3 )
		( TEST-0 )
		( ASSIGNMENT RES I0 B )
		( ASSIGNMENT RES I1 SPACE )
		( ASSIGNMENT RES I2 L )
		( SIZE RES I3 )
	)
  :EFFECT
	( AND
		( NOT ( TEST-0 ) )
		( TEST-1 )
		( NOT ( STACK-LINE-3 ?STACKROW0 ) )
		( STACK-LINE-0 ?STACKROW0 )
		( HIINDEX STR I6 )
		( LOINDEX STR I0 )
		( HIINDEX STR2 I5 )
		( LOINDEX STR2 I0 )
		( SIZE STR I6 )
		( SIZE STR2 I5 )
		( SIZE RES I0 )
		( INPUT-ASSIGNMENT STR-VAR STR ROW-0 )
		( INPUT-ASSIGNMENT STR2-VAR STR2 ROW-0 )
		( NEXT I0 I1 )
		( NEXT I1 I2 )
		( NEXT I2 I3 )
		( NEXT I3 I4 )
		( NEXT I4 I5 )
		( NEXT I5 I6 )
		( NEXT I6 I7 )
		( NEXT I7 I8 )
		( NEXT I8 I9 )
		( NEXT I9 I10 )
		( NEXT I10 I11 )
		( NEXT I11 I12 )
		( ASSIGNMENT STR I0 C )
		( ASSIGNMENT STR I1 O )
		( ASSIGNMENT STR I2 A )
		( ASSIGNMENT STR I3 H )
		( ASSIGNMENT STR I4 F )
		( ASSIGNMENT STR I5 U )
		( ASSIGNMENT STR2 I0 T )
		( ASSIGNMENT STR2 I1 H )
		( ASSIGNMENT STR2 I2 O )
		( ASSIGNMENT STR2 I3 A )
		( ASSIGNMENT STR2 I4 D )
		( FORALL
			( ?STRING1 - STRING ?INDEX2 - INDEX ?CHAR3 - CHAR )
			( WHEN
				( AND
					( ASSIGNMENT ?STRING1 ?INDEX2 ?CHAR3 )
				)
				( NOT ( ASSIGNMENT ?STRING1 ?INDEX2 ?CHAR3 ) )
			)
		)
		( FORALL
			( ?INPUT1 - INPUT ?INDEX2 - INDEX )
			( WHEN
				( AND
					( LOINDEX ?INPUT1 ?INDEX2 )
				)
				( NOT ( LOINDEX ?INPUT1 ?INDEX2 ) )
			)
		)
		( FORALL
			( ?INPUT1 - INPUT ?INDEX2 - INDEX )
			( WHEN
				( AND
					( HIINDEX ?INPUT1 ?INDEX2 )
				)
				( NOT ( HIINDEX ?INPUT1 ?INDEX2 ) )
			)
		)
		( FORALL
			( ?STRING1 - STRING ?INDEX2 - INDEX )
			( WHEN
				( AND
					( SIZE ?STRING1 ?INDEX2 )
				)
				( NOT ( SIZE ?STRING1 ?INDEX2 ) )
			)
		)
		( FORALL
			( ?INPUT-VARIABLE1 - INPUT-VARIABLE )
			( WHEN
				( AND
					( EMPTY ?INPUT-VARIABLE1 )
				)
				( NOT ( EMPTY ?INPUT-VARIABLE1 ) )
			)
		)
		( FORALL
			( ?INDEX1 - INDEX ?INDEX2 - INDEX )
			( WHEN
				( AND
					( NEXT ?INDEX1 ?INDEX2 )
				)
				( NOT ( NEXT ?INDEX1 ?INDEX2 ) )
			)
		)
		( FORALL
			( ?INPUT-VARIABLE1 - INPUT-VARIABLE ?INPUT2 - INPUT ?STACKROW3 - STACKROW )
			( WHEN
				( AND
					( INPUT-ASSIGNMENT ?INPUT-VARIABLE1 ?INPUT2 ?STACKROW3 )
				)
				( NOT ( INPUT-ASSIGNMENT ?INPUT-VARIABLE1 ?INPUT2 ?STACKROW3 ) )
			)
		)
	)
)
( :ACTION REPEAT-END-MAIN-1-1
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-1 ROW-0 )
		( INS-END-1 )
		( TEST-1 )
		( ASSIGNMENT RES I0 C )
		( ASSIGNMENT RES I1 SPACE )
		( ASSIGNMENT RES I2 T )
		( SIZE RES I3 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
	)
)
( :ACTION REPEAT-END-MAIN-1-2
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-2 ROW-0 )
		( INS-END-2 )
		( TEST-1 )
		( ASSIGNMENT RES I0 C )
		( ASSIGNMENT RES I1 SPACE )
		( ASSIGNMENT RES I2 T )
		( SIZE RES I3 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
	)
)
( :ACTION REPEAT-END-MAIN-1-3
  :PARAMETERS ( ?STACKROW0 - STACKROW )
  :PRECONDITION
	( AND
		( TOP-STACK ?STACKROW0 )
		( TOP-STACK ROW-0 )
		( STACK-MAIN ROW-0 )
		( STACK-LINE-3 ROW-0 )
		( INS-END-3 )
		( TEST-1 )
		( ASSIGNMENT RES I0 C )
		( ASSIGNMENT RES I1 SPACE )
		( ASSIGNMENT RES I2 T )
		( SIZE RES I3 )
	)
  :EFFECT
	( AND
		( DONE-PROGRAMMING )
	)
)
( :ACTION REPEAT-END-0-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-1 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-1 ?STACKROW1 ) )
		( FORALL
			( ?INPUT-VARIABLE2 - INPUT-VARIABLE ?INPUT3 - INPUT )
			( AND
				( NOT ( INPUT-ASSIGNMENT ?INPUT-VARIABLE2 ?INPUT3 ?STACKROW1 ) )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-2 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-2 ?STACKROW1 ) )
		( FORALL
			( ?INPUT-VARIABLE2 - INPUT-VARIABLE ?INPUT3 - INPUT )
			( AND
				( NOT ( INPUT-ASSIGNMENT ?INPUT-VARIABLE2 ?INPUT3 ?STACKROW1 ) )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-0-3
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-3 )
		( TEST-0 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-3 ?STACKROW1 ) )
		( FORALL
			( ?INPUT-VARIABLE2 - INPUT-VARIABLE ?INPUT3 - INPUT )
			( AND
				( NOT ( INPUT-ASSIGNMENT ?INPUT-VARIABLE2 ?INPUT3 ?STACKROW1 ) )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-1-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-1 )
		( TEST-1 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-1 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-1 ?STACKROW1 ) )
		( FORALL
			( ?INPUT-VARIABLE2 - INPUT-VARIABLE ?INPUT3 - INPUT )
			( AND
				( NOT ( INPUT-ASSIGNMENT ?INPUT-VARIABLE2 ?INPUT3 ?STACKROW1 ) )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-1-2
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-2 )
		( TEST-1 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-2 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-2 ?STACKROW1 ) )
		( FORALL
			( ?INPUT-VARIABLE2 - INPUT-VARIABLE ?INPUT3 - INPUT )
			( AND
				( NOT ( INPUT-ASSIGNMENT ?INPUT-VARIABLE2 ?INPUT3 ?STACKROW1 ) )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-END-0-1-3
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW )
  :PRECONDITION
	( AND
		( INS-END-3 )
		( TEST-1 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-3 ?STACKROW1 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW1 ) )
		( TOP-STACK ?STACKROW0 )
		( NOT ( STACK-MAIN ?STACKROW1 ) )
		( NOT ( STACK-LINE-3 ?STACKROW1 ) )
		( FORALL
			( ?INPUT-VARIABLE2 - INPUT-VARIABLE ?INPUT3 - INPUT )
			( AND
				( NOT ( INPUT-ASSIGNMENT ?INPUT-VARIABLE2 ?INPUT3 ?STACKROW1 ) )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-CALL-0-0-0
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW ?INPUT-VARIABLE2 - INPUT-VARIABLE )
  :PRECONDITION
	( AND
		( CALL-0-0-0 ?INPUT-VARIABLE2 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-0 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-0 ?STACKROW0 ) )
		( STACK-LINE-1 ?STACKROW0 )
		( FORALL
			( ?INPUT3 - INPUT )
			( WHEN
				( INPUT-ASSIGNMENT ?INPUT-VARIABLE2 ?INPUT3 ?STACKROW0 )
				( INPUT-ASSIGNMENT STR-VAR ?INPUT3 ?STACKROW1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-CALL-0-0-1
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW ?INPUT-VARIABLE2 - INPUT-VARIABLE )
  :PRECONDITION
	( AND
		( CALL-0-0-1 ?INPUT-VARIABLE2 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-1 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-1 ?STACKROW0 ) )
		( STACK-LINE-2 ?STACKROW0 )
		( FORALL
			( ?INPUT3 - INPUT )
			( WHEN
				( INPUT-ASSIGNMENT ?INPUT-VARIABLE2 ?INPUT3 ?STACKROW0 )
				( INPUT-ASSIGNMENT STR-VAR ?INPUT3 ?STACKROW1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION REPEAT-CALL-0-0-2
  :PARAMETERS ( ?STACKROW0 - STACKROW ?STACKROW1 - STACKROW ?INPUT-VARIABLE2 - INPUT-VARIABLE )
  :PRECONDITION
	( AND
		( CALL-0-0-2 ?INPUT-VARIABLE2 )
		( NEXT-STACK-ROW ?STACKROW0 ?STACKROW1 )
		( TOP-STACK ?STACKROW0 )
		( STACK-MAIN ?STACKROW0 )
		( STACK-LINE-2 ?STACKROW0 )
	)
  :EFFECT
	( AND
		( NOT ( TOP-STACK ?STACKROW0 ) )
		( TOP-STACK ?STACKROW1 )
		( STACK-MAIN ?STACKROW1 )
		( STACK-LINE-0 ?STACKROW1 )
		( NOT ( STACK-LINE-2 ?STACKROW0 ) )
		( STACK-LINE-3 ?STACKROW0 )
		( FORALL
			( ?INPUT3 - INPUT )
			( WHEN
				( INPUT-ASSIGNMENT ?INPUT-VARIABLE2 ?INPUT3 ?STACKROW0 )
				( INPUT-ASSIGNMENT STR-VAR ?INPUT3 ?STACKROW1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
)
