(define (problem freecell-f2-c3-s4-i1-03-13-23-33
)(:domain freecell)
(:objects 
          C0 CA C2 C3
          H0 HA H2 H3
          S0 SA S2 S3
          D0 DA D2 D3
 - card
          CELLN0 CELLN1 CELLN2 
 - cellnum
          COLN0 COLN1 COLN2 COLN3 
 - colnum
          N0 N1 N2 N3 
 - num
           C H S D
 - suit
)
(:init
(VALUE C0 N0)
(VALUE CA N1)
(VALUE C2 N2)
(VALUE C3 N3)
(VALUE H0 N0)
(VALUE HA N1)
(VALUE H2 N2)
(VALUE H3 N3)
(VALUE S0 N0)
(VALUE SA N1)
(VALUE S2 N2)
(VALUE S3 N3)
(VALUE D0 N0)
(VALUE DA N1)
(VALUE D2 N2)
(VALUE D3 N3)
(CELLSUCCESSOR CELLN1 CELLN0)
(CELLSUCCESSOR CELLN2 CELLN1)
(COLSUCCESSOR COLN1 COLN0)
(COLSUCCESSOR COLN2 COLN1)
(COLSUCCESSOR COLN3 COLN2)
(SUCCESSOR N1 N0)
(SUCCESSOR N2 N1)
(SUCCESSOR N3 N2)
(HASSUIT C0 C)
(HASSUIT CA C)
(HASSUIT C2 C)
(HASSUIT C3 C)
(HASSUIT H0 H)
(HASSUIT HA H)
(HASSUIT H2 H)
(HASSUIT H3 H)
(HASSUIT S0 S)
(HASSUIT SA S)
(HASSUIT S2 S)
(HASSUIT S3 S)
(HASSUIT D0 D)
(HASSUIT DA D)
(HASSUIT D2 D)
(HASSUIT D3 D)
(CANSTACK C2 H3)
(CANSTACK C2 D3)
(CANSTACK H2 C3)
(CANSTACK H2 S3)
(CANSTACK S2 H3)
(CANSTACK S2 D3)
(CANSTACK D2 C3)
(CANSTACK D2 S3)
(HOME C0)
(HOME H0)
(HOME S0)
(HOME D0)
(CELLSPACE CELLN2)
(COLSPACE COLN2)

(BOTTOMCOL D2)
(ON D3 D2)
(ON SA D3)
(ON H3 SA)
(ON S2 H3)
(ON S3 S2)
(ON DA S3)
(ON HA DA)
(ON H2 HA)
(ON C2 H2)
(ON C3 C2)
(ON CA C3)
(CLEAR CA)
)
(:goal
(and
(HOME C3)
(HOME H3)
(HOME S3)
(HOME D3)
)
)
)
