(define (problem freecell-f3-c7-s4-i6-03-13-23-33
)(:domain freecell)
(:objects 
          C0 CA C2 C3
          H0 HA H2 H3
          S0 SA S2 S3
          D0 DA D2 D3
 - card
          CELLN0 CELLN1 CELLN2 CELLN3 
 - cellnum
          COLN0 COLN1 COLN2 COLN3 COLN4 COLN5 COLN6 COLN7 
 - colnum
          N0 N1 N2 N3 
 - num
           C H S D
 - suit
)
(:init
(VALUE C0 N0)
(VALUE CA N1)
(VALUE C2 N2)
(VALUE C3 N3)
(VALUE H0 N0)
(VALUE HA N1)
(VALUE H2 N2)
(VALUE H3 N3)
(VALUE S0 N0)
(VALUE SA N1)
(VALUE S2 N2)
(VALUE S3 N3)
(VALUE D0 N0)
(VALUE DA N1)
(VALUE D2 N2)
(VALUE D3 N3)
(CELLSUCCESSOR CELLN1 CELLN0)
(CELLSUCCESSOR CELLN2 CELLN1)
(CELLSUCCESSOR CELLN3 CELLN2)
(COLSUCCESSOR COLN1 COLN0)
(COLSUCCESSOR COLN2 COLN1)
(COLSUCCESSOR COLN3 COLN2)
(COLSUCCESSOR COLN4 COLN3)
(COLSUCCESSOR COLN5 COLN4)
(COLSUCCESSOR COLN6 COLN5)
(COLSUCCESSOR COLN7 COLN6)
(SUCCESSOR N1 N0)
(SUCCESSOR N2 N1)
(SUCCESSOR N3 N2)
(SUIT C0 C)
(SUIT CA C)
(SUIT C2 C)
(SUIT C3 C)
(SUIT H0 H)
(SUIT HA H)
(SUIT H2 H)
(SUIT H3 H)
(SUIT S0 S)
(SUIT SA S)
(SUIT S2 S)
(SUIT S3 S)
(SUIT D0 D)
(SUIT DA D)
(SUIT D2 D)
(SUIT D3 D)
(CANSTACK C2 H3)
(CANSTACK C2 D3)
(CANSTACK H2 C3)
(CANSTACK H2 S3)
(CANSTACK S2 H3)
(CANSTACK S2 D3)
(CANSTACK D2 C3)
(CANSTACK D2 S3)
(HOME C0)
(HOME H0)
(HOME S0)
(HOME D0)
(CELLSPACE CELLN3)
(COLSPACE COLN1)

(BOTTOMCOL HA)
(ON C3 HA)
(CLEAR C3)

(BOTTOMCOL D3)
(ON H3 D3)
(CLEAR H3)

(BOTTOMCOL S3)
(ON DA S3)
(ON C2 DA)
(ON CA C2)
(CLEAR CA)

(BOTTOMCOL D2)
(ON SA D2)
(CLEAR SA)

(BOTTOMCOL H2)
(CLEAR H2)

(BOTTOMCOL S2)
(CLEAR S2)
)
(:goal
(and
(HOME C3)
(HOME H3)
(HOME S3)
(HOME D3)
)
)
)
