(define (problem freecell-f3-c6-s4-i5-02-12-22-32
)(:domain freecell)
(:objects 
          C0 CA C2
          H0 HA H2
          S0 SA S2
          D0 DA D2
 - card
          CELLN0 CELLN1 CELLN2 CELLN3 
 - cellnum
          COLN0 COLN1 COLN2 COLN3 COLN4 COLN5 COLN6 
 - colnum
          N0 N1 N2 
 - num
           C H S D
 - suit
)
(:init
(VALUE C0 N0)
(VALUE CA N1)
(VALUE C2 N2)
(VALUE H0 N0)
(VALUE HA N1)
(VALUE H2 N2)
(VALUE S0 N0)
(VALUE SA N1)
(VALUE S2 N2)
(VALUE D0 N0)
(VALUE DA N1)
(VALUE D2 N2)
(CELLSUCCESSOR CELLN1 CELLN0)
(CELLSUCCESSOR CELLN2 CELLN1)
(CELLSUCCESSOR CELLN3 CELLN2)
(COLSUCCESSOR COLN1 COLN0)
(COLSUCCESSOR COLN2 COLN1)
(COLSUCCESSOR COLN3 COLN2)
(COLSUCCESSOR COLN4 COLN3)
(COLSUCCESSOR COLN5 COLN4)
(COLSUCCESSOR COLN6 COLN5)
(SUCCESSOR N1 N0)
(SUCCESSOR N2 N1)
(HASSUIT C0 C)
(HASSUIT CA C)
(HASSUIT C2 C)
(HASSUIT H0 H)
(HASSUIT HA H)
(HASSUIT H2 H)
(HASSUIT S0 S)
(HASSUIT SA S)
(HASSUIT S2 S)
(HASSUIT D0 D)
(HASSUIT DA D)
(HASSUIT D2 D)
(HOME C0)
(HOME H0)
(HOME S0)
(HOME D0)
(CELLSPACE CELLN3)
(COLSPACE COLN1)

(BOTTOMCOL D2)
(CLEAR D2)

(BOTTOMCOL DA)
(ON HA DA)
(ON CA HA)
(ON H2 CA)
(CLEAR H2)

(BOTTOMCOL S2)
(ON C2 S2)
(CLEAR C2)

(BOTTOMCOL SA)
(CLEAR SA)
)
(:goal
(and
(HOME C2)
(HOME H2)
(HOME S2)
(HOME D2)
)
)
)
