#! /usr/bin/env python3

from collections import defaultdict
import itertools

from lab.reports import Report, Table


DOMAIN_GROUPS = {
    "airport": ["airport"],
    "assembly": ["assembly"],
    "barman": ["barman", "barman-opt11-strips", "barman-opt14-strips"],
    "blocks": ["blocks", "blocksworld"],
    "cavediving": ["cavediving-14-adl"],
    "childsnack": ["childsnack-opt14-strips"],
    "citycar": ["citycar-opt14-adl"],
    "depot": ["depot", "depots"],
    "driverlog": ["driverlog"],
    "elevators": ["elevators-opt08-strips", "elevators-opt11-strips"],
    "floortile": ["floortile-opt11-strips", "floortile-opt14-strips"],
    "freecell": ["freecell"],
    "ged": ["ged-opt14-strips"],
    "grid": ["grid"],
    "gripper": ["gripper"],
    "hiking": ["hiking-opt14-strips"],
    "logistics": ["logistics98", "logistics00"],
    "maintenance": ["maintenance-opt14-adl"],
    "miconic-strips": ["miconic", "miconic-strips"],
    "miconic-fulladl": ["miconic-fulladl"],
    "miconic-simpleadl": ["miconic-simpleadl"],
    "movie": ["movie"],
    "mprime": ["mprime"],
    "mystery": ["mystery"],
    "nomystery": ["nomystery-opt11-strips"],
    "openstacks": ["openstacks", "openstacks-strips", "openstacks-opt08-strips", "openstacks-opt11-strips", "openstacks-opt14-strips", "openstacks-opt08-adl"],
    "optical-telegraphs": ["optical-telegraphs"],
    "parcprinter": ["parcprinter-08-strips", "parcprinter-opt11-strips"],
    "parking": ["parking-opt11-strips", "parking-opt14-strips"],
    "pathways": ["pathways", "pathways-noneg"],
    "pegsol": ["pegsol-08-strips", "pegsol-opt11-strips"],
    "philosophers": ["philosophers"],
    "pipes-nt": ["pipesworld-notankage"],
    "pipes-t": ["pipesworld-tankage"],
    "psr": ["psr-middle", "psr-large", "psr-small"],
    "rovers": ["rover", "rovers"],
    "satellite": ["satellite"],
    "scanalyzer": ["scanalyzer-08-strips", "scanalyzer-opt11-strips"],
    "schedule": ["schedule"],
    "sokoban": ["sokoban-opt08-strips", "sokoban-opt11-strips"],
    "storage": ["storage"],
    "tetris": ["tetris-opt14-strips"],
    "tidybot": ["tidybot-opt11-strips", "tidybot-opt14-strips"],
    "tpp": ["tpp"],
    "transport": ["transport-opt08-strips", "transport-opt11-strips", "transport-opt14-strips"],
    "trucks": ["trucks", "trucks-strips"],
    "visitall": ["visitall-opt11-strips", "visitall-opt14-strips"],
    "woodworking": ["woodworking-opt08-strips", "woodworking-opt11-strips"],
    "zenotravel": ["zenotravel"],
    # IPC 2018:
    "agricola": ["agricola", "agricola-opt18-strips"],
    "caldera": ["caldera-opt18-adl", "caldera-split-opt18-adl"],
    "data-network": ["data-network", "data-network-opt18-strips"],
    "nurikabe": ["nurikabe-opt18-adl"],
    "organic-split": ["organic-synthesis-split", "organic-synthesis-split-opt18-strips"],
    "organic" : ["organic-synthesis", "organic-synthesis-opt18-strips"],
    "petri-net": ["petri-net-alignment", "petri-net-alignment-opt18-strips"],
    "settlers": ["settlers-opt18-adl"],
    "snake": ["snake", "snake-opt18-strips"],
    "spider": ["spider", "spider-opt18-strips"],
    "termes": ["termes", "termes-opt18-strips"],
}

DOMAIN_RENAMINGS = {}
for group_name, domains in DOMAIN_GROUPS.items():
    for domain in domains:
        DOMAIN_RENAMINGS[domain] = group_name
for group_name in DOMAIN_GROUPS:
    DOMAIN_RENAMINGS[group_name] = group_name


def group_domains(run):
    old_domain = run["domain"]
    run["domain"] = DOMAIN_RENAMINGS[old_domain]
    run["problem"] = old_domain + "-" + run["problem"]
    return run

OLD = [
("barman", "bjolp", 4),
("barman", "blind", 6),
("barman", "celmcut", 4),
("barman", "comp2", 7),
("barman", "ipdb", 4),
("barman", "lmcut", 0),
("barman", "mas1", 4),
("barman", "mas2", 4),
("barman", "miasm", 5),
("barman", "sccdfp", 4),
("barman", "scorpion", 4),
("barman", "symba1", 12),
("barman", "symba2", 12),
("blocks", "bjolp", 26),
("blocks", "blind", 18),
("blocks", "celmcut", 28),
("blocks", "comp2", 30),
("blocks", "ipdb", 28),
("blocks", "lmcut", 28),
("blocks", "mas1", 28),
("blocks", "mas2", 20),
("blocks", "miasm", 25),
("blocks", "sccdfp", 27),
("blocks", "scorpion", 28),
("blocks", "symba1", 30),
("blocks", "symba2", 30),
("childsnack", "bjolp", 0),
("childsnack", "blind", 5),
("childsnack", "celmcut", 6),
("childsnack", "comp2", 0),
("childsnack", "ipdb", 6),
("childsnack", "lmcut", 0),
("childsnack", "mas1", 0),
("childsnack", "mas2", 0),
("childsnack", "miasm", 5),
("childsnack", "sccdfp", 6),
("childsnack", "scorpion", 0),
("childsnack", "symba1", 3),
("childsnack", "symba2", 2),
("depot", "bjolp", 7),
("depot", "blind", 5),
("depot", "celmcut", 7),
("depot", "comp2", 6),
("depot", "ipdb", 9),
("depot", "lmcut", 6),
("depot", "mas1", 7),
("depot", "mas2", 6),
("depot", "miasm", 7),
("depot", "sccdfp", 8),
("depot", "scorpion", 13),
("depot", "symba1", 6),
("depot", "symba2", 6),
("driverlog", "bjolp", 14),
("driverlog", "blind", 7),
("driverlog", "celmcut", 13),
("driverlog", "comp2", 14),
("driverlog", "ipdb", 13),
("driverlog", "lmcut", 13),
("driverlog", "mas1", 13),
("driverlog", "mas2", 13),
("driverlog", "miasm", 12),
("driverlog", "sccdfp", 12),
("driverlog", "scorpion", 15),
("driverlog", "symba1", 12),
("driverlog", "symba2", 12),
("floortile", "bjolp", 2),
("floortile", "blind", 16),
("floortile", "celmcut", 30),
("floortile", "comp2", 31),
("floortile", "ipdb", 15),
("floortile", "lmcut", 9),
("floortile", "mas1", 3),
("floortile", "mas2", 13),
("floortile", "miasm", 21),
("floortile", "sccdfp", 16),
("floortile", "scorpion", 12),
("floortile", "symba1", 34),
("floortile", "symba2", 34),
("gripper", "bjolp", 7),
("gripper", "blind", 20),
("gripper", "celmcut", 20),
("gripper", "comp2", 18),
("gripper", "ipdb", 20),
("gripper", "lmcut", 6),
("gripper", "mas1", 8),
("gripper", "mas2", 20),
("gripper", "miasm", 20),
("gripper", "sccdfp", 20),
("gripper", "scorpion", 7),
("gripper", "symba1", 20),
("gripper", "symba2", 20),
("hiking", "bjolp", 9),
("hiking", "blind", 14),
("hiking", "celmcut", 11),
("hiking", "comp2", 13),
("hiking", "ipdb", 15),
("hiking", "lmcut", 8),
("hiking", "mas1", 11),
("hiking", "mas2", 12),
("hiking", "miasm", 15),
("hiking", "sccdfp", 15),
("hiking", "scorpion", 12),
("hiking", "symba1", 14),
("hiking", "symba2", 14),
("miconic-strips", "bjolp", 142),
("miconic-strips", "blind", 50),
("miconic-strips", "celmcut", 141),
("miconic-strips", "comp2", 85),
("miconic-strips", "ipdb", 53),
("miconic-strips", "lmcut", 140),
("miconic-strips", "mas1", 50),
("miconic-strips", "mas2", 77),
("miconic-strips", "miasm", 55),
("miconic-strips", "sccdfp", 79),
("miconic-strips", "scorpion", 125),
("miconic-strips", "symba1", 100),
("miconic-strips", "symba2", 98),
("parking", "bjolp", 3),
("parking", "blind", 0),
("parking", "celmcut", 1),
("parking", "comp2", 1),
("parking", "ipdb", 11),
("parking", "lmcut", 2),
("parking", "mas1", 13),
("parking", "mas2", 1),
("parking", "miasm", 0),
("parking", "sccdfp", 6),
("parking", "scorpion", 12),
("parking", "symba1", 1),
("parking", "symba2", 1),
("rovers", "bjolp", 8),
("rovers", "blind", 6),
("rovers", "celmcut", 9),
("rovers", "comp2", 12),
("rovers", "ipdb", 9),
("rovers", "lmcut", 7),
("rovers", "mas1", 6),
("rovers", "mas2", 8),
("rovers", "miasm", 9),
("rovers", "sccdfp", 9),
("rovers", "scorpion", 10),
("rovers", "symba1", 12),
("rovers", "symba2", 12),
("satellite", "bjolp", 7),
("satellite", "blind", 6),
("satellite", "celmcut", 14),
("satellite", "comp2", 7),
("satellite", "ipdb", 7),
("satellite", "lmcut", 7),
("satellite", "mas1", 6),
("satellite", "mas2", 6),
("satellite", "miasm", 7),
("satellite", "sccdfp", 9),
("satellite", "scorpion", 8),
("satellite", "symba1", 9),
("satellite", "symba2", 9),
("tpp", "bjolp", 6),
("tpp", "blind", 6),
("tpp", "celmcut", 7),
("tpp", "comp2", 12),
("tpp", "ipdb", 6),
("tpp", "lmcut", 6),
("tpp", "mas1", 6),
("tpp", "mas2", 7),
("tpp", "miasm", 8),
("tpp", "sccdfp", 9),
("tpp", "scorpion", 7),
("tpp", "symba1", 8),
("tpp", "symba2", 8),
("trucks", "bjolp", 7),
("trucks", "blind", 6),
("trucks", "celmcut", 10),
("trucks", "comp2", 9),
("trucks", "ipdb", 9),
("trucks", "lmcut", 9),
("trucks", "mas1", 6),
("trucks", "mas2", 6),
("trucks", "miasm", 10),
("trucks", "sccdfp", 7),
("trucks", "scorpion", 12),
("trucks", "symba1", 11),
("trucks", "symba2", 11),
("visitall", "bjolp", 14),
("visitall", "blind", 12),
("visitall", "celmcut", 14),
("visitall", "comp2", 24),
("visitall", "ipdb", 28),
("visitall", "lmcut", 15),
("visitall", "mas1", 28),
("visitall", "mas2", 13),
("visitall", "miasm", 13),
("visitall", "sccdfp", 13),
("visitall", "scorpion", 29),
("visitall", "symba1", 18),
("visitall", "symba2", 18),
("woodworking", "bjolp", 21),
("woodworking", "blind", 29),
("woodworking", "celmcut", 49),
("woodworking", "comp2", 38),
("woodworking", "ipdb", 30),
("woodworking", "lmcut", 25),
("woodworking", "mas1", 23),
("woodworking", "mas2", 19),
("woodworking", "miasm", 45),
("woodworking", "sccdfp", 49),
("woodworking", "scorpion", 50),
("woodworking", "symba1", 38),
("woodworking", "symba2", 38),
("zenotravel", "bjolp", 10),
("zenotravel", "blind", 7),
("zenotravel", "celmcut", 12),
("zenotravel", "comp2", 10),
("zenotravel", "ipdb", 11),
("zenotravel", "lmcut", 11),
("zenotravel", "mas1", 10),
("zenotravel", "mas2", 12),
("zenotravel", "miasm", 10),
("zenotravel", "sccdfp", 11),
("zenotravel", "scorpion", 13),
("zenotravel", "symba1", 10),
("zenotravel", "symba2", 10),
]

NEW_BASELINE = [
("barman", "bjolp", 6),
("barman", "blind", 7),
("barman", "celmcut", 8),
("barman", "comp2", 10),
("barman", "ipdb", 10),
("barman", "lmcut", 6),
("barman", "mas1", 6),
("barman", "mas2", 6),
("barman", "miasm", 11),
("barman", "sccdfp", 9),
("barman", "scorpion", 9),
("barman", "symba1", 10),
("barman", "symba2", 10),
("blocksworld", "bjolp", 5),
("blocksworld", "blind", 3),
("blocksworld", "celmcut", 5),
("blocksworld", "comp2", 5),
("blocksworld", "ipdb", 5),
("blocksworld", "lmcut", 5),
("blocksworld", "mas1", 5),
("blocksworld", "mas2", 4),
("blocksworld", "miasm", 4),
("blocksworld", "sccdfp", 5),
("blocksworld", "scorpion", 6),
("blocksworld", "symba1", 5),
("blocksworld", "symba2", 5),
("childsnack", "bjolp", 2),
("childsnack", "blind", 8),
("childsnack", "celmcut", 8),
("childsnack", "comp2", 3),
("childsnack", "ipdb", 8),
("childsnack", "lmcut", 3),
("childsnack", "mas1", 3),
("childsnack", "mas2", 3),
("childsnack", "miasm", 8),
("childsnack", "sccdfp", 8),
("childsnack", "scorpion", 3),
("childsnack", "symba1", 6),
("childsnack", "symba2", 7),
("depots", "bjolp", 32),
("depots", "blind", 23),
("depots", "celmcut", 32),
("depots", "comp2", 19),
("depots", "ipdb", 32),
("depots", "lmcut", 22),
("depots", "mas1", 23),
("depots", "mas2", 25),
("depots", "miasm", 25),
("depots", "sccdfp", 29),
("depots", "scorpion", 32),
("depots", "symba1", 24),
("depots", "symba2", 24),
("driverlog", "bjolp", 12),
("driverlog", "blind", 7),
("driverlog", "celmcut", 11),
("driverlog", "comp2", 13),
("driverlog", "ipdb", 12),
("driverlog", "lmcut", 11),
("driverlog", "mas1", 12),
("driverlog", "mas2", 13),
("driverlog", "miasm", 12),
("driverlog", "sccdfp", 13),
("driverlog", "scorpion", 14),
("driverlog", "symba1", 12),
("driverlog", "symba2", 12),
("floortile", "bjolp", 9),
("floortile", "blind", 16),
("floortile", "celmcut", 22),
("floortile", "comp2", 21),
("floortile", "ipdb", 16),
("floortile", "lmcut", 14),
("floortile", "mas1", 10),
("floortile", "mas2", 13),
("floortile", "miasm", 20),
("floortile", "sccdfp", 16),
("floortile", "scorpion", 15),
("floortile", "symba1", 23),
("floortile", "symba2", 23),
("gripper", "bjolp", 5),
("gripper", "blind", 30),
("gripper", "celmcut", 30),
("gripper", "comp2", 29),
("gripper", "ipdb", 30),
("gripper", "lmcut", 3),
("gripper", "mas1", 6),
("gripper", "mas2", 30),
("gripper", "miasm", 30),
("gripper", "sccdfp", 30),
("gripper", "scorpion", 5),
("gripper", "symba1", 30),
("gripper", "symba2", 30),
("hiking", "bjolp", 30),
("hiking", "blind", 0),
("hiking", "celmcut", 0),
("hiking", "comp2", 0),
("hiking", "ipdb", 0),
("hiking", "lmcut", 30),
("hiking", "mas1", 30),
("hiking", "mas2", 30),
("hiking", "miasm", 0),
("hiking", "sccdfp", 0),
("hiking", "scorpion", 0),
("hiking", "symba1", 0),
("hiking", "symba2", 0),
("miconic-strips", "bjolp", 32),
("miconic-strips", "blind", 26),
("miconic-strips", "celmcut", 32),
("miconic-strips", "comp2", 32),
("miconic-strips", "ipdb", 32),
("miconic-strips", "lmcut", 32),
("miconic-strips", "mas1", 30),
("miconic-strips", "mas2", 32),
("miconic-strips", "miasm", 32),
("miconic-strips", "sccdfp", 32),
("miconic-strips", "scorpion", 32),
("miconic-strips", "symba1", 32),
("miconic-strips", "symba2", 32),
("parking", "bjolp", 4),
("parking", "blind", 4),
("parking", "celmcut", 4),
("parking", "comp2", 4),
("parking", "ipdb", 6),
("parking", "lmcut", 4),
("parking", "mas1", 6),
("parking", "mas2", 4),
("parking", "miasm", 4),
("parking", "sccdfp", 5),
("parking", "scorpion", 6),
("parking", "symba1", 4),
("parking", "symba2", 4),
("rover", "bjolp", 32),
("rover", "blind", 23),
("rover", "celmcut", 32),
("rover", "comp2", 32),
("rover", "ipdb", 32),
("rover", "lmcut", 32),
("rover", "mas1", 29),
("rover", "mas2", 31),
("rover", "miasm", 32),
("rover", "sccdfp", 32),
("rover", "scorpion", 32),
("rover", "symba1", 32),
("rover", "symba2", 32),
("satellite", "bjolp", 18),
("satellite", "blind", 15),
("satellite", "celmcut", 30),
("satellite", "comp2", 29),
("satellite", "ipdb", 27),
("satellite", "lmcut", 20),
("satellite", "mas1", 12),
("satellite", "mas2", 20),
("satellite", "miasm", 28),
("satellite", "sccdfp", 27),
("satellite", "scorpion", 21),
("satellite", "symba1", 30),
("satellite", "symba2", 30),
("tpp", "bjolp", 3),
("tpp", "blind", 3),
("tpp", "celmcut", 3),
("tpp", "comp2", 4),
("tpp", "ipdb", 3),
("tpp", "lmcut", 3),
("tpp", "mas1", 3),
("tpp", "mas2", 3),
("tpp", "miasm", 3),
("tpp", "sccdfp", 3),
("tpp", "scorpion", 3),
("tpp", "symba1", 5),
("tpp", "symba2", 5),
("trucks", "bjolp", 0),
("trucks", "blind", 0),
("trucks", "celmcut", 0),
("trucks", "comp2", 0),
("trucks", "ipdb", 0),
("trucks", "lmcut", 0),
("trucks", "mas1", 0),
("trucks", "mas2", 0),
("trucks", "miasm", 0),
("trucks", "sccdfp", 0),
("trucks", "scorpion", 0),
("trucks", "symba1", 0),
("trucks", "symba2", 0),
("visitall", "bjolp", 5),
("visitall", "blind", 4),
("visitall", "celmcut", 5),
("visitall", "comp2", 6),
("visitall", "ipdb", 5),
("visitall", "lmcut", 5),
("visitall", "mas1", 5),
("visitall", "mas2", 5),
("visitall", "miasm", 5),
("visitall", "sccdfp", 5),
("visitall", "scorpion", 5),
("visitall", "symba1", 5),
("visitall", "symba2", 5),
("woodworking", "bjolp", 5),
("woodworking", "blind", 12),
("woodworking", "celmcut", 12),
("woodworking", "comp2", 7),
("woodworking", "ipdb", 8),
("woodworking", "lmcut", 5),
("woodworking", "mas1", 5),
("woodworking", "mas2", 5),
("woodworking", "miasm", 12),
("woodworking", "sccdfp", 13),
("woodworking", "scorpion", 12),
("woodworking", "symba1", 8),
("woodworking", "symba2", 8),
("zenotravel", "bjolp", 21),
("zenotravel", "blind", 7),
("zenotravel", "celmcut", 20),
("zenotravel", "comp2", 21),
("zenotravel", "ipdb", 20),
("zenotravel", "lmcut", 19),
("zenotravel", "mas1", 19),
("zenotravel", "mas2", 22),
("zenotravel", "miasm", 19),
("zenotravel", "sccdfp", 21),
("zenotravel", "scorpion", 26),
("zenotravel", "symba1", 21),
("zenotravel", "symba2", 21),
]

NEW_SART = [
("barman", "bjolp", 6),
("barman", "blind", 4),
("barman", "celmcut", 5),
("barman", "comp2", 6),
("barman", "ipdb", 7),
("barman", "lmcut", 4),
("barman", "mas1", 4),
("barman", "mas2", 4),
("barman", "miasm", 6),
("barman", "sccdfp", 6),
("barman", "scorpion", 7),
("barman", "symba1", 7),
("barman", "symba2", 7),
("blocksworld", "bjolp", 7),
("blocksworld", "blind", 3),
("blocksworld", "celmcut", 7),
("blocksworld", "comp2", 7),
("blocksworld", "ipdb", 8),
("blocksworld", "lmcut", 8),
("blocksworld", "mas1", 9),
("blocksworld", "mas2", 8),
("blocksworld", "miasm", 6),
("blocksworld", "sccdfp", 9),
("blocksworld", "scorpion", 7),
("blocksworld", "symba1", 7),
("blocksworld", "symba2", 7),
("childsnack", "bjolp", 3),
("childsnack", "blind", 11),
("childsnack", "celmcut", 11),
("childsnack", "comp2", 4),
("childsnack", "ipdb", 11),
("childsnack", "lmcut", 4),
("childsnack", "mas1", 4),
("childsnack", "mas2", 4),
("childsnack", "miasm", 11),
("childsnack", "sccdfp", 11),
("childsnack", "scorpion", 4),
("childsnack", "symba1", 10),
("childsnack", "symba2", 9),
("depots", "bjolp", 8),
("depots", "blind", 8),
("depots", "celmcut", 9),
("depots", "comp2", 8),
("depots", "ipdb", 10),
("depots", "lmcut", 7),
("depots", "mas1", 8),
("depots", "mas2", 8),
("depots", "miasm", 9),
("depots", "sccdfp", 9),
("depots", "scorpion", 11),
("depots", "symba1", 9),
("depots", "symba2", 9),
("driverlog", "bjolp", 11),
("driverlog", "blind", 4),
("driverlog", "celmcut", 11),
("driverlog", "comp2", 13),
("driverlog", "ipdb", 13),
("driverlog", "lmcut", 11),
("driverlog", "mas1", 13),
("driverlog", "mas2", 14),
("driverlog", "miasm", 12),
("driverlog", "sccdfp", 12),
("driverlog", "scorpion", 13),
("driverlog", "symba1", 12),
("driverlog", "symba2", 12),
("floortile", "bjolp", 5),
("floortile", "blind", 12),
("floortile", "celmcut", 17),
("floortile", "comp2", 18),
("floortile", "ipdb", 12),
("floortile", "lmcut", 9),
("floortile", "mas1", 4),
("floortile", "mas2", 8),
("floortile", "miasm", 16),
("floortile", "sccdfp", 12),
("floortile", "scorpion", 10),
("floortile", "symba1", 20),
("floortile", "symba2", 20),
("gripper", "bjolp", 7),
("gripper", "blind", 30),
("gripper", "celmcut", 30),
("gripper", "comp2", 29),
("gripper", "ipdb", 30),
("gripper", "lmcut", 5),
("gripper", "mas1", 8),
("gripper", "mas2", 30),
("gripper", "miasm", 30),
("gripper", "sccdfp", 30),
("gripper", "scorpion", 7),
("gripper", "symba1", 30),
("gripper", "symba2", 30),
("hiking", "bjolp", 5),
("hiking", "blind", 15),
("hiking", "celmcut", 9),
("hiking", "comp2", 14),
("hiking", "ipdb", 24),
("hiking", "lmcut", 4),
("hiking", "mas1", 8),
("hiking", "mas2", 9),
("hiking", "miasm", 16),
("hiking", "sccdfp", 21),
("hiking", "scorpion", 9),
("hiking", "symba1", 19),
("hiking", "symba2", 19),
("miconic-strips", "bjolp", 9),
("miconic-strips", "blind", 3),
("miconic-strips", "celmcut", 8),
("miconic-strips", "comp2", 5),
("miconic-strips", "ipdb", 3),
("miconic-strips", "lmcut", 8),
("miconic-strips", "mas1", 2),
("miconic-strips", "mas2", 4),
("miconic-strips", "miasm", 4),
("miconic-strips", "sccdfp", 5),
("miconic-strips", "scorpion", 8),
("miconic-strips", "symba1", 6),
("miconic-strips", "symba2", 6),
("parking", "bjolp", 4),
("parking", "blind", 4),
("parking", "celmcut", 4),
("parking", "comp2", 5),
("parking", "ipdb", 5),
("parking", "lmcut", 4),
("parking", "mas1", 5),
("parking", "mas2", 4),
("parking", "miasm", 4),
("parking", "sccdfp", 5),
("parking", "scorpion", 5),
("parking", "symba1", 4),
("parking", "symba2", 4),
("rover", "bjolp", 6),
("rover", "blind", 1),
("rover", "celmcut", 9),
("rover", "comp2", 9),
("rover", "ipdb", 6),
("rover", "lmcut", 9),
("rover", "mas1", 3),
("rover", "mas2", 5),
("rover", "miasm", 6),
("rover", "sccdfp", 5),
("rover", "scorpion", 10),
("rover", "symba1", 9),
("rover", "symba2", 9),
("satellite", "bjolp", 3),
("satellite", "blind", 3),
("satellite", "celmcut", 5),
("satellite", "comp2", 5),
("satellite", "ipdb", 4),
("satellite", "lmcut", 3),
("satellite", "mas1", 3),
("satellite", "mas2", 5),
("satellite", "miasm", 4),
("satellite", "sccdfp", 4),
("satellite", "scorpion", 4),
("satellite", "symba1", 5),
("satellite", "symba2", 5),
("tpp", "bjolp", 2),
("tpp", "blind", 2),
("tpp", "celmcut", 5),
("tpp", "comp2", 5),
("tpp", "ipdb", 4),
("tpp", "lmcut", 3),
("tpp", "mas1", 2),
("tpp", "mas2", 3),
("tpp", "miasm", 5),
("tpp", "sccdfp", 6),
("tpp", "scorpion", 3),
("tpp", "symba1", 3),
("tpp", "symba2", 4),
("trucks", "bjolp", 1),
("trucks", "blind", 1),
("trucks", "celmcut", 1),
("trucks", "comp2", 1),
("trucks", "ipdb", 1),
("trucks", "lmcut", 1),
("trucks", "mas1", 1),
("trucks", "mas2", 1),
("trucks", "miasm", 1),
("trucks", "sccdfp", 1),
("trucks", "scorpion", 1),
("trucks", "symba1", 1),
("trucks", "symba2", 1),
("visitall", "bjolp", 3),
("visitall", "blind", 2),
("visitall", "celmcut", 3),
("visitall", "comp2", 3),
("visitall", "ipdb", 3),
("visitall", "lmcut", 3),
("visitall", "mas1", 3),
("visitall", "mas2", 3),
("visitall", "miasm", 3),
("visitall", "sccdfp", 3),
("visitall", "scorpion", 3),
("visitall", "symba1", 3),
("visitall", "symba2", 3),
("woodworking", "bjolp", 2),
("woodworking", "blind", 5),
("woodworking", "celmcut", 5),
("woodworking", "comp2", 3),
("woodworking", "ipdb", 4),
("woodworking", "lmcut", 2),
("woodworking", "mas1", 3),
("woodworking", "mas2", 3),
("woodworking", "miasm", 5),
("woodworking", "sccdfp", 5),
("woodworking", "scorpion", 5),
("woodworking", "symba1", 4),
("woodworking", "symba2", 4),
("zenotravel", "bjolp", 11),
("zenotravel", "blind", 7),
("zenotravel", "celmcut", 14),
("zenotravel", "comp2", 12),
("zenotravel", "ipdb", 9),
("zenotravel", "lmcut", 11),
("zenotravel", "mas1", 13),
("zenotravel", "mas2", 13),
("zenotravel", "miasm", 9),
("zenotravel", "sccdfp", 9),
("zenotravel", "scorpion", 18),
("zenotravel", "symba1", 13),
("zenotravel", "symba2", 14),
]

names = ["old", "new_baseline", "new_sart"]

sets = {}
dicts = {}
domains = None
planners = None
for name in names:
    original_list = globals()[name.upper()]
    sanitized = [(DOMAIN_RENAMINGS[domain], algo, coverage) for domain, algo, coverage in original_list]
    new_set = set(sanitized)
    sets[name] = new_set

    new_domains = sorted({domain for domain, _, _ in sanitized})
    assert domains is None or domains == new_domains
    domains = new_domains

    new_planners = sorted({planner for _, planner, _ in sanitized})
    assert planners is None or planners == new_planners
    planners = new_planners

    dic = defaultdict(dict)
    for domain, algo, coverage in sanitized:
        dic[domain][algo] = coverage
    dicts[name] = dic

assert len({len(s) for s in sets.values()}) == 1

table = Table(title="different scores", min_wins=False)
table.set_column_order(names)
for name in names:
    different_coverage_scores = defaultdict(set)
    for domain, algo, coverage in sets[name]:
        different_coverage_scores[domain].add(coverage)
    for domain, different_scores in different_coverage_scores.items():
        table.add_cell(domain, name, len(different_scores))

tables = [table]

for name1, name2 in itertools.combinations(names, 2):
    set1 = sets[name1]
    set2 = sets[name2]

    table = Table(title=f"{name1} vs. {name2}", min_wins=None)
    outcomes = [f"only {name1}", f"only {name2}"]
    table.set_column_order(outcomes)

    for domain in domains:
        result = {outcome: 0 for outcome in outcomes}
        for planner1, planner2 in itertools.permutations(planners, 2):
            coverage11 = dicts[name1][domain][planner1]
            coverage12 = dicts[name1][domain][planner2]
            coverage21 = dicts[name2][domain][planner1]
            coverage22 = dicts[name2][domain][planner2]
            if coverage11 > coverage12 and coverage21 <= coverage22:
                result[f"only {name1}"] += 1
            elif coverage21 > coverage22 and coverage11 <= coverage12:
                result[f"only {name2}"] += 1
        for key, value in result.items():
            table.add_cell(domain, key, value)

    tables.append(table)

def render_txt2tags(text, target="xhtml"):
    from lab.reports import markup
    doc = markup.Document()
    doc.add_text(text)
    return doc.render(target=target)

print(render_txt2tags("\n\n\n".join(str(table) for table in tables)))
