(DEFINE (PROBLEM ADD-PAREN-3-19062018191751)
  (:DOMAIN EXCEL)
  (:OBJECTS
	SPACE HYPH COLON DOT LPAR RPAR - LIMITER
	A B C D E F G H I J K L M N O P Q R S T U V W X Y Z N0 N1 N2 N3 N4 N5 N6 N7 N8 N9 - CHAR
	STR - INPUT
	RES - OUTPUT
	STR-VAR - INPUT-VARIABLE
	 I2 I3 I4 - INDEX 
  )
  (:INIT
	( HIINDEX STR I3 )
	( LOINDEX STR I0 )
	( SIZE STR I3 )
	( SIZE RES I0 )
	( INPUT-ASSIGNMENT STR-VAR STR )
	( NEXT I0 I1 )
	( NEXT I1 I2 )
	( NEXT I2 I3 )
	( NEXT I3 I4 )
	( ASSIGNMENT STR I0 LPAR )
	( ASSIGNMENT STR I1 A )
	( ASSIGNMENT STR I2 J )
  )
  (:GOAL
	( AND
	( ASSIGNMENT RES I0 LPAR )
	( ASSIGNMENT RES I1 A )
	( ASSIGNMENT RES I2 J )
	( ASSIGNMENT RES I3 RPAR )
	)
  )
)