; Domain designed by Yannis Dimopoulos, Alfonso Gerevini and Alessandro Saetti
; This file has been automatically generated by the generator available from
; http://zeus.ing.unibs.it/ipc-5/generators/index.html

(define (problem Pathways-Problem)
(:domain Pathways-Propositional)
(:objects
	l0 - level
	l1 - level
	l2 - level
	l3 - level
	l4 - level)


(:init
	(possible pRb-E2F4p1-DP12)
	(possible PCNA)
	(possible p53p1)
	(possible HDAC1)
	(association-reaction HDAC1 pRb-E2F4p1-DP12 HDAC1-pRb-E2F4p1-DP12)
	(association-reaction p21 Gadd45 p21-Gadd45)
	(synthesis-reaction p53p1 c-Fos) 
	(synthesis-reaction p53p1 Gadd45) 
	(synthesis-reaction p53p1 Mdm2) 
	(synthesis-reaction p53p1 p21) 
	(association-reaction PCNA Gadd45 PCNA-Gadd45)
	(association-reaction PCNA p21 PCNA-p21)
	(num-subs l0)
	(next l1 l0)
	(next l2 l1)
	(next l3 l2)
	(next l4 l3))


(:goal
	(and
	(goal1)
	(goal2)
	(goal3)
	(goal4)))

)
