#! /bin/bash

set -xeuo pipefail

g++ -O6 -m32 -c -x c++ hsp_f.ccx
g++ -O6 -m32 -c -x c++ rational.ccx
g++ -O6 -m32 -c -x c++ index_type.ccx
g++ -O6 -m32 -c -x c++ name.ccx
g++ -O6 -m32 -c -x c++ ptr_table.ccx
g++ -O6 -m32 -c -x c++ char_map.ccx
g++ -O6 -m32 -c -x c++ string_table.ccx
g++ -O6 -m32 -c -x c++ numeric_type.ccx
g++ -O6 -m32 -c -x c++ graph.ccx
g++ -O6 -m32 -c -x c++ enumerators.ccx
g++ -O6 -m32 -c -x c++ rng.ccx
g++ -O6 -m32 -c -x c++ problem.ccx
g++ -O6 -m32 -c -x c++ soft.ccx
g++ -O6 -m32 -c -x c++ search.ccx
g++ -O6 -m32 -c -x c++ heuristic.ccx
g++ -O6 -m32 -c -x c++ stats.ccx
g++ -O6 -m32 -c -x c++ exec.ccx
g++ -O6 -m32 -c -x c++ plans.ccx
g++ -O6 -m32 -c -x c++ preprocess.ccx
g++ -O6 -m32 -c -x c++ cost_table.ccx
g++ -O6 -m32 -c -x c++ additive.ccx
g++ -O6 -m32 -c -x c++ atomset.ccx
g++ -O6 -m32 -c -x c++ resource.ccx
g++ -O6 -m32 -c -x c++ seq_reg.ccx
g++ -O6 -m32 -c -x c++ forward.ccx
g++ -O6 -m32 -c -x c++ search_base.ccx
g++ -O6 -m32 -c -x c++ hashtable.ccx
g++ -O6 -m32 -c -x c++ ida.ccx
g++ -O6 -m32 -c -x c++ nodeset.ccx
g++ -O6 -m32 -c -x c++ bfs.ccx
g++ -O6 -m32 -c -x c++ base.ccx
g++ -O6 -m32 -c -x c++ parser.ccx
g++ -O6 -m32 -c -x c++ grammar.ccx
g++ -O6 -m32 -c -x c++ scanner.ccx
g++ -O6 -m32 -o hsp_f  hsp_f.o  rational.o  index_type.o  name.o  ptr_table.o  char_map.o  string_table.o  numeric_type.o  graph.o  enumerators.o  rng.o  problem.o  soft.o  search.o  heuristic.o  stats.o  exec.o  plans.o  preprocess.o  cost_table.o  additive.o  atomset.o  resource.o  seq_reg.o  forward.o  search_base.o  hashtable.o  ida.o  nodeset.o  bfs.o  base.o  parser.o  grammar.o  scanner.o
